/**
 * THE BRIEFING — the section of The Edit that sits directly below "What to
 * acquire next".
 *
 * The free list above it is visibly the INPUT: atomic gaps, ranked, each one
 * a link through to The Rail. The Briefing is visibly the NEXT STEP — the
 * same gap data read a second time for the throughline running through it,
 * and compared against the last Briefing so it can say what has closed since
 * (briefing.ts holds that reasoning and the season memory).
 *
 * It is deliberately NOT styled like the rest of The Edit. No grid, no
 * table, no hairline rows: a single wide column of serif prose at ~640px,
 * a small uppercase dateline and one document heading. It should read as the
 * thing written for you, not another dashboard module — which is also why
 * it carries an export: this is the one artifact in the app someone would
 * plausibly keep or send on.
 *
 * THE EXPAND IS THE TRIGGER. There is no "generate" button. The Briefing
 * sits inside an accordion in The Edit (beau-tab.tsx) and this component is
 * mounted the first time that section is opened — whereupon it shows the
 * Briefing this user already has, or writes the first one. That is the same
 * fetch-or-reason contract Beau's verdict and his other assessments use.
 *
 * TWO STATES:
 *   1. Writing — the walnut card, while Beau draws the season together.
 *   2. The document — paper, dateline, heading, the synthesis, "Since last
 *      time" (from the second Briefing onward only), the considered path
 *      forward, and the Regenerate / Save as PDF actions.
 *
 * v1 is UNLOCKED for everyone — no paywall state here by design.
 */
import { useEffect, useRef, useState } from 'react';
import { Download, Loader2, RefreshCw } from 'lucide-react';
import { typography } from '../../lib/colors';
import type { BeauAssessment } from './beau-assessment';
import type { StyleProfile, WardrobePiece } from './profile-data';
import { openRailForGap } from './coverage-map';
import {
  canGenerateBriefing,
  exportBriefingDocument,
  fetchBriefings,
  generateBriefing,
  seasonHasTurned,
  type BriefingRecord,
} from './briefing.ts';

// The document's own type scale — a wide single column, serif body, and
// small uppercase datelines set in the site's own heading face (the same
// Cormorant/Lora pairing as everywhere else — no monospace anywhere).
const DOC_WIDTH = '640px';
const WALNUT = '#241a12';
const CREAM = '#f6f0e5';
// Every accent and label on this document is the app's oxblood. Gold belongs
// to Beau's verdict band and nowhere else on The Edit.
const OXBLOOD = '#8b3a3a';

const kicker: React.CSSProperties = {
  fontFamily: 'var(--space-font-heading)',
  fontSize: '12px',
  letterSpacing: '0.16em',
  textTransform: 'uppercase',
};

const prose: React.CSSProperties = {
  fontFamily: 'var(--space-font-family)',
  fontSize: '15px',
  lineHeight: 1.75,
  maxWidth: DOC_WIDTH,
};

/** Remembers the season we already auto-generated for, so the turn of a
 * season spends exactly one call — never one per page load. */
const AUTO_SEASON_KEY = 'ethaion_briefing_auto_season';

function alreadyAutoGenerated(season: string): boolean {
  try {
    return localStorage.getItem(AUTO_SEASON_KEY) === season;
  } catch {
    return false;
  }
}

function markAutoGenerated(season: string): void {
  try {
    localStorage.setItem(AUTO_SEASON_KEY, season);
  } catch { /* storage unavailable — the worst case is one extra pass */ }
}

// ---------------------------------------------------------------------------
// State 1 — Beau is writing it. Reached by expanding the section; there is
// no call to action, because the expand IS the call to action.
// ---------------------------------------------------------------------------

function BriefingWriting({ phase }: { phase: string }) {
  return (
    <div style={{ background: WALNUT, padding: '32px' }} aria-live="polite">
      {/* On walnut the oxblood accent would disappear, so the label is cream
          held back instead — the accent proper belongs on the paper states. */}
      <p style={{ ...kicker, color: CREAM, opacity: 0.6, marginBottom: '12px' }}>Briefing</p>
      <h3 style={{ fontFamily: 'var(--space-font-heading)', fontWeight: 400, color: CREAM, fontSize: '26px', lineHeight: 1.2, marginBottom: '16px' }}>
        Beau is drawing the season together.
      </h3>
      <p className="inline-flex items-center gap-2" style={{ fontFamily: 'var(--space-font-family)', fontSize: '14px', color: CREAM, opacity: 0.8 }}>
        <Loader2 className="w-4 h-4 animate-spin" aria-hidden="true" />
        {phase}
      </p>
    </div>
  );
}

/** Nothing on the page yet — either Beau has not finished reading the
 * wardrobe, or the last attempt fell over. Both say so plainly on paper,
 * and the second offers the way back. */
function BriefingNotice({ message, onRetry, busy }: { message: string; onRetry?: () => void; busy: boolean }) {
  return (
    <div className="bg-[var(--space-surface-card)] border border-[var(--space-border-default)]" style={{ padding: '28px 32px' }}>
      <p style={{ ...kicker, color: OXBLOOD, marginBottom: '10px' }}>Briefing</p>
      <p className={typography.color.secondary} style={{ ...prose, fontSize: '14px', margin: 0 }}>
        {message}
      </p>
      {onRetry && (
        <button
          type="button"
          onClick={onRetry}
          disabled={busy}
          className="inline-flex items-center gap-1.5 min-h-[44px] hover:opacity-70 transition-opacity disabled:opacity-60"
          style={{ fontFamily: 'var(--space-font-family)', fontSize: '12px', color: OXBLOOD, marginTop: '8px' }}
        >
          {busy ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <RefreshCw className="w-3.5 h-3.5" />}
          Try again
        </button>
      )}
    </div>
  );
}

// ---------------------------------------------------------------------------
// State 2 — the document.
// ---------------------------------------------------------------------------

function BriefingDocument({
  record,
  onRegenerate,
  busy,
  phase,
  history,
  onSelect,
}: {
  record: BriefingRecord;
  onRegenerate: () => void;
  busy: boolean;
  phase: string;
  history: BriefingRecord[];
  onSelect: (record: BriefingRecord) => void;
}) {
  const { sections } = record;
  const earlier = history.filter((item) => item.id !== record.id);

  return (
    <div
      className="bg-[var(--space-surface-card)] border border-[var(--space-border-default)]"
      style={{ padding: '40px 32px' }}
    >
      <p style={{ ...kicker, color: OXBLOOD, marginBottom: '10px' }}>
        Briefing — {record.seasonLabel}
      </p>
      <h3
        className={typography.color.primary}
        style={{ fontFamily: 'var(--space-font-heading)', fontWeight: 400, fontSize: '30px', lineHeight: 1.15, marginBottom: '26px' }}
      >
        {sections.heading}
      </h3>

      {/* The synthesis — the throughline, in prose. */}
      <p className={typography.color.primary} style={{ ...prose, marginBottom: '32px' }}>
        {sections.opening}
      </p>

      {/* Season memory — present from the second Briefing onward only. */}
      {sections.sinceLastTime && (
        <div style={{ borderLeft: `2px solid ${OXBLOOD}`, paddingLeft: '18px', marginBottom: '32px' }}>
          <p style={{ ...kicker, color: OXBLOOD, marginBottom: '8px' }}>
            Since last time
          </p>
          <p className={typography.color.secondary} style={{ ...prose, fontSize: '14px', lineHeight: 1.65, maxWidth: '600px' }}>
            {sections.sinceLastTime}
          </p>
        </div>
      )}

      <p style={{ ...kicker, color: OXBLOOD, marginBottom: '8px' }}>
        The considered path forward
      </p>
      <p className={typography.color.primary} style={{ ...prose, marginBottom: sections.referencedPieces.length > 0 ? '18px' : '32px' }}>
        {sections.pathForward}
      </p>

      {/* The pieces named above, in the order he sequenced them — each one
          opens The Rail on that gap, exactly as "What to acquire next" does. */}
      {sections.referencedPieces.length > 0 && (
        <p className={typography.color.secondary} style={{ fontFamily: 'var(--space-font-family)', fontSize: '13px', lineHeight: 1.7, maxWidth: DOC_WIDTH, marginBottom: '32px' }}>
          In that order, on The Rail:{' '}
          {sections.referencedPieces.map((piece, i) => (
            <span key={`${piece.label}-${i}`}>
              {i > 0 && <span aria-hidden="true"> · </span>}
              <button
                type="button"
                onClick={() => openRailForGap(piece.category || piece.label)}
                className="underline underline-offset-2 decoration-dotted hover:text-[var(--space-text-primary)] transition-colors"
                style={{ color: OXBLOOD }}
              >
                {piece.label}
              </button>
            </span>
          ))}
        </p>
      )}

      {/* Actions — regenerate, and the one thing here worth keeping. */}
      <div className="flex items-center gap-6 flex-wrap pt-4 border-t border-[var(--space-border-default)]">
        <button
          type="button"
          onClick={onRegenerate}
          disabled={busy}
          className="inline-flex items-center gap-1.5 min-h-[44px] sm:min-h-0 sm:py-2 hover:opacity-70 transition-opacity disabled:opacity-60"
          style={{ fontFamily: 'var(--space-font-family)', fontSize: '12px', color: OXBLOOD }}
        >
          {busy ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <RefreshCw className="w-3.5 h-3.5" />}
          {busy ? phase : 'Regenerate'}
        </button>
        <button
          type="button"
          onClick={() => exportBriefingDocument(record)}
          className="inline-flex items-center gap-1.5 min-h-[44px] sm:min-h-0 sm:py-2 hover:opacity-70 transition-opacity"
          style={{ fontFamily: 'var(--space-font-family)', fontSize: '12px', color: OXBLOOD }}
        >
          <Download className="w-3.5 h-3.5" />
          Save as PDF
        </button>
      </div>

      {/* The memory made visible — every Briefing he has been sent. */}
      {earlier.length > 0 && (
        <p className={`${typography.size.xs} ${typography.color.muted} mt-4`} style={{ fontFamily: 'var(--space-font-family)' }}>
          Earlier:{' '}
          {earlier.map((item, i) => (
            <span key={item.id}>
              {i > 0 && <span aria-hidden="true"> · </span>}
              <button
                type="button"
                onClick={() => onSelect(item)}
                className="underline underline-offset-2 decoration-dotted hover:text-[var(--space-text-primary)] transition-colors"
              >
                {item.seasonLabel}
              </button>
            </span>
          ))}
        </p>
      )}
    </div>
  );
}

// ---------------------------------------------------------------------------
// The section
// ---------------------------------------------------------------------------

export function Briefing({
  assessment,
  profile,
  pieces,
}: {
  assessment: BeauAssessment | null;
  profile: StyleProfile | null;
  pieces: WardrobePiece[];
}) {
  const [history, setHistory] = useState<BriefingRecord[]>([]);
  const [shown, setShown] = useState<BriefingRecord | null>(null);
  const [loaded, setLoaded] = useState(false);
  const [busy, setBusy] = useState(false);
  const [phase, setPhase] = useState('Writing\u2026');
  const [error, setError] = useState<string | null>(null);

  const autoRef = useRef(false);
  const firstRunRef = useRef(false);
  const inputsRef = useRef({ assessment, profile, pieces });
  inputsRef.current = { assessment, profile, pieces };

  useEffect(() => {
    let live = true;
    void fetchBriefings()
      .then((list) => {
        if (!live) return;
        setHistory(list);
        setShown(list[0] || null);
      })
      .finally(() => {
        if (live) setLoaded(true);
      });
    return () => {
      live = false;
    };
  }, []);

  /** `previous` undefined lets the generator re-read the history itself, so
   * a failed first fetch can never silently lose the season memory. */
  const write = (previous: BriefingRecord | null | undefined) => {
    const { assessment: a, profile: p, pieces: pc } = inputsRef.current;
    if (!a || busy) return;
    setBusy(true);
    setError(null);
    void generateBriefing({ assessment: a, profile: p, pieces: pc, previous, onPhase: setPhase })
      .then((record) => {
        setShown(record);
        setHistory((current) => [record, ...current.filter((item) => item.id !== record.id)]);
      })
      .catch((e: unknown) => {
        setError(e instanceof Error ? e.message : 'Beau couldn\u2019t write it just now — try again in a moment.');
      })
      .finally(() => setBusy(false));
  };

  const latest = history[0] || null;

  // THE TRIGGER. This component is only mounted once the accordion has been
  // expanded, so the moment the history read lands we either have a Briefing
  // to show or we write his first one — no button, no second tap.
  useEffect(() => {
    if (!loaded || firstRunRef.current || busy) return;
    if (latest) {
      firstRunRef.current = true;
      return;
    }
    if (!canGenerateBriefing(assessment)) return;
    firstRunRef.current = true;
    write(null);
  }, [loaded, latest, assessment, busy]);

  // A new season is the other moment the Briefing writes itself. Once per
  // season, only for someone who already has one, and only once Beau's read
  // of the wardrobe is in.
  useEffect(() => {
    if (!loaded || autoRef.current || busy) return;
    if (!latest || !canGenerateBriefing(assessment) || !seasonHasTurned(latest)) return;
    const season = latest.seasonLabel;
    if (alreadyAutoGenerated(season)) return;
    autoRef.current = true;
    markAutoGenerated(season);
    write(latest);
  }, [loaded, latest, assessment, busy]);

  if (!loaded) return <BriefingWriting phase="Beau is looking out his last Briefing…" />;

  if (shown) {
    return (
      <div>
        <BriefingDocument
          record={shown}
          onRegenerate={() => write(latest)}
          busy={busy}
          phase={phase}
          history={history}
          onSelect={setShown}
        />
        {error && <p className={`${typography.size.xs} text-[var(--space-semantic-warning)] mt-3`}>{error}</p>}
      </div>
    );
  }

  if (busy) return <BriefingWriting phase={phase} />;

  if (error) return <BriefingNotice message={error} onRetry={() => write(latest)} busy={busy} />;

  if (!canGenerateBriefing(assessment)) {
    return (
      <BriefingNotice
        message="Once Beau has read your wardrobe above, he can draw the season together here."
        busy={busy}
      />
    );
  }

  return <BriefingWriting phase="Beau is drawing the season together…" />;
}
