/**
 * GARMENT TYPE ENTRIES 2 of 4 — OUTERWEAR · FORMALWEAR.
 * One `gt(id, name, category, band, reach, cuts, colours, makers)` per line.
 * Assembled and indexed by garment-types.ts — import from THERE, not here.
 */
import { gt, C, SC, B, F, BT, OW, type GarmentType } from './garment-type-model';

export const GARMENT_TYPE_ENTRIES_2: GarmentType[] = [
  // ─── OUTERWEAR · blousons & jackets ───
  gt('harrington-jacket', 'Harrington Jacket', 'outerwear', '10-15', [C, SC], ['Regular', 'Slim'], ['Navy', 'Stone', 'Black', 'Burgundy'], ['Baracuta', 'Fred Perry', 'Grenfell', 'Private White V.C.']),
  gt('golfer-jacket', 'Golfer Jacket', 'outerwear', '10-15', [C, SC], ['Regular'], ['Stone', 'Navy', 'Tan'], ['Grenfell']),
  gt('ma1-bomber', 'MA-1 Bomber', 'outerwear', '5-10', [C], ['Regular', 'Slim'], ['Sage green', 'Black', 'Navy'], ['Alpha Industries', 'Buzz Rickson']),
  gt('a1-flight-jacket', 'A-1 Flight Jacket', 'outerwear', '10-15', [C], ['Regular'], ['Seal brown', 'Russet'], ['Buzz Rickson']),
  gt('a2-flight-jacket', 'A-2 Flight Jacket', 'outerwear', '5-10', [C], ['Regular'], ['Seal brown', 'Russet'], ['Buzz Rickson']),
  gt('g1-flight-jacket', 'G-1 Flight Jacket', 'outerwear', '5-10', [C], ['Regular'], ['Dark brown'], ['Buzz Rickson']),
  gt('b3-shearling-bomber', 'B-3 Shearling Bomber', 'outerwear', 'below-0', [C], ['Regular'], ['Seal brown', 'Dark tan'], ['Buzz Rickson']),
  gt('b10-flight-jacket', 'B-10 Flight Jacket', 'outerwear', '0-5', [C], ['Regular'], ['Olive drab', 'Navy'], ['Buzz Rickson']),
  gt('suede-blouson', 'Suede Blouson', 'outerwear', '10-15', [SC, C], ['Regular', 'Slim'], ['Tobacco', 'Dark brown', 'Navy', 'Sand'], ['Valstar']),
  gt('wool-bomber', 'Wool Bomber', 'outerwear', '5-10', [C, SC], ['Regular'], ['Charcoal', 'Navy', 'Camel'], ['Private White V.C.']),
  gt('leather-biker-jacket', 'Leather Biker Jacket', 'outerwear', '10-15', [C], ['Slim', 'Regular'], ['Black', 'Dark brown'], []),
  gt('cafe-racer-jacket', 'Caf\u00e9 Racer Jacket', 'outerwear', '10-15', [C], ['Slim', 'Regular'], ['Black', 'Brown', 'Oxblood'], []),
  gt('denim-trucker', 'Denim Trucker Jacket', 'outerwear', '10-15', [C], ['Regular', 'Slim', 'Sherpa-lined'], ['Indigo', 'Washed indigo', 'Black'], ['OrSlow', 'Blackhorse Lane Ateliers', 'Full Count', 'Rogue Territory']),
  gt('suede-trucker', 'Suede Trucker Jacket', 'outerwear', '10-15', [C, SC], ['Regular'], ['Tan', 'Chocolate'], ['Valstar']),
  gt('n1-deck-jacket', 'N-1 Deck Jacket', 'outerwear', '0-5', [C, OW], ['Regular'], ['Navy', 'Khaki'], ['Buzz Rickson']),
  gt('tanker-jacket', 'Tanker Jacket', 'outerwear', '0-5', [C, OW], ['Regular'], ['Olive drab'], ['Buzz Rickson']),
  gt('m65-field-jacket', 'M-65 Field Jacket', 'outerwear', '5-10', [C, OW], ['Regular', 'Relaxed'], ['Olive drab', 'Black', 'Navy'], ['Alpha Industries']),
  gt('m43-field-jacket', 'M-43 Field Jacket', 'outerwear', '5-10', [C, OW], ['Regular', 'Relaxed'], ['Olive drab'], ['OrSlow', 'Buzz Rickson']),
  gt('m41-field-jacket', 'M-41 Field Jacket', 'outerwear', '10-15', [C, OW], ['Regular'], ['Olive drab', 'Khaki'], ['Buzz Rickson']),
  gt('battledress-blouson', 'Battledress Blouson', 'outerwear', '5-10', [C], ['Regular'], ['Olive', 'Navy', 'Brown herringbone'], []),
  gt('safari-jacket', 'Safari Jacket', 'outerwear', '20-25', [C, SC], ['Regular'], ['Sand', 'Olive', 'Stone'], []),
  gt('sahariana', 'Sahariana', 'outerwear', '25-30', [SC, C], ['Regular'], ['Sand', 'Cream', 'Tobacco'], ['Boglioli']),
  gt('cpo-jacket', 'CPO Shirt Jacket', 'outerwear', '5-10', [C, OW], ['Regular', 'Relaxed'], ['Navy wool', 'Charcoal', 'Plaid'], ['Buzz Rickson', 'Universal Works']),
  gt('overshirt', 'Overshirt', 'outerwear', '10-15', [C, SC], ['Regular', 'Relaxed'], ['Olive', 'Navy', 'Ecru', 'Check'], ['Universal Works', "Drake's", 'Finisterre']),
  gt('wool-shirt-jacket', 'Wool Shirt Jacket', 'outerwear', '5-10', [C, OW], ['Regular', 'Relaxed'], ['Buffalo check', 'Grey melton', 'Forest'], ['Filson', 'Universal Works']),
  gt('chore-coat', 'Chore Coat', 'outerwear', '10-15', [C, OW], ['Regular', 'Relaxed'], ['French blue', 'Navy', 'Ecru', 'Duck brown'], ['Le Laboureur', 'Vetra', 'Universal Works', 'Stan Ray']),
  gt('donkey-jacket', 'Donkey Jacket', 'outerwear', '0-5', [C, OW], ['Regular'], ['Black', 'Navy'], []),
  gt('boilersuit', 'Boilersuit', 'outerwear', '10-15', [OW, C], ['Regular', 'Relaxed'], ['Ecru', 'Navy', 'Olive'], ['Stan Ray', 'Universal Works']),
  gt('shop-coat', 'Shop Coat', 'outerwear', '10-15', [OW, C], ['Regular', 'Long'], ['French blue', 'Ecru', 'Navy'], ['Vetra', 'Universal Works']),
  gt('varsity-jacket', 'Varsity Jacket', 'outerwear', '5-10', [C], ['Regular'], ['Navy-cream', 'Black-white', 'Green-cream'], []),
  gt('coach-jacket', 'Coach Jacket', 'outerwear', '10-15', [C], ['Regular', 'Relaxed'], ['Black', 'Navy', 'Olive'], ['Stan Ray']),
  gt('souvenir-jacket', 'Souvenir Jacket', 'outerwear', '10-15', [C], ['Regular'], ['Black-gold', 'Navy embroidered'], ['Buzz Rickson']),
  gt('track-jacket', 'Track Jacket', 'outerwear', '15-20', [C], ['Regular', 'Slim'], ['Navy', 'Black', 'Bottle green'], ['Fred Perry']),
  gt('windbreaker', 'Windbreaker', 'outerwear', '15-20', [C], ['Regular', 'Relaxed'], ['Navy', 'Stone', 'Red'], []),
  gt('anorak', 'Anorak', 'outerwear', '10-15', [C, OW], ['Regular', 'Relaxed'], ['Navy', 'Orange', 'Stone'], ['Finisterre', 'L.L.Bean']),
  gt('fisherman-smock', 'Fisherman Smock', 'outerwear', '10-15', [C, OW], ['Relaxed'], ['Navy', 'Ochre', 'Ecru'], ['Finisterre']),
  gt('cagoule', 'Cagoule', 'outerwear', '10-15', [C, OW], ['Regular', 'Packable'], ['Navy', 'Red', 'Forest'], []),
  gt('mountain-parka', 'Mountain Parka', 'outerwear', '5-10', [C, OW], ['Regular', 'Relaxed'], ['Navy-tan 60/40', 'Olive', 'Rust'], ['L.L.Bean', 'Finisterre']),
  gt('shell-jacket', 'Technical Shell Jacket', 'outerwear', '10-15', [C, OW], ['Regular'], ['Black', 'Navy', 'Stone'], ['Finisterre']),
  gt('sailing-jacket', 'Sailing Jacket', 'outerwear', '10-15', [C, OW], ['Regular'], ['Navy', 'Yellow', 'Red'], ['Finisterre']),
  gt('fleece-jacket', 'Fleece Jacket', 'outerwear', '5-10', [C, OW], ['Regular', 'Relaxed'], ['Oat', 'Navy', 'Forest'], ['Finisterre', 'L.L.Bean']),
  gt('fleece-gilet', 'Fleece Gilet', 'outerwear', '5-10', [C, OW], ['Regular'], ['Oat', 'Navy'], ['L.L.Bean']),
  gt('down-gilet', 'Down Gilet', 'outerwear', '0-5', [C], ['Regular', 'Slim'], ['Navy', 'Black', 'Olive'], ['Uniqlo']),
  gt('quilted-gilet', 'Quilted Gilet', 'outerwear', '5-10', [C, SC, OW], ['Regular'], ['Olive', 'Navy'], ['Barbour']),
  gt('quilted-jacket', 'Quilted Jacket', 'outerwear', '5-10', [C, SC, OW], ['Regular', 'Slim'], ['Olive', 'Navy', 'Black'], ['Barbour']),
  gt('liner-jacket', 'Liner Jacket', 'outerwear', '5-10', [C], ['Regular'], ['Olive', 'Ecru'], ['Alpha Industries', 'OrSlow']),
  gt('waxed-field-jacket', 'Waxed Field Jacket', 'outerwear', '5-10', [C, OW], ['Regular', 'Relaxed'], ['Olive', 'Navy', 'Rustic brown'], ['Barbour', 'Private White V.C.']),
  gt('waxed-motorcycle-jacket', 'Waxed Motorcycle Jacket', 'outerwear', '5-10', [C, OW], ['Regular', 'Slim'], ['Black', 'Olive'], ['Barbour', 'Private White V.C.']),
  gt('norfolk-jacket', 'Norfolk Jacket', 'outerwear', '5-10', [SC, OW], ['Regular'], ['Tweed green', 'Brown herringbone'], ['Cordings']),
  gt('barn-coat', 'Barn Coat', 'outerwear', '5-10', [C, OW], ['Regular', 'Relaxed'], ['Tan duck', 'Navy', 'Forest'], ['L.L.Bean', 'Filson']),
  gt('mackinaw-cruiser', 'Mackinaw Cruiser', 'outerwear', '0-5', [C, OW], ['Regular'], ['Buffalo check', 'Forest green', 'Charcoal'], ['Filson']),
  gt('shearling-ranch-jacket', 'Shearling Ranch Jacket', 'outerwear', 'below-0', [C], ['Regular'], ['Tan', 'Dark brown'], []),
  gt('boiled-wool-jacket', 'Boiled Wool Jacket', 'outerwear', '0-5', [C, SC], ['Regular'], ['Charcoal', 'Loden green', 'Navy'], []),

  // ─── OUTERWEAR · rain & coats ───
  gt('mac-raincoat', 'Mac Raincoat', 'outerwear', '10-15', [SC, B, F], ['Regular', 'Long'], ['Stone', 'Navy', 'Black'], ['Mackintosh', 'Grenfell', 'Private White V.C.']),
  gt('trench-coat', 'Trench Coat', 'outerwear', '10-15', [SC, B], ['Regular', 'Long', 'Double-breasted'], ['Khaki', 'Stone', 'Navy'], ['Grenfell', 'Private White V.C.']),
  gt('rubberised-raincoat', 'Rubberised Raincoat', 'outerwear', '10-15', [C, SC], ['Regular', 'Long'], ['Black', 'Navy', 'Yellow'], ['Stutterheim']),
  gt('balmacaan', 'Balmacaan Coat', 'outerwear', '5-10', [SC, B], ['Relaxed', 'Long'], ['Tweed grey', 'Navy', 'Tan'], ['Mackintosh']),
  gt('raglan-overcoat', 'Raglan Overcoat', 'outerwear', '0-5', [B, F, SC], ['Relaxed', 'Long'], ['Charcoal', 'Navy', 'Herringbone'], ['Anglo-Italian']),
  gt('covert-coat', 'Covert Coat', 'outerwear', '5-10', [B, SC, F], ['Regular'], ['Fawn', 'Olive covert'], ['Cordings']),
  gt('chesterfield-coat', 'Chesterfield Coat', 'outerwear', '0-5', [F, B, BT], ['Single-breasted', 'Double-breasted'], ['Charcoal', 'Navy', 'Grey with velvet collar'], []),
  gt('wool-overcoat', 'Wool Overcoat', 'outerwear', '0-5', [B, F, SC], ['Single-breasted', 'Double-breasted', 'Long'], ['Charcoal', 'Navy', 'Camel', 'Herringbone'], ['Anglo-Italian', 'Suitsupply', 'Spier & Mackay']),
  gt('polo-coat', 'Polo Coat', 'outerwear', '0-5', [SC, B], ['Double-breasted', 'Long'], ['Camel', 'Dark camel'], ['Anglo-Italian']),
  gt('ulster-coat', 'Ulster Coat', 'outerwear', 'below-0', [SC, B], ['Double-breasted', 'Long'], ['Brown herringbone', 'Grey tweed'], []),
  gt('greatcoat', 'Greatcoat', 'outerwear', 'below-0', [SC, B], ['Double-breasted', 'Long'], ['Grey melton', 'Navy'], []),
  gt('british-warm', 'British Warm', 'outerwear', '0-5', [B, SC], ['Double-breasted'], ['Taupe melton', 'Camel'], ['Cordings']),
  gt('guards-coat', 'Guards Coat', 'outerwear', '0-5', [F, B], ['Double-breasted', 'Long'], ['Charcoal', 'Navy'], []),
  gt('paletot', 'Paletot Coat', 'outerwear', '0-5', [B, F], ['Double-breasted'], ['Navy', 'Charcoal'], []),
  gt('loden-coat', 'Loden Coat', 'outerwear', '0-5', [SC, C], ['Relaxed', 'Long'], ['Loden green', 'Charcoal'], []),
  gt('duffle-coat', 'Duffle Coat', 'outerwear', '0-5', [C, SC], ['Regular', 'Long'], ['Camel', 'Navy', 'Charcoal'], ['Gloverall']),
  gt('pea-coat', 'Pea Coat', 'outerwear', '0-5', [C, SC], ['Regular', 'Slim'], ['Navy', 'Black', 'Charcoal'], ['Gloverall', 'Buzz Rickson', 'Private White V.C.']),
  gt('bridge-coat', 'Bridge Coat', 'outerwear', '0-5', [SC, B], ['Double-breasted', 'Long'], ['Navy'], ['Gloverall']),
  gt('car-coat', 'Car Coat', 'outerwear', '5-10', [SC, B], ['Regular'], ['Navy', 'Stone', 'Charcoal'], ['Valstar', 'Private White V.C.']),
  gt('fishtail-parka', 'Fishtail Parka (M-51)', 'outerwear', '0-5', [C], ['Relaxed', 'Long'], ['Olive drab'], ['Buzz Rickson']),
  gt('snorkel-parka', 'Snorkel Parka (N-3B)', 'outerwear', 'below-0', [C], ['Regular', 'Long'], ['Sage green', 'Navy'], ['Alpha Industries']),
  gt('down-parka', 'Down Expedition Parka', 'outerwear', 'below-0', [C, OW], ['Regular', 'Long'], ['Navy', 'Black', 'Olive'], []),
  gt('puffer-jacket', 'Puffer Jacket', 'outerwear', '0-5', [C], ['Regular', 'Lightweight'], ['Navy', 'Black', 'Olive'], ['Uniqlo']),

  // ─── FORMALWEAR ───
  gt('navy-blazer', 'Navy Blazer', 'formalwear', '10-15', [SC, B], ['Single-breasted', 'Double-breasted'], ['Navy'], ['Anglo-Italian', 'Ring Jacket', 'Suitsupply', 'Spier & Mackay']),
  gt('hopsack-blazer', 'Hopsack Blazer', 'formalwear', '15-20', [SC, B], ['Single-breasted', 'Double-breasted'], ['Navy', 'Mid-blue'], ['Ring Jacket', 'Anglo-Italian']),
  gt('unstructured-blazer', 'Unstructured Blazer', 'formalwear', '15-20', [SC, B], ['Slim', 'Regular'], ['Navy', 'Stone', 'Olive', 'Grey'], ['Boglioli', 'Ring Jacket']),
  gt('teba-jacket', 'Teba Jacket', 'formalwear', '10-15', [SC, C], ['Regular'], ['Tweed brown', 'Navy', 'Green check'], []),
  gt('tweed-sport-coat', 'Tweed Sport Coat', 'formalwear', '0-5', [SC, B], ['Regular', 'Slim'], ['Brown herringbone', 'Green check', 'Grey Donegal'], ['Cordings', 'Anglo-Italian', 'Spier & Mackay']),
  gt('linen-sport-coat', 'Linen Sport Coat', 'formalwear', '25-30', [SC, B], ['Regular', 'Slim'], ['Sand', 'Navy', 'Sage'], ['Boglioli', 'Ring Jacket', 'Spier & Mackay']),
  gt('seersucker-jacket', 'Seersucker Jacket', 'formalwear', '25-30', [SC], ['Regular'], ['Blue stripe', 'Grey stripe'], ['Spier & Mackay']),
  gt('madras-jacket', 'Madras Jacket', 'formalwear', '25-30', [SC], ['Regular'], ['Multicolour check'], []),
  gt('camelhair-blazer', 'Camel Hair Blazer', 'formalwear', '0-5', [SC, B], ['Single-breasted', 'Double-breasted'], ['Camel'], ['Anglo-Italian']),
  gt('corduroy-sport-coat', 'Corduroy Sport Coat', 'formalwear', '5-10', [SC], ['Regular'], ['Tan', 'Bottle green', 'Chocolate'], ['Cordings', 'Spier & Mackay']),
  gt('worsted-suit', 'Worsted Suit', 'formalwear', '10-15', [B, F], ['Single-breasted', 'Double-breasted', 'Slim', 'Regular'], ['Navy', 'Charcoal', 'Mid-grey'], ['Suitsupply', 'Spier & Mackay', 'Anglo-Italian', 'Ring Jacket']),
  gt('pinstripe-suit', 'Pinstripe Suit', 'formalwear', '10-15', [B, F], ['Single-breasted', 'Double-breasted'], ['Navy pinstripe', 'Charcoal chalk stripe'], ['Suitsupply', 'Spier & Mackay']),
  gt('flannel-suit', 'Flannel Suit', 'formalwear', '0-5', [B, F], ['Single-breasted', 'Double-breasted'], ['Mid-grey', 'Charcoal', 'Navy'], ['Anglo-Italian', 'Spier & Mackay']),
  gt('fresco-suit', 'Fresco Suit', 'formalwear', '25-30', [B, F], ['Single-breasted'], ['Mid-grey', 'Navy'], ['Anglo-Italian', 'Ring Jacket']),
  gt('linen-suit', 'Linen Suit', 'formalwear', '25-30', [SC, B], ['Single-breasted', 'Relaxed'], ['Sand', 'Cream', 'Navy'], ['Boglioli', 'Suitsupply']),
  gt('seersucker-suit', 'Seersucker Suit', 'formalwear', '25-30', [SC, B], ['Single-breasted'], ['Blue stripe'], ['Spier & Mackay']),
  gt('cotton-suit', 'Cotton Suit', 'formalwear', '20-25', [SC, B], ['Single-breasted', 'Slim'], ['Stone', 'Olive', 'Tobacco'], ['Boglioli', 'Suitsupply']),
  gt('tweed-suit', 'Tweed Suit', 'formalwear', '0-5', [SC, B], ['Single-breasted', 'Three-piece'], ['Brown herringbone', 'Green estate tweed'], ['Cordings']),
  gt('corduroy-suit', 'Corduroy Suit', 'formalwear', '5-10', [SC], ['Single-breasted'], ['Tan', 'Bottle green', 'Brown'], ['Cordings']),
  gt('mohair-suit', 'Mohair Suit', 'formalwear', '20-25', [B, F], ['Slim', 'Single-breasted'], ['Midnight', 'Tonic grey'], []),
  gt('dinner-suit', 'Dinner Suit', 'formalwear', '10-15', [BT], ['Shawl lapel', 'Peak lapel', 'Single-breasted', 'Double-breasted'], ['Black', 'Midnight blue'], ['Suitsupply', 'Ring Jacket']),
  gt('white-dinner-jacket', 'White Dinner Jacket', 'formalwear', '25-30', [BT], ['Shawl lapel', 'Peak lapel'], ['Ivory', 'Cream'], []),
  gt('velvet-dinner-jacket', 'Velvet Dinner Jacket', 'formalwear', '5-10', [BT], ['Shawl lapel'], ['Bottle green', 'Burgundy', 'Midnight'], []),
  gt('smoking-jacket', 'Smoking Jacket', 'formalwear', '10-15', [BT], ['Shawl lapel'], ['Burgundy', 'Bottle green', 'Black'], []),
  gt('mess-jacket', 'Mess Jacket', 'formalwear', '20-25', [BT], ['Cropped'], ['White', 'Ivory'], []),
  gt('morning-coat', 'Morning Coat', 'formalwear', '10-15', [F], ['Regular'], ['Black', 'Grey'], []),
  gt('morning-trousers', 'Morning Trousers', 'formalwear', '10-15', [F], ['Regular'], ['Cashmere stripe grey'], []),
  gt('evening-tailcoat', 'Evening Tailcoat', 'formalwear', '10-15', [BT], ['Regular'], ['Black'], []),
  gt('evening-trousers', 'Evening Trousers', 'formalwear', '10-15', [BT], ['Regular', 'High-rise'], ['Black with braid', 'Midnight with braid'], []),
  gt('evening-waistcoat', 'Evening Waistcoat', 'formalwear', '10-15', [BT], ['Low-cut'], ['White marcella', 'Black'], []),
  gt('odd-waistcoat', 'Odd Waistcoat', 'formalwear', '10-15', [SC, B, F], ['Regular'], ['Fawn', 'Tattersall', 'Moleskin brown'], ['Cordings']),
  gt('stroller-jacket', 'Stroller (Black Lounge) Jacket', 'formalwear', '10-15', [F], ['Regular'], ['Black', 'Charcoal'], []),
  gt('boating-blazer', 'Boating Blazer', 'formalwear', '20-25', [SC], ['Regular'], ['Club stripe', 'Cream with piping'], []),
  gt('nehru-jacket', 'Nehru Jacket', 'formalwear', '20-25', [SC], ['Slim', 'Regular'], ['Ivory', 'Navy', 'Black'], []),
];
