/**
 * GARMENT TYPE ENTRIES 3 of 4 — BOTTOMS · SHOES.
 * One `gt(id, name, category, band, reach, cuts, colours, makers)` per line.
 * Assembled and indexed by garment-types.ts — import from THERE, not here.
 */
import { gt, C, SC, B, F, BT, OW, type GarmentType } from './garment-type-model';

export const GARMENT_TYPE_ENTRIES_3: GarmentType[] = [
  // ─── BOTTOMS ───
  gt('chinos', 'Chinos', 'bottoms', '15-20', [C, SC, B], ['Flat-front', 'Single-pleat', 'Slim', 'Straight'], ['Khaki', 'Stone', 'Navy', 'Olive'], ['Uniqlo', 'Casatlantic', 'Stan Ray', 'Berg & Berg']),
  gt('flannel-trousers', 'Flannel Trousers', 'bottoms', '0-5', [B, F, SC], ['High-rise', 'Single-pleat', 'Double-pleat', 'Flat-front'], ['Mid-grey', 'Charcoal', 'Navy'], ['Rota', 'Anglo-Italian', 'Berg & Berg']),
  gt('worsted-trousers', 'Worsted Trousers', 'bottoms', '10-15', [B, F], ['Flat-front', 'Single-pleat', 'High-rise'], ['Navy', 'Charcoal', 'Mid-grey'], ['Rota', 'Berg & Berg', 'Suitsupply']),
  gt('fresco-trousers', 'Fresco Trousers', 'bottoms', '25-30', [B, F], ['Flat-front', 'Single-pleat'], ['Mid-grey', 'Navy'], ['Anglo-Italian', 'Rota']),
  gt('corduroy-trousers', 'Corduroy Trousers', 'bottoms', '5-10', [C, SC], ['Regular', 'High-rise', 'Slim'], ['Tan', 'Bottle green', 'Brown', 'Navy'], ['Bhode', 'Cordings', "Drake's"]),
  gt('moleskin-trousers', 'Moleskin Trousers', 'bottoms', '0-5', [C, SC, OW], ['Regular', 'High-rise'], ['Fawn', 'Olive', 'Brown'], ['Bhode', 'Cordings']),
  gt('linen-trousers', 'Linen Trousers', 'bottoms', '25-30', [C, SC], ['Relaxed', 'Flat-front', 'Drawstring'], ['Sand', 'Cream', 'Navy'], ['Berg & Berg', 'Anglo-Italian']),
  gt('seersucker-trousers', 'Seersucker Trousers', 'bottoms', '25-30', [SC], ['Flat-front'], ['Blue stripe', 'Grey stripe'], []),
  gt('cavalry-twill-trousers', 'Cavalry Twill Trousers', 'bottoms', '5-10', [SC, B], ['Regular', 'High-rise'], ['Fawn', 'Taupe'], ['Cordings']),
  gt('tweed-trousers', 'Tweed Trousers', 'bottoms', '0-5', [SC], ['Regular'], ['Grey herringbone', 'Brown Donegal'], ['Cordings']),
  gt('gurkha-trousers', 'Gurkha Trousers', 'bottoms', '20-25', [SC], ['High-rise', 'Double-pleat'], ['Stone', 'Olive', 'Navy'], ['Casatlantic', 'Rota']),
  gt('selvedge-jeans', 'Selvedge Jeans', 'bottoms', '10-15', [C], ['Straight', 'Slim', 'Tapered', 'Loose'], ['Raw indigo', 'Washed indigo', 'Black'], ['Full Count', 'Rogue Territory', 'Blackhorse Lane Ateliers', 'OrSlow']),
  gt('classic-jeans', 'Classic Five-Pocket Jeans', 'bottoms', '10-15', [C], ['Straight', 'Slim', 'Relaxed'], ['Indigo', 'Washed blue', 'Black', 'Ecru'], ['Uniqlo', 'Blackhorse Lane Ateliers']),
  gt('fatigue-pants', 'Fatigue Pants (OG-107)', 'bottoms', '15-20', [C, OW], ['Regular', 'Relaxed', 'Tapered'], ['Olive drab', 'Navy', 'Stone'], ['OrSlow', 'Stan Ray']),
  gt('cargo-trousers', 'Cargo Trousers', 'bottoms', '15-20', [C, OW], ['Regular', 'Relaxed'], ['Olive', 'Khaki', 'Black'], ['Stan Ray']),
  gt('carpenter-pants', 'Carpenter Pants', 'bottoms', '10-15', [C, OW], ['Straight', 'Relaxed'], ['Duck brown', 'Ecru', 'Indigo'], ['Stan Ray']),
  gt('work-trousers', 'Duck Canvas Work Trousers', 'bottoms', '10-15', [OW, C], ['Regular', 'Double-knee'], ['Duck brown', 'Black', 'Moss'], ['Stan Ray', 'Filson']),
  gt('bib-overalls', 'Bib Overalls', 'bottoms', '10-15', [OW, C], ['Regular', 'Relaxed'], ['Indigo', 'Duck brown', 'Hickory stripe'], ['Stan Ray']),
  gt('drawstring-trousers', 'Drawstring Trousers', 'bottoms', '20-25', [C], ['Relaxed'], ['Navy', 'Olive', 'Sand'], ['Universal Works']),
  gt('track-pants', 'Track Pants', 'bottoms', '10-15', [C], ['Regular', 'Tapered'], ['Navy', 'Black'], ['Fred Perry']),
  gt('sweatpants', 'Loopback Sweatpants', 'bottoms', '10-15', [C], ['Regular', 'Tapered'], ['Grey melange', 'Navy', 'Black'], ['Lady White Co.', 'Merz b. Schwanen', 'Sunspel']),
  gt('deck-trousers', 'Naval Deck Trousers', 'bottoms', '5-10', [C, OW], ['Relaxed', 'High-rise'], ['Navy', 'Ecru'], ['Buzz Rickson']),
  gt('brace-top-trousers', 'Brace-Top Trousers', 'bottoms', '10-15', [SC, B], ['High-rise', 'Fishtail-back'], ['Grey flannel', 'Fawn', 'Navy'], []),
  gt('oxford-bags', 'Oxford Bags', 'bottoms', '10-15', [SC], ['Wide', 'High-rise'], ['Grey flannel', 'Cream'], []),
  gt('cricket-flannels', 'Cricket Flannels', 'bottoms', '20-25', [SC], ['Regular'], ['Cream', 'Ivory'], []),
  gt('breeks', 'Breeks', 'bottoms', '5-10', [OW, SC], ['Regular'], ['Estate tweed', 'Olive'], ['Cordings']),
  gt('plus-fours', 'Plus Fours', 'bottoms', '5-10', [SC, OW], ['Regular'], ['Tweed check', 'Fawn'], ['Cordings']),
  gt('chino-shorts', 'Chino Shorts', 'bottoms', '25-30', [C, SC], ['Regular', 'Slim', '7-inch'], ['Stone', 'Navy', 'Olive'], ['Uniqlo', 'Universal Works']),
  gt('linen-shorts', 'Linen Shorts', 'bottoms', 'above-30', [C], ['Relaxed', 'Drawstring'], ['Sand', 'White', 'Navy'], ['Luca Faloni']),
  gt('tailored-shorts', 'Tailored Shorts', 'bottoms', '25-30', [SC], ['Flat-front', 'Single-pleat'], ['Stone', 'Navy', 'Cream'], ['Berg & Berg']),
  gt('corduroy-shorts', 'Corduroy Shorts', 'bottoms', '20-25', [C], ['Regular'], ['Tan', 'Moss', 'Navy'], ['Bhode']),
  gt('gurkha-shorts', 'Gurkha Shorts', 'bottoms', '25-30', [SC, C], ['High-rise', 'Double-pleat'], ['Stone', 'Olive'], ['Casatlantic']),
  gt('swim-shorts', 'Swim Shorts', 'bottoms', 'above-30', [C], ['Mid-length', 'Short', 'Long'], ['Navy', 'Coral', 'Sky', 'Print'], ['Orlebar Brown']),

  // ─── SHOES · oxfords, derbies & dress ───
  gt('cap-toe-oxford', 'Cap-Toe Oxford', 'shoes', '10-15', [F, B], ['Round last', 'Sleek last'], ['Black', 'Dark oak', 'Burgundy'], ['Crockett & Jones', 'Loake 1880', 'Carmina', 'Meermin', 'Morjas']),
  gt('wholecut-oxford', 'Wholecut Oxford', 'shoes', '10-15', [F, B], ['Sleek last'], ['Black', 'Dark brown'], ['Carmina', 'Crockett & Jones']),
  gt('adelaide-oxford', 'Adelaide Oxford', 'shoes', '10-15', [F, B], ['Sleek last'], ['Dark oak', 'Black'], ['Carmina']),
  gt('full-brogue-oxford', 'Full Brogue (Wingtip)', 'shoes', '10-15', [B, SC], ['Round last', 'Country sole'], ['Tan', 'Dark brown', 'Black'], ['Loake 1880', 'Crockett & Jones', 'Berwick']),
  gt('semi-brogue', 'Semi-Brogue Oxford', 'shoes', '10-15', [B, F], ['Round last'], ['Black', 'Dark brown'], ['Crockett & Jones', 'Loake 1880']),
  gt('austerity-brogue', 'Austerity Brogue', 'shoes', '10-15', [SC, B], ['Round last'], ['Black', 'Brown'], ['Crockett & Jones']),
  gt('spectator-shoe', 'Spectator Shoe', 'shoes', '20-25', [SC], ['Classic last'], ['Brown-white', 'Black-white'], []),
  gt('saddle-shoe', 'Saddle Shoe', 'shoes', '15-20', [C, SC], ['Classic last'], ['White-navy', 'Ecru-brown'], ['G.H. Bass']),
  gt('white-buck', 'White Buck', 'shoes', '20-25', [SC], ['Classic last'], ['White nubuck', 'Dirty buck'], ['G.H. Bass']),
  gt('plain-derby', 'Plain-Toe Derby', 'shoes', '10-15', [SC, B], ['Round last', 'Dainite sole'], ['Black', 'Dark brown', 'Suede snuff'], ['Berwick', 'Loake 1880', 'Paraboot']),
  gt('split-toe-derby', 'Split-Toe Derby', 'shoes', '10-15', [SC, B], ['Norwegian welt'], ['Dark brown', 'Black'], ['Paraboot', 'Carmina']),
  gt('longwing-derby', 'Longwing Derby', 'shoes', '10-15', [SC, C], ['Country sole'], ['Burgundy', 'Tan', 'Black'], ['Loake 1880']),
  gt('postman-shoe', 'Postman Shoe', 'shoes', '10-15', [C, OW], ['Cushion sole'], ['Black', 'Dark brown'], ['Solovair', 'Sanders']),
  gt('tyrolean-shoe', 'Tyrolean Shoe', 'shoes', '5-10', [C, SC], ['Norwegian welt'], ['Dark brown', 'Black grain'], ['Paraboot']),

  // ─── SHOES · loafers & mocs ───
  gt('penny-loafer', 'Penny Loafer', 'shoes', '15-20', [SC, C, B], ['Beefroll', 'Sleek last', 'Unlined'], ['Burgundy', 'Dark brown', 'Black', 'Snuff suede'], ['G.H. Bass', 'Carmina', 'Crockett & Jones', 'Rancourt & Co.', 'Morjas']),
  gt('tassel-loafer', 'Tassel Loafer', 'shoes', '15-20', [SC, B], ['Sleek last'], ['Black', 'Burgundy', 'Snuff suede'], ['Crockett & Jones', 'Carmina']),
  gt('horsebit-loafer', 'Horsebit Loafer', 'shoes', '15-20', [SC, B], ['Sleek last'], ['Black', 'Dark brown'], ['Morjas']),
  gt('kiltie-loafer', 'Kiltie Loafer', 'shoes', '15-20', [SC], ['Classic last'], ['Burgundy', 'Brown'], []),
  gt('belgian-loafer', 'Belgian Loafer', 'shoes', '20-25', [SC], ['Soft unlined'], ['Velvet navy', 'Suede tan', 'Black'], []),
  gt('venetian-loafer', 'Venetian Loafer', 'shoes', '20-25', [SC], ['Soft unlined'], ['Suede sand', 'Dark brown'], ['Rancourt & Co.']),
  gt('driving-moc', 'Driving Moccasin', 'shoes', '20-25', [C, SC], ['Rubber-pebble sole'], ['Navy suede', 'Tan', 'Chocolate'], []),
  gt('boat-shoe', 'Boat Shoe', 'shoes', '20-25', [C], ['Classic'], ['Brown', 'Navy', 'Tan'], ['Rancourt & Co.', 'G.H. Bass']),
  gt('camp-moc', 'Camp Moccasin', 'shoes', '15-20', [C], ['Classic'], ['Brown', 'Navy', 'Tan'], ['Rancourt & Co.', 'L.L.Bean']),
  gt('blucher-moc', 'Blucher Moccasin', 'shoes', '15-20', [C], ['Classic'], ['Brown', 'Whiskey'], ['Rancourt & Co.']),
  gt('wallabee', 'Wallabee', 'shoes', '10-15', [C], ['Crepe sole'], ['Sand suede', 'Maple', 'Black'], ['Clarks Originals']),
  gt('espadrille', 'Espadrille', 'shoes', 'above-30', [C], ['Flat', 'Slip-on'], ['Natural', 'Navy', 'Black'], []),

  // ─── SHOES · monks & boots ───
  gt('single-monk', 'Single Monk Strap', 'shoes', '10-15', [B, F], ['Sleek last'], ['Black', 'Dark brown'], ['Carmina', 'Berwick']),
  gt('double-monk', 'Double Monk Strap', 'shoes', '10-15', [B, SC], ['Sleek last'], ['Dark oak', 'Black'], ['Carmina', 'Crockett & Jones']),
  gt('chukka-boot', 'Chukka Boot', 'shoes', '5-10', [C, SC], ['Dainite sole', 'Suede', 'Calf'], ['Snuff suede', 'Dark brown', 'Sand'], ['Sanders', 'Loake 1880', 'Astorflex', 'Crockett & Jones']),
  gt('desert-boot', 'Desert Boot', 'shoes', '10-15', [C], ['Crepe sole'], ['Sand suede', 'Beeswax', 'Brown'], ['Clarks Originals', 'Astorflex']),
  gt('chelsea-boot', 'Chelsea Boot', 'shoes', '5-10', [SC, B, C], ['Sleek last', 'Round last'], ['Black', 'Dark brown', 'Suede snuff'], ['R.M. Williams', 'Crockett & Jones', 'Loake 1880', 'Morjas']),
  gt('jodhpur-boot', 'Jodhpur Boot', 'shoes', '5-10', [SC, B], ['Sleek last'], ['Dark brown', 'Black'], ['Carmina']),
  gt('balmoral-boot', 'Balmoral Boot', 'shoes', '0-5', [F, B], ['Sleek last'], ['Black', 'Two-tone'], ['Crockett & Jones']),
  gt('george-boot', 'George Boot', 'shoes', '5-10', [F, B], ['Round last'], ['Black', 'Dark brown'], ['Sanders']),
  gt('country-brogue-boot', 'Country Brogue Boot', 'shoes', '0-5', [SC, OW], ['Country sole', 'Commando sole'], ['Tan grain', 'Dark brown'], ['Crockett & Jones', 'Loake 1880']),
  gt('service-boot', 'Service Boot', 'shoes', '0-5', [C, OW], ['Round last', 'Commando sole'], ['Black', 'Brown', 'Oxblood'], ['Solovair', 'Sanders']),
  gt('moc-toe-boot', 'Moc-Toe Work Boot', 'shoes', '0-5', [C, OW], ['Wedge sole'], ['Whiskey', 'Brown'], []),
  gt('engineer-boot', 'Engineer Boot', 'shoes', '0-5', [C, OW], ['Regular'], ['Black', 'Brown'], []),
  gt('logger-boot', 'Logger Boot', 'shoes', 'below-0', [OW], ['Lug sole'], ['Brown', 'Black'], []),
  gt('lace-to-toe-boot', 'Lace-to-Toe Boot', 'shoes', '0-5', [OW, C], ['Regular'], ['Brown', 'Tan'], []),
  gt('monkey-boot', 'Monkey Boot', 'shoes', '5-10', [C], ['Regular'], ['Black', 'Oxblood'], ['Solovair']),
  gt('hiking-boot', 'Leather Hiking Boot', 'shoes', '0-5', [C, OW], ['Norwegian welt', 'Lug sole'], ['Brown', 'Tan'], ['Paraboot']),
  gt('wellington-boot', 'Wellington Boot', 'shoes', '5-10', [OW, C], ['Regular'], ['Green', 'Black'], ['Barbour']),
  gt('duck-boot', 'Duck Boot', 'shoes', '0-5', [C, OW], ['Regular'], ['Tan-brown', 'Navy'], ['L.L.Bean']),
  gt('deck-boot', 'Rubber Deck Boot', 'shoes', '5-10', [C, OW], ['Regular'], ['Navy', 'Olive'], []),
  gt('veldskoen', 'Veldskoen', 'shoes', '20-25', [C], ['Regular'], ['Sand suede', 'Brown'], []),

  // ─── SHOES · evening, house & sneakers ───
  gt('opera-pump', 'Opera Pump', 'shoes', '10-15', [BT], ['Classic'], ['Black patent'], []),
  gt('patent-oxford', 'Patent Oxford', 'shoes', '10-15', [BT, F], ['Sleek last'], ['Black patent'], ['Loake 1880']),
  gt('albert-slipper', 'Albert Slipper', 'shoes', '10-15', [BT, SC], ['Classic'], ['Velvet black', 'Velvet burgundy', 'Embroidered'], []),
  gt('sheepskin-slipper', 'Sheepskin Slipper', 'shoes', '0-5', [C], ['Classic'], ['Chestnut', 'Grey'], []),
  gt('minimal-leather-sneaker', 'Minimal Leather Sneaker', 'shoes', '15-20', [C, SC], ['Low-top'], ['White', 'Off-white', 'Black'], ['Common Projects', 'CQP', 'Veja']),
  gt('leather-tennis-sneaker', 'Leather Tennis Sneaker', 'shoes', '15-20', [C, SC], ['Low-top'], ['White-green', 'White-navy'], ['CQP']),
  gt('gat-trainer', 'German Army Trainer', 'shoes', '15-20', [C], ['Low-top'], ['White-gum', 'Off-white'], []),
  gt('canvas-low-top', 'Canvas Low-Top', 'shoes', '20-25', [C], ['Low-top'], ['Ecru', 'Navy', 'Black'], ['Novesta']),
  gt('canvas-high-top', 'Canvas High-Top', 'shoes', '15-20', [C], ['High-top'], ['Ecru', 'Black'], ['Novesta']),
  gt('retro-runner', 'Retro Runner', 'shoes', '15-20', [C], ['Low-profile'], ['Grey-navy', 'Silver', 'Forest'], ['Novesta']),
  gt('leather-sandal', 'Leather Sandal', 'shoes', 'above-30', [C], ['Two-strap', 'Slide'], ['Tan', 'Dark brown', 'Black'], []),
  gt('fisherman-sandal', 'Fisherman Sandal', 'shoes', 'above-30', [C], ['Closed-toe'], ['Tan', 'Black'], ['Paraboot']),
  gt('gurkha-sandal', 'Gurkha Sandal', 'shoes', 'above-30', [C, SC], ['Woven'], ['Tan', 'Dark brown'], []),
  gt('cork-footbed-sandal', 'Cork-Footbed Sandal', 'shoes', '25-30', [C], ['Two-strap'], ['Taupe suede', 'Black'], []),
];
