/**
 * GARMENT TYPE ENTRIES 1 of 4 — TOPS · KNITWEAR · SWEATSHIRTS · BASE LAYERS.
 * One `gt(id, name, category, band, reach, cuts, colours, makers)` per line.
 * Assembled and indexed by garment-types.ts — import from THERE, not here.
 */
import { gt, C, SC, B, F, BT, OW, type GarmentType } from './garment-type-model';

export const GARMENT_TYPE_ENTRIES_1: GarmentType[] = [
  // ─── TOPS ───
  gt('oxford-button-down-shirt', 'Oxford Button-Down Shirt', 'tops', '10-15', [C, SC, B], ['Regular', 'Slim', 'Relaxed'], ['White', 'Blue', 'Ecru', 'Pink', 'University stripe'], ['Kamakura Shirts', 'Gitman Vermont', "Drake's", 'Spier & Mackay']),
  gt('poplin-dress-shirt', 'Poplin Dress Shirt', 'tops', '10-15', [B, F, SC], ['Regular', 'Slim'], ['White', 'Light blue', 'Pale pink'], ['100Hands', 'Kamakura Shirts']),
  gt('twill-dress-shirt', 'Twill Dress Shirt', 'tops', '5-10', [B, F], ['Regular', 'Slim'], ['White', 'Blue', 'Cream'], ['100Hands', 'Kamakura Shirts']),
  gt('end-on-end-shirt', 'End-on-End Shirt', 'tops', '15-20', [SC, B], ['Regular', 'Slim'], ['Blue', 'Lilac', 'Grey'], ['100Hands', "Drake's"]),
  gt('chambray-shirt', 'Chambray Shirt', 'tops', '15-20', [C, SC, OW], ['Regular', 'Relaxed'], ['Indigo', 'Washed blue', 'Ecru'], ['Gitman Vermont', "Drake's", 'OrSlow']),
  gt('denim-shirt', 'Denim Shirt', 'tops', '10-15', [C, OW], ['Regular', 'Slim'], ['Indigo', 'Washed indigo', 'Black'], ['OrSlow', 'Blackhorse Lane Ateliers', 'Rogue Territory']),
  gt('western-shirt', 'Western Shirt', 'tops', '10-15', [C], ['Regular', 'Slim'], ['Indigo', 'Black', 'Sand'], ['OrSlow', 'Rogue Territory']),
  gt('flannel-shirt', 'Flannel Shirt', 'tops', '5-10', [C, OW], ['Regular', 'Relaxed'], ['Buffalo check', 'Grey', 'Green tartan', 'Rust'], ['Gitman Vermont', 'Filson', 'Universal Works']),
  gt('chamois-shirt', 'Chamois Cloth Shirt', 'tops', '0-5', [C, OW], ['Regular', 'Relaxed'], ['Tan', 'Forest green', 'Burgundy'], ['Filson', 'L.L.Bean']),
  gt('linen-shirt', 'Linen Shirt', 'tops', '25-30', [C, SC], ['Regular', 'Relaxed'], ['White', 'Sky blue', 'Sand', 'Olive'], ['Luca Faloni', "Drake's", 'Anglo-Italian']),
  gt('camp-collar-shirt', 'Camp-Collar Shirt', 'tops', '25-30', [C], ['Regular', 'Boxy'], ['Cream', 'Navy', 'Sage', 'Print'], ["Drake's", 'Universal Works', 'Corridor NYC']),
  gt('grandad-collar-shirt', 'Grandad-Collar Shirt', 'tops', '20-25', [C, SC], ['Regular', 'Relaxed'], ['White', 'Stripe', 'Chambray blue'], ['Universal Works', 'Vetra']),
  gt('popover-shirt', 'Popover Shirt', 'tops', '15-20', [C, SC], ['Regular', 'Relaxed'], ['White', 'Blue', 'Stripe'], ["Drake's", 'Kamakura Shirts']),
  gt('safari-shirt', 'Safari Shirt', 'tops', '25-30', [C, OW], ['Regular'], ['Sand', 'Olive', 'Stone'], []),
  gt('corduroy-shirt', 'Corduroy Shirt', 'tops', '5-10', [C, SC], ['Regular', 'Relaxed'], ['Tan', 'Bottle green', 'Navy', 'Rust'], ["Drake's", 'Universal Works', 'Bhode']),
  gt('madras-shirt', 'Madras Shirt', 'tops', '25-30', [C, SC], ['Regular'], ['Multicolour check'], ['Gitman Vermont', 'Kamakura Shirts']),
  gt('seersucker-shirt', 'Seersucker Shirt', 'tops', '25-30', [C, SC], ['Regular'], ['Blue stripe', 'White', 'Grey stripe'], ['Gitman Vermont']),
  gt('work-shirt', 'Twill Work Shirt', 'tops', '10-15', [C, OW], ['Regular', 'Relaxed'], ['Duck brown', 'Navy', 'Hickory stripe'], ['Stan Ray', 'Vetra', 'Le Laboureur']),
  gt('fatigue-shirt', 'Fatigue Shirt', 'tops', '15-20', [C, OW], ['Regular', 'Relaxed'], ['Olive drab', 'Navy', 'Stone'], ['OrSlow', 'Stan Ray', 'Universal Works']),
  gt('winchester-shirt', 'Winchester Shirt', 'tops', '10-15', [B, F], ['Regular', 'Slim'], ['Blue with white collar', 'Stripe with white collar'], ['100Hands']),
  gt('tattersall-shirt', 'Tattersall Shirt', 'tops', '5-10', [SC, OW], ['Regular'], ['Cream check', 'Red-green check'], ['Cordings']),
  gt('gingham-shirt', 'Gingham Shirt', 'tops', '15-20', [C, SC], ['Regular', 'Slim'], ['Navy check', 'Red check', 'Green check'], ['Kamakura Shirts', 'Gitman Vermont']),
  gt('club-collar-shirt', 'Club-Collar Shirt', 'tops', '10-15', [SC, B], ['Regular', 'Slim'], ['White', 'Stripe', 'Blue'], ["Drake's", 'Kamakura Shirts']),
  gt('pin-collar-shirt', 'Pin-Collar Shirt', 'tops', '10-15', [B, F], ['Regular', 'Slim'], ['White', 'Light blue'], ['100Hands']),
  gt('marcella-dress-shirt', 'Marcella Evening Shirt', 'tops', '10-15', [BT, F], ['Regular'], ['White'], ['100Hands']),
  gt('guayabera', 'Guayabera', 'tops', 'above-30', [C, SC], ['Regular', 'Relaxed'], ['White', 'Cream', 'Sky blue'], []),
  gt('bowling-shirt', 'Bowling Shirt', 'tops', '25-30', [C], ['Boxy'], ['Two-tone', 'Cream', 'Black'], []),
  gt('aloha-shirt', 'Aloha Shirt', 'tops', 'above-30', [C], ['Regular', 'Boxy'], ['Print', 'Navy print', 'Cream print'], []),
  gt('pique-polo', 'Piqu\u00e9 Polo Shirt', 'tops', '20-25', [C, SC], ['Regular', 'Slim'], ['Navy', 'White', 'Bottle green', 'Burgundy'], ['Fred Perry', 'Sunspel', 'Luca Faloni']),
  gt('jersey-polo', 'Jersey Polo Shirt', 'tops', '20-25', [C], ['Regular'], ['Navy', 'Grey melange', 'Olive'], ['Sunspel', 'Merz b. Schwanen']),
  gt('terry-polo', 'Terry-Towelling Polo', 'tops', '25-30', [C], ['Regular'], ['Cream', 'Navy', 'Coral'], ['Orlebar Brown', 'Sunspel']),
  gt('long-sleeve-polo', 'Long-Sleeve Polo', 'tops', '15-20', [C, SC], ['Regular', 'Slim'], ['Navy', 'Charcoal', 'Cream'], ['Sunspel', 'John Smedley']),
  gt('zip-polo', 'Zip-Neck Polo', 'tops', '15-20', [C, SC], ['Regular'], ['Navy', 'Grey', 'Black'], ['John Smedley']),
  gt('rugby-shirt', 'Rugby Shirt', 'tops', '5-10', [C], ['Regular', 'Relaxed'], ['Hooped stripe', 'Navy', 'Bottle green'], ["Drake's"]),
  gt('breton-shirt', 'Breton Stripe Shirt', 'tops', '15-20', [C], ['Regular'], ['Navy-ecru stripe', 'Ecru-navy stripe', 'Red-ecru stripe'], ['Saint James', 'Merz b. Schwanen']),
  gt('classic-tee', 'Classic T-Shirt', 'tops', '20-25', [C], ['Regular', 'Slim', 'Relaxed'], ['White', 'Navy', 'Grey melange', 'Black'], ['Sunspel', 'Lady White Co.', 'Merz b. Schwanen']),
  gt('loopwheel-tee', 'Heavyweight Loopwheel T-Shirt', 'tops', '20-25', [C], ['Regular', 'Boxy'], ['White', 'Ecru', 'Faded black'], ['Merz b. Schwanen', 'Lady White Co.', 'Buzz Rickson']),
  gt('pocket-tee', 'Pocket T-Shirt', 'tops', '20-25', [C], ['Regular', 'Relaxed'], ['White', 'Olive', 'Navy'], ['Lady White Co.', 'Sunspel']),
  gt('v-neck-tee', 'V-Neck T-Shirt', 'tops', '20-25', [C], ['Regular', 'Slim'], ['White', 'Grey', 'Navy'], ['Sunspel', 'Hanro']),
  gt('long-sleeve-tee', 'Long-Sleeve T-Shirt', 'tops', '15-20', [C], ['Regular', 'Relaxed'], ['White', 'Navy', 'Grey melange'], ['Sunspel', 'Lady White Co.']),
  gt('mock-neck-tee', 'Mock-Neck T-Shirt', 'tops', '10-15', [C, SC], ['Regular', 'Slim'], ['Cream', 'Black', 'Navy'], ['Lady White Co.']),
  gt('baseball-tee', 'Raglan Baseball T-Shirt', 'tops', '15-20', [C], ['Regular'], ['White-navy', 'Grey-black'], ['Merz b. Schwanen']),
  gt('ringer-tee', 'Ringer T-Shirt', 'tops', '20-25', [C], ['Regular'], ['White-navy', 'Ecru-red'], ['Merz b. Schwanen']),
  gt('terry-camp-shirt', 'Terry-Cloth Camp Shirt', 'tops', '25-30', [C], ['Boxy'], ['Cream', 'Sea green', 'Navy'], ['Orlebar Brown']),
  gt('henley', 'Henley', 'tops', '15-20', [C], ['Regular', 'Slim'], ['Ecru', 'Grey melange', 'Navy'], ['Merz b. Schwanen', 'Sunspel']),

  // ─── KNITWEAR ───
  gt('shetland-crew', 'Shetland Crew Neck', 'knitwear', '0-5', [C, SC], ['Regular', 'Relaxed'], ['Oatmeal', 'Moss', 'Rust', 'Navy', 'Mustard'], ["Jamieson's of Shetland", 'Harley of Scotland']),
  gt('brushed-shetland', 'Brushed Shetland', 'knitwear', '0-5', [C, SC], ['Regular'], ['Heather', 'Sky', 'Coral', 'Moss'], ['Harley of Scotland', "Drake's"]),
  gt('lambswool-crew', 'Lambswool Crew Neck', 'knitwear', '5-10', [C, SC], ['Regular', 'Slim'], ['Navy', 'Charcoal', 'Camel', 'Bottle green'], ['William Lockie', "Colhay's", 'Harley of Scotland']),
  gt('donegal-crew', 'Donegal Crew Neck', 'knitwear', '0-5', [C, SC], ['Regular'], ['Flecked grey', 'Flecked oat', 'Flecked moss'], ['Inis Me\u00e1in']),
  gt('merino-crew', 'Merino Crew Neck', 'knitwear', '10-15', [SC, B], ['Regular', 'Slim'], ['Navy', 'Charcoal', 'Camel', 'Black'], ['John Smedley', 'William Lockie']),
  gt('cashmere-crew', 'Cashmere Crew Neck', 'knitwear', '5-10', [SC, B], ['Regular', 'Slim'], ['Navy', 'Grey', 'Camel', 'Cream'], ["Colhay's", 'William Lockie', 'Johnstons of Elgin', 'Luca Faloni']),
  gt('cotton-crew', 'Cotton Crew Neck', 'knitwear', '15-20', [C, SC], ['Regular'], ['Ecru', 'Navy', 'Sage'], ['John Smedley', 'Sunspel']),
  gt('linen-crew', 'Linen Crew Neck', 'knitwear', '20-25', [C, SC], ['Regular', 'Relaxed'], ['Ecru', 'Sky', 'Olive'], ['Inis Me\u00e1in', 'Luca Faloni']),
  gt('camelhair-crew', 'Camel Hair Sweater', 'knitwear', '0-5', [SC, B], ['Regular'], ['Camel', 'Dark camel'], ['Johnstons of Elgin']),
  gt('alpaca-crew', 'Alpaca Crew Neck', 'knitwear', '0-5', [C, SC], ['Regular', 'Relaxed'], ['Oat', 'Brown', 'Grey'], ['Inis Me\u00e1in']),
  gt('cable-crew', 'Cable-Knit Crew Neck', 'knitwear', '0-5', [C], ['Regular', 'Relaxed'], ['Cream', 'Navy', 'Grey'], ['William Lockie', 'Inis Me\u00e1in']),
  gt('aran-sweater', 'Aran Sweater', 'knitwear', 'below-0', [C, OW], ['Regular', 'Relaxed'], ['Ecru', 'Oat', 'Charcoal'], ['Inis Me\u00e1in']),
  gt('aran-cardigan', 'Aran Cardigan', 'knitwear', 'below-0', [C], ['Regular'], ['Ecru', 'Grey'], ['Inis Me\u00e1in']),
  gt('guernsey-sweater', 'Guernsey Sweater', 'knitwear', '0-5', [C, OW], ['Traditional square'], ['Navy', 'Ecru', 'Charcoal'], ['Le Tricoteur']),
  gt('submariner-rollneck', 'Submariner Rollneck', 'knitwear', 'below-0', [C, OW], ['Regular', 'Relaxed'], ['Ecru', 'Navy', 'Charcoal'], ['Le Tricoteur']),
  gt('fine-gauge-rollneck', 'Fine-Gauge Rollneck', 'knitwear', '5-10', [SC, B, F], ['Regular', 'Slim'], ['Black', 'Navy', 'Charcoal', 'Cream'], ['John Smedley', "Colhay's"]),
  gt('cashmere-rollneck', 'Cashmere Rollneck', 'knitwear', '5-10', [SC, B], ['Regular'], ['Camel', 'Grey', 'Navy'], ['Johnstons of Elgin', "Colhay's", 'Luca Faloni']),
  gt('mock-neck-knit', 'Mock-Neck Knit', 'knitwear', '5-10', [C, SC], ['Regular', 'Slim'], ['Cream', 'Black', 'Moss'], ['John Smedley']),
  gt('v-neck-sweater', 'V-Neck Sweater', 'knitwear', '10-15', [SC, B], ['Regular', 'Slim'], ['Navy', 'Grey', 'Burgundy'], ['William Lockie', 'John Smedley']),
  gt('cricket-sweater', 'Cricket Sweater', 'knitwear', '10-15', [C, SC], ['Regular'], ['Cream with trim', 'Ecru'], ['William Lockie']),
  gt('fair-isle-sweater', 'Fair Isle Sweater', 'knitwear', '0-5', [C], ['Regular'], ['Traditional multi', 'Oat multi'], ["Jamieson's of Shetland"]),
  gt('nordic-sweater', 'Nordic Patterned Sweater', 'knitwear', 'below-0', [C], ['Regular', 'Relaxed'], ['Grey-white', 'Navy-white'], []),
  gt('lopapeysa', 'Icelandic Lopapeysa', 'knitwear', 'below-0', [C, OW], ['Regular'], ['Grey yoke', 'Brown yoke'], []),
  gt('cowichan-cardigan', 'Cowichan Cardigan', 'knitwear', 'below-0', [C], ['Relaxed'], ['Cream-black motif', 'Grey motif'], []),
  gt('sweater-vest', 'Sweater Vest', 'knitwear', '10-15', [SC, B], ['Regular'], ['Navy', 'Grey', 'Fair Isle'], ['William Lockie', 'John Smedley']),
  gt('fair-isle-vest', 'Fair Isle Vest', 'knitwear', '5-10', [C, SC], ['Regular'], ['Traditional multi'], ["Jamieson's of Shetland"]),
  gt('cardigan', 'Cardigan', 'knitwear', '10-15', [C, SC], ['Regular', 'Slim'], ['Navy', 'Grey', 'Camel'], ['John Smedley', 'William Lockie']),
  gt('shawl-collar-cardigan', 'Shawl-Collar Cardigan', 'knitwear', '0-5', [C, SC], ['Regular', 'Relaxed'], ['Charcoal', 'Oat', 'Navy'], ["Colhay's", 'William Lockie', 'Inis Me\u00e1in']),
  gt('zip-through-cardigan', 'Zip-Through Knit Cardigan', 'knitwear', '5-10', [C], ['Regular'], ['Navy', 'Charcoal'], ['John Smedley']),
  gt('half-zip-knit', 'Half-Zip Knit', 'knitwear', '5-10', [C, SC], ['Regular'], ['Navy', 'Grey', 'Moss'], ['John Smedley', 'William Lockie']),
  gt('knitted-polo-shirt', 'Knitted Polo Shirt', 'knitwear', '20-25', [SC, B], ['Regular', 'Slim'], ['Navy', 'Cream', 'Sage', 'Chocolate'], ['John Smedley', "Colhay's", 'Luca Faloni']),
  gt('polo-collar-sweater', 'Polo-Collar Sweater', 'knitwear', '10-15', [SC, B], ['Regular'], ['Navy', 'Grey', 'Rust'], ["Colhay's", 'John Smedley']),
  gt('knitted-tee', 'Knitted T-Shirt', 'knitwear', '20-25', [SC], ['Regular'], ['Ecru', 'Navy', 'Olive'], ['John Smedley', 'Luca Faloni']),
  gt('commando-sweater', 'Commando Sweater', 'knitwear', '0-5', [OW, C], ['Regular'], ['Olive', 'Navy', 'Black'], []),
  gt('fisherman-rib-crew', 'Fisherman-Rib Crew Neck', 'knitwear', '0-5', [C], ['Regular', 'Relaxed'], ['Ecru', 'Navy', 'Moss'], ['Inis Me\u00e1in', 'William Lockie']),

  // ─── SWEATSHIRTS ───
  gt('crewneck-sweatshirt', 'Crewneck Sweatshirt', 'sweatshirts', '10-15', [C], ['Regular', 'Relaxed', 'Boxy'], ['Grey melange', 'Navy', 'Ecru', 'Faded black'], ['Merz b. Schwanen', 'Lady White Co.', 'Sunspel']),
  gt('loopwheel-sweatshirt', 'Loopwheel Sweatshirt', 'sweatshirts', '10-15', [C], ['Regular', 'Boxy'], ['Grey melange', 'Ecru', 'Navy'], ['Merz b. Schwanen', 'Buzz Rickson']),
  gt('reverse-weave-sweatshirt', 'Reverse-Weave Sweatshirt', 'sweatshirts', '5-10', [C], ['Boxy'], ['Grey', 'Navy', 'Forest'], []),
  gt('salt-pepper-sweatshirt', 'Salt-and-Pepper Sweatshirt', 'sweatshirts', '10-15', [C], ['Regular', 'Boxy'], ['Salt-and-pepper grey'], ['Merz b. Schwanen']),
  gt('pullover-hoodie', 'Pullover Hoodie', 'sweatshirts', '10-15', [C], ['Regular', 'Relaxed'], ['Grey melange', 'Navy', 'Black'], ['Lady White Co.', 'Sunspel']),
  gt('zip-hoodie', 'Zip-Through Hoodie', 'sweatshirts', '10-15', [C], ['Regular'], ['Grey melange', 'Navy', 'Black'], ['Lady White Co.']),
  gt('half-zip-sweatshirt', 'Half-Zip Sweatshirt', 'sweatshirts', '10-15', [C], ['Regular'], ['Grey', 'Navy', 'Olive'], ['Lady White Co.']),
  gt('raglan-gym-sweatshirt', 'Raglan Gym Sweatshirt', 'sweatshirts', '10-15', [C], ['Regular'], ['Grey melange', 'Oat'], ['Merz b. Schwanen', 'Buzz Rickson']),
  gt('terry-sweatshirt', 'Terry-Towelling Sweatshirt', 'sweatshirts', '15-20', [C], ['Regular'], ['Cream', 'Navy', 'Sage'], ['Orlebar Brown']),

  // ─── BASE LAYERS ───
  gt('crew-undershirt', 'Crew-Neck Undershirt', 'base-layers', '10-15', [C, SC, B, F], ['Regular', 'Slim'], ['White', 'Grey'], ['Sunspel', 'Hanro', 'Merz b. Schwanen']),
  gt('v-neck-undershirt', 'V-Neck Undershirt', 'base-layers', '10-15', [SC, B, F], ['Slim'], ['White'], ['Hanro', 'Sunspel']),
  gt('tank-undershirt', 'Tank Undershirt', 'base-layers', '15-20', [C], ['Regular'], ['White', 'Grey'], ['Hanro', 'Merz b. Schwanen']),
  gt('waffle-henley', 'Waffle Thermal Henley', 'base-layers', '0-5', [C, OW], ['Regular'], ['Ecru', 'Grey', 'Olive'], ['Merz b. Schwanen']),
  gt('thermal-long-johns', 'Thermal Long Johns', 'base-layers', 'below-0', [C, OW], ['Regular'], ['Ecru', 'Grey'], ['Hanro', 'Merz b. Schwanen']),
  gt('merino-base-top', 'Merino Base-Layer Top', 'base-layers', '0-5', [C, OW], ['Regular', 'Slim'], ['Black', 'Grey', 'Navy'], ['Smartwool', 'Icebreaker']),
  gt('merino-leggings', 'Merino Base-Layer Leggings', 'base-layers', 'below-0', [C, OW], ['Regular'], ['Black', 'Grey'], ['Smartwool', 'Icebreaker']),
  gt('technical-base-top', 'Technical Base-Layer Top', 'base-layers', '0-5', [C, OW], ['Slim'], ['Black', 'White'], ['Uniqlo']),
  gt('string-mesh-vest', 'String Mesh Vest', 'base-layers', '0-5', [OW, C], ['Regular'], ['Ecru', 'Olive'], []),
  gt('heavyweight-thermal-crew', 'Heavyweight Thermal Crew', 'base-layers', '0-5', [C, OW], ['Regular'], ['Ecru', 'Grey', 'Navy'], ['Merz b. Schwanen']),
  gt('union-suit', 'Union Suit', 'base-layers', 'below-0', [OW, C], ['Regular'], ['Ecru', 'Red'], ['Merz b. Schwanen']),
  gt('boxer-shorts', 'Boxer Shorts', 'base-layers', '10-15', [C, SC, B, F], ['Regular'], ['White', 'Blue stripe', 'Patterned'], ['Sunspel', 'Hanro']),
  gt('boxer-briefs', 'Boxer Briefs', 'base-layers', '10-15', [C, SC, B, F], ['Regular'], ['White', 'Grey', 'Black', 'Navy'], ['Sunspel', 'Hanro', 'Uniqlo']),
  gt('briefs', 'Briefs', 'base-layers', '10-15', [C, SC, B, F], ['Regular'], ['White', 'Grey', 'Black'], ['Hanro', 'Sunspel']),
];
