/**
 * WORLD OF MENSWEAR — entries, part 4 of 4: ACCESSORIES, BAGS and
 * HATS/HEADWEAR. See world-entries-1.ts for the editorial conventions.
 */
import type { WorldEntry } from './world-types';

export const WORLD_ENTRIES_ACC_BAGS_HATS: WorldEntry[] = [
  // =========================================================================
  // ACCESSORIES
  // =========================================================================
  {
    id: 'belt',
    name: 'Belt',
    categoryId: 'accessories',
    what: 'The leather strap that finishes a trouser waist: dress belts are narrow (around 3cm), bridle- or box-calf with a discreet buckle; casual belts run wider in thicker, oilier leathers. The old harmony — belt matches shoes — still quietly works.',
    history: 'Belts replaced braces as trousers acquired belt loops in the early twentieth century — a sportswear innovation that became universal. Bridle leather from English tanneries remains the benchmark strap.',
    useCase: 'Every trouser with loops. One dark brown and one black dress belt plus one heavier casual belt answer nearly every outfit; suede versions bridge the smart-casual middle beautifully.',
    pairings: ['Match the leather to your shoes', 'Suede belt with flannels and loafers', 'A heavy bridle belt with raw denim', 'No belt at all with side-adjuster trousers'],
    essential: true,
    find: [
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=bridle+leather+belt+english' },
      { retailer: 'Etsy', url: 'https://www.etsy.com/search?q=bridle+leather+belt+handmade' },
      { retailer: 'Mr Porter', url: 'https://www.mrporter.com/en-gb/mens/search?keywords=leather+belt' },
    ],
    keywords: ['belt', 'leather belt', 'bridle belt'],
  },
  {
    id: 'watch',
    name: 'Watch (Dress, Field, Diver)',
    categoryId: 'accessories',
    what: 'The one piece of jewellery tradition hands a man, in three canonical forms: the dress watch (thin, plain dial, leather strap), the field watch (legible, workmanlike, canvas or leather), and the diver (rotating bezel, bracelet, built for depth).',
    history: 'Wristwatches replaced pocket watches through WWI trench necessity. The mid-century established the archetypes — Calatrava the dress ideal, military-issue fields, and the 1950s divers (Submariner, Fifty Fathoms) that became the most copied designs on earth.',
    useCase: 'Dress with tailoring, field with casualwear, diver with almost anything — the diver-with-a-suit tension is a post-Bond privilege. One honest watch worn daily beats a drawer of occasional ones.',
    pairings: ['A dress watch with a dinner suit', 'A field watch with a chore coat', 'A diver on a NATO strap in summer', 'Leather strap matched loosely to shoes'],
    essential: true,
    find: [
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=field+watch+hand+wound' },
      { retailer: 'Mr Porter', url: 'https://www.mrporter.com/en-gb/mens/search?keywords=watches' },
      { retailer: 'Grailed', url: 'https://www.grailed.com/shop?query=vintage+watch' },
    ],
    keywords: ['watch', 'wristwatch', 'dress watch', 'field watch', 'diver watch'],
  },
  {
    id: 'pocket-square',
    name: 'Pocket Square',
    categoryId: 'accessories',
    what: 'The square of silk, linen or cotton folded into a jacket’s breast pocket. White linen in a TV fold is the eternal baseline; silk squares add colour that should echo — never match — the tie. It is finish, not function.',
    history: 'Handkerchiefs are ancient; the decorative breast-pocket square arrived with the two-piece suit in the early twentieth century, peaked with Golden Age Hollywood, and never quite left the well-dressed jacket.',
    useCase: 'Any jacket with a welt pocket, any time you want the outfit to look completed rather than assembled. White linen with everything; patterns only when the rest of the chest is quiet.',
    pairings: ['A navy blazer (white linen, TV fold)', 'A tweed jacket (wool square, puffed)', 'A dinner jacket (white, one point)', 'Never matching the tie exactly'],
    essential: false,
    find: [
      { retailer: "Drake's", url: 'https://drakes.com/search?q=pocket+square' },
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=linen+pocket+square' },
      { retailer: 'Etsy', url: 'https://www.etsy.com/search?q=silk+pocket+square' },
    ],
    keywords: ['pocket square', 'handkerchief', 'hank'],
  },
  {
    id: 'tie',
    name: 'Tie (Silk, Knit, Wool)',
    categoryId: 'accessories',
    what: 'The strip of cloth that formalises a collar: printed or woven silk for business and occasion, the square-ended knitted tie for texture and ease, wool and cashmere for winter tailoring. Around 8cm wide and ending at the waistband, decade in, decade out.',
    history: 'Croatian mercenaries’ neck cloths (“cravate”) charmed seventeenth-century Paris; the long tie and the four-in-hand knot won the nineteenth century, and Jesse Langsdorf’s 1922 bias-cut patent gave the modern tie its recovery and drape.',
    useCase: 'Where respect or occasion asks for it — and, worn by choice with a tweed jacket or knit, as the most direct signal that an outfit is deliberate. The four-in-hand is the only knot most men ever need.',
    pairings: ['A grenadine with a navy suit', 'A knitted tie with an OCBD and tweed', 'Wool challis with flannel in winter', 'A dimple, always'],
    essential: true,
    find: [
      { retailer: "Drake's", url: 'https://drakes.com/search?q=tie' },
      { retailer: 'Berg & Berg', url: 'https://bergbergstore.com/search?q=tie' },
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=grenadine+silk+tie' },
    ],
    keywords: ['tie', 'necktie', 'knitted tie', 'grenadine'],
  },
  {
    id: 'bow-tie',
    name: 'Bow Tie',
    categoryId: 'accessories',
    what: 'The self-tied bow at the collar — black silk for evening dress, patterned silk or cotton for day wear among the confident. Self-tie is the only version that counts: the slight asymmetry of a hand-tied bow is the point.',
    history: 'Another descendant of the Croat cravat, settled into its modern form in the nineteenth century. Black tie made it mandatory after dark; academia, architects and bon vivants kept the daytime version alive.',
    useCase: 'Compulsory with a dinner jacket; optional armour for those whose personality carries it by day. Learn the knot — it is a shoelace in slow motion, and clip-ons betray at close range.',
    pairings: ['A dinner suit (black silk, self-tied)', 'A tweed jacket for donnish day wear', 'A marcella shirt at white tie', 'A cardigan, at the eccentric end'],
    essential: false,
    find: [
      { retailer: "Drake's", url: 'https://drakes.com/search?q=bow+tie' },
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=self+tie+silk+bow+tie' },
      { retailer: 'Etsy', url: 'https://www.etsy.com/search?q=self+tie+bow+tie' },
    ],
    keywords: ['bow tie', 'bowtie', 'black tie bow'],
  },
  {
    id: 'cufflinks',
    name: 'Cufflinks',
    categoryId: 'accessories',
    what: 'The fastenings for double (French) cuffs: two decorative faces joined by a link or bar, in silver, gold, enamel, silk knots or vintage novelty. They exist only where the shirt demands them — which is what makes them an occasion.',
    history: 'As shirt cuffs stiffened with starch in the seventeenth–nineteenth centuries, buttons lost the fight and jewelled links took over. The double cuff survives as the formal shirt’s signature, links as the last male jewellery box.',
    useCase: 'French-cuff shirts at weddings, black tie and boardroom-formal settings. Silk knots for modesty, silver ovals for everything, inherited pairs for meaning.',
    pairings: ['A double-cuff poplin shirt', 'A three-piece suit', 'A dinner jacket (with studs to match)', 'A watch that does not fight them'],
    essential: false,
    find: [
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=vintage+silver+cufflinks' },
      { retailer: 'Etsy', url: 'https://www.etsy.com/search?q=sterling+silver+cufflinks' },
      { retailer: 'Mr Porter', url: 'https://www.mrporter.com/en-gb/mens/search?keywords=cufflinks' },
    ],
    keywords: ['cufflinks', 'cuff links', 'silk knots'],
  },
  {
    id: 'collar-bar',
    name: 'Collar Bar / Pin',
    categoryId: 'accessories',
    what: 'A metal bar or pin that passes under the tie knot and joins the collar points — clipping, screwing or piercing through — lifting the knot forward into a small arc of self-assurance. A precision detail from tailoring’s golden age.',
    history: 'An Edwardian device that peaked in the 1920s–30s — every Golden Age illustration shows the lifted knot — and returns whenever that era does (Boardwalk Empire single-handedly revived pinned collars).',
    useCase: 'With soft point collars and a four-in-hand — the bar needs room and the knot needs smallness. Business-with-flair or vintage-leaning tailoring; never with button-downs or cutaways.',
    pairings: ['A pin-collar shirt and grenadine tie', 'A three-piece flannel suit', 'A covert coat and trilby', 'A tie bar is redundant with it — choose one'],
    essential: false,
    find: [
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=collar+bar+pin+vintage' },
      { retailer: 'Etsy', url: 'https://www.etsy.com/search?q=collar+pin+bar' },
      { retailer: 'Grailed', url: 'https://www.grailed.com/shop?query=collar+pin' },
    ],
    keywords: ['collar bar', 'collar pin', 'pin collar'],
  },
  {
    id: 'braces',
    name: 'Braces / Suspenders',
    categoryId: 'accessories',
    what: 'Elastic or boxcloth straps that hold trousers from the shoulders, fastening to buttons inside the waistband (clips are the compromise the garment tolerates, not the one it respects). Trousers hang from braces; they grip from belts — the drape is visibly better.',
    history: 'Albert Thurston has made them in London since 1820; every trouser before the belt era assumed them. High-rise tailoring, City tradition and workwear all kept separate brace cultures alive.',
    useCase: 'With high-rise tailored trousers — especially three-piece suits and formal dress, where the waistband must never dip. Under the waistcoat or jacket they are private engineering; wearing them exposed is a costume choice.',
    pairings: ['High-rise flannels with brace buttons', 'A three-piece suit', 'White tie (white braces, by law of custom)', 'Never with a belt — one system at a time'],
    essential: false,
    find: [
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=albert+thurston+braces' },
      { retailer: 'Etsy', url: 'https://www.etsy.com/search?q=boxcloth+braces+men' },
      { retailer: 'Mr Porter', url: 'https://www.mrporter.com/en-gb/mens/search?keywords=braces+suspenders' },
    ],
    keywords: ['braces', 'suspenders', 'boxcloth braces'],
  },
  {
    id: 'scarf',
    name: 'Scarf (Wool, Cashmere, Silk)',
    categoryId: 'accessories',
    what: 'The neck’s answer to weather and the coat’s answer to colour: lambswool and cashmere for warmth, silk for polish (the evening white silk scarf is its own institution), wool challis prints for the middle ground.',
    history: 'From Roman sudaria to aviators’ silks to the university stripes of the college scarf — the scarf has been rank, allegiance and warmth by turns. The dress scarf tradition survives strongest in Britain and Italy.',
    useCase: 'Every coat from October to March — the once-around or the drape for short coats, the Parisian loop for overcoats. It is the cheapest way to make the same coat read differently all winter.',
    pairings: ['A navy overcoat and grey scarf', 'A camel coat and burgundy cashmere', 'White silk with a dinner suit and overcoat', 'A duffle coat and college stripes'],
    essential: true,
    find: [
      { retailer: "Colhay's", url: 'https://colhays.com/search?q=scarf' },
      { retailer: "Drake's", url: 'https://drakes.com/search?q=scarf' },
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=cashmere+scarf+scotland' },
    ],
    keywords: ['scarf', 'muffler', 'cashmere scarf'],
  },
  {
    id: 'gloves',
    name: 'Gloves (Leather, Wool)',
    categoryId: 'accessories',
    what: 'Winter’s hand dressing: unlined or cashmere-lined leather (peccary and hairsheep at the top of the tree) for smart wear, knitted wool for casual. Leather gloves should fit close enough to show the knuckles’ landscape.',
    history: 'Gloves carried centuries of etiquette — thrown down for duels, removed for handshakes — and glovemaking cities (Naples, Millau, Worcester) built industries on the skill. The dress-glove habit faded with hat-wearing; the craft survives.',
    useCase: 'With overcoats and tailoring, leather in brown or grey (black for formal wear); wool or shearling with casual coats. Cashmere-lined is the correct indulgence — hands notice.',
    pairings: ['A covert coat and brown gloves', 'A peacoat and knitted gloves', 'A trench and grey unlined leather', 'Black leather with a dark formal coat'],
    essential: true,
    find: [
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=cashmere+lined+leather+gloves+men' },
      { retailer: 'Etsy', url: 'https://www.etsy.com/search?q=leather+dress+gloves+men' },
      { retailer: 'Mr Porter', url: 'https://www.mrporter.com/en-gb/mens/search?keywords=leather+gloves' },
    ],
    keywords: ['gloves', 'leather gloves', 'wool gloves'],
  },
  {
    id: 'lapel-pin',
    name: 'Lapel Pin',
    categoryId: 'accessories',
    what: 'The small ornament for a jacket’s lapel: a boutonnière flower (real or silk) through the buttonhole, a stick pin, or a discreet enamel badge. One small object doing one small job — signalling that the wearer noticed his own lapel.',
    history: 'The buttonhole flower was Victorian and Edwardian daily dress — a fresh gardenia or cornflower from the market. Club, regimental and society pins carried the badge tradition; the modern silk boutonnière revives the flower without the vase.',
    useCase: 'Weddings (the classic boutonnière moment), occasions, and tailoring that wants one point of wit. One pin, small, and never competing with a pocket square for attention.',
    pairings: ['A morning coat at a wedding', 'A plain navy suit needing one grace note', 'A tweed jacket and wool tie', 'Nothing else ornamental nearby'],
    essential: false,
    find: [
      { retailer: 'Etsy', url: 'https://www.etsy.com/search?q=silk+boutonniere+lapel+pin' },
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=vintage+stick+pin+lapel' },
      { retailer: 'Grailed', url: 'https://www.grailed.com/shop?query=lapel+pin' },
    ],
    keywords: ['lapel pin', 'boutonniere', 'stick pin'],
  },
  {
    id: 'hat-pin',
    name: 'Hat Pin',
    categoryId: 'accessories',
    what: 'A small decorative pin worn in a hat’s band — feathers, brushes and badges are its cousins. On a felt hat, a discreet side ornament above the bow; historically also the long functional pin that anchored hats to hair.',
    history: 'Functional hat pins belonged to the great hat era — anchoring and adorning through the nineteenth and early twentieth centuries. Tyrolean and country hats kept the decorative tradition of feathers and Gamsbart brushes alive.',
    useCase: 'For the committed hat wearer: one small pin or feather in the band of a felt hat, country-leaning by nature. It is punctuation for the hat, not a headline.',
    pairings: ['A wool felt hat with a grosgrain band', 'A loden coat, in the Alpine spirit', 'A tweed suit at the races', 'Restraint, above all'],
    essential: false,
    find: [
      { retailer: 'Etsy', url: 'https://www.etsy.com/search?q=hat+pin+feather+fedora' },
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=hat+feather+pin+brooch' },
    ],
    keywords: ['hat pin', 'hat feather', 'hat brooch'],
  },
  {
    id: 'tie-bar',
    name: 'Tie Bar / Clip',
    categoryId: 'accessories',
    what: 'A slim metal bar that clips the tie to the shirt placket, keeping it in place and adding one horizontal glint. Rules: between the third and fourth shirt buttons, never wider than the tie, and always slightly askew of perfection in spirit.',
    history: 'A 1920s–30s practicality (ties once flew about) that became mid-century signature — Mad Men’s wardrobe department re-taught a generation how to wear one.',
    useCase: 'Working days with a tie — it earns its place bending over desks and lunches. Silver or brushed steel with everything; skip it when wearing a waistcoat or collar pin, which do its job.',
    pairings: ['A navy suit and silk tie', 'An OCBD and knit tie for Ivy neatness', 'A grey flannel suit', 'Not with a cardigan holding the tie anyway'],
    essential: false,
    find: [
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=vintage+tie+bar+silver' },
      { retailer: 'Etsy', url: 'https://www.etsy.com/search?q=sterling+tie+bar' },
      { retailer: 'Mr Porter', url: 'https://www.mrporter.com/en-gb/mens/search?keywords=tie+bar' },
    ],
    keywords: ['tie bar', 'tie clip', 'tie slide'],
  },
  {
    id: 'wallet',
    name: 'Wallet',
    categoryId: 'accessories',
    what: 'The leather keeper of the pocket: the folding billfold, the slim cardholder (the modern default as cash retreats), and the breast-pocket coat wallet. Full-grain leather, saddle-stitched, ages into a private patina no new object has.',
    history: 'Purses predate pockets; the folding banknote wallet arrived with paper currency in the seventeenth–nineteenth centuries. The cardholder’s rise is simply the wallet evolving with what money became.',
    useCase: 'Daily, invisibly — which is exactly why quality matters: it is handled more than any other object you own. Slim always; the overstuffed billfold ruins trouser and jacket lines alike.',
    pairings: ['A cardholder in a trouser pocket', 'A coat wallet in a suit’s breast pocket', 'Chestnut or dark brown with most wardrobes', 'A key fob in matching leather'],
    essential: true,
    find: [
      { retailer: 'Etsy', url: 'https://www.etsy.com/search?q=full+grain+leather+cardholder+handmade' },
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=leather+billfold+wallet+made+in+england' },
      { retailer: 'Mr Porter', url: 'https://www.mrporter.com/en-gb/mens/search?keywords=cardholder' },
    ],
    keywords: ['wallet', 'cardholder', 'card holder', 'billfold'],
  },
  {
    id: 'key-fob',
    name: 'Key Fob',
    categoryId: 'accessories',
    what: 'The small leather or brass keeper that organises keys — a loop, hook or Chelsea-style “fob” that makes them findable in a bag and civilised in a pocket. Minor object, daily service.',
    history: 'Watch fobs — the chains and ornaments of pocket-watch dress — lent the name; leather goods houses scaled the idea to keys as the pocket watch retired. The sailor’s brass hook lineage survives in the best designs.',
    useCase: 'Every day, on the keys — especially once a good bag enters the rotation and keys need finding by feel. Brass and bridle leather age together handsomely.',
    pairings: ['A tote or briefcase it can clip into', 'A wallet in the same leather family', 'Jeans — belt-loop hooked, workwear style', 'Nothing — it is jewellery for keys'],
    essential: false,
    find: [
      { retailer: 'Etsy', url: 'https://www.etsy.com/search?q=brass+leather+key+fob' },
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=leather+key+fob+brass+hook' },
      { retailer: 'Bennett Winch', url: 'https://www.bennettwinch.com/search?q=key' },
    ],
    keywords: ['key fob', 'key holder', 'key hook'],
  },
  {
    id: 'sunglasses',
    name: 'Sunglasses',
    categoryId: 'accessories',
    what: 'Eye protection that became the twentieth century’s most efficient charisma device. The classic shapes — aviator, wayfarer, clubmaster, round wire — all date from before 1960 and fit the same face rules: frame width matches face width, brow line follows the frame’s top.',
    history: 'Aviators were military issue (Bausch & Lomb, 1936, for pilots’ glare); the Wayfarer (1952) put attitude into acetate. Persol’s foldables, McQueen’s 714s and one Vogue-era Onassis photo did the rest.',
    useCase: 'Sun, obviously — but choose one classic shape in acetate or wire and wear it for years. Green and grey lenses read neutral; brown warms; never mirrored with tailoring.',
    pairings: ['A camp collar shirt on holiday', 'A suit — the aviator’s favourite tension', 'A Harrington and tee', 'A panama, carefully, at the beach'],
    essential: true,
    find: [
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=persol+714+sunglasses' },
      { retailer: 'Mr Porter', url: 'https://www.mrporter.com/en-gb/mens/search?keywords=sunglasses' },
      { retailer: 'Grailed', url: 'https://www.grailed.com/shop?query=vintage+sunglasses' },
    ],
    keywords: ['sunglasses', 'shades', 'aviator', 'wayfarer'],
  },
  {
    id: 'umbrella',
    name: 'Umbrella',
    categoryId: 'accessories',
    what: 'The full-length stick umbrella — one-piece solid shaft (maple, chestnut, malacca), a proper crook handle, and a canopy that opens like punctuation. The collapsible is a tool; the stick umbrella is a garment you hold.',
    history: 'Jonas Hanway scandalised 1750s London by carrying one (umbrellas were French, effete, and rain was for enduring); within a century it was the City gent’s sceptre. James Smith & Sons has sold them on New Oxford Street since 1830.',
    useCase: 'Proper rain over proper clothes — it protects tailoring a hood would crush. Navy or black canopy always; the wooden crook doubles as a walking stick and a coat-check conversation.',
    pairings: ['A trench or covert coat', 'A City suit, umbrella furled tight', 'A mac and brogues', 'Rolled — a well-furled umbrella is half its beauty'],
    essential: false,
    find: [
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=solid+stick+umbrella+crook+handle' },
      { retailer: 'Etsy', url: 'https://www.etsy.com/search?q=gentlemans+umbrella+wood+handle' },
      { retailer: 'Mr Porter', url: 'https://www.mrporter.com/en-gb/mens/search?keywords=umbrella' },
    ],
    keywords: ['umbrella', 'stick umbrella', 'brolly'],
  },
  {
    id: 'ascot-cravat',
    name: 'Ascot / Cravat',
    categoryId: 'accessories',
    what: 'Neckwear without the tie’s verticality: the day cravat worn inside an open shirt collar (silk, loosely knotted, faintly raffish) and the formal ascot worn over the shirt with morning dress, pinned. Two garments sharing one family name.',
    history: 'The direct heir of the seventeenth-century cravat that fathered all neckwear. The formal ascot belonged to Royal Ascot’s enclosures; the day cravat to the twentieth century’s silk-dressing-gown class — Grant, Niven, and every actor playing one.',
    useCase: 'The day cravat with an open collar and a blazer for occasions that want polish without a tie; the pinned ascot only with morning dress. Confidence is the actual fabric.',
    pairings: ['A blazer and open OCBD', 'A camel coat, silk at the throat', 'Morning dress (the pinned formal version)', 'A dressing gown, at home, legitimately'],
    essential: false,
    find: [
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=silk+day+cravat+ascot' },
      { retailer: 'Etsy', url: 'https://www.etsy.com/search?q=silk+ascot+cravat+men' },
      { retailer: "Drake's", url: 'https://drakes.com/search?q=cravat' },
    ],
    keywords: ['ascot', 'cravat', 'day cravat', 'neckerchief'],
  },
  {
    id: 'cummerbund',
    name: 'Cummerbund',
    categoryId: 'accessories',
    what: 'The pleated silk waist sash of black tie, worn with single-breasted dinner jackets to cover the waistband — pleats facing up (they once held theatre tickets). It completes the unbroken dark column evening dress is built on.',
    history: 'From the Hindi “kamarband” — British officers in India adopted the sash as a cooler waistcoat substitute for mess dress in the nineteenth century, and it travelled home into black tie’s rulebook.',
    useCase: 'Black tie with a single-breasted jacket and no waistcoat — one or the other, never neither, never both. Black grosgrain or barathea to match the lapels; midnight if the suit is.',
    pairings: ['A shawl-collar dinner jacket', 'A marcella shirt and black bow tie', 'Braces beneath (a belt is unthinkable here)', 'Opera pumps to finish'],
    essential: false,
    find: [
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=silk+cummerbund+black' },
      { retailer: 'Etsy', url: 'https://www.etsy.com/search?q=silk+cummerbund' },
      { retailer: 'Mr Porter', url: 'https://www.mrporter.com/en-gb/mens/search?keywords=cummerbund' },
    ],
    keywords: ['cummerbund', 'kamarband', 'waist sash'],
  },

  // =========================================================================
  // BAGS
  // =========================================================================
  {
    id: 'tote',
    name: 'Tote',
    categoryId: 'bags',
    what: 'The open-topped carryall with two handles — canvas with leather trim in its classic form, all-leather in its smart one. It swallows a day’s objects without ceremony, which is its entire philosophy.',
    history: 'L.L.Bean’s 1944 Boat and Tote — built to haul ice — fathered the type; decades of boat clubs, bookshops and design houses turned the ice bag into the default civilised carry.',
    useCase: 'Daily life: laptop, book, gym kit, groceries — one bag, no zips to argue with. Canvas versions improve with grime; leather ones with everything else.',
    pairings: ['A chore coat and jeans', 'Summer tailoring, canvas against cloth', 'A weekend uniform of tee and chinos', 'A market on Saturday morning'],
    essential: true,
    find: [
      { retailer: 'Bennett Winch', url: 'https://www.bennettwinch.com/search?q=tote' },
      { retailer: 'Filson', url: 'https://www.filson.com/search?q=tote' },
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=canvas+leather+tote+bag+men' },
    ],
    keywords: ['tote', 'tote bag', 'carryall'],
  },
  {
    id: 'weekender',
    name: 'Weekender / Holdall',
    categoryId: 'bags',
    what: 'The soft duffel sized for two or three days — canvas or leather, one cavernous zipped compartment, carried by hand or shoulder strap. Cabin-sized by design and better-looking than any wheeled case will ever be.',
    history: 'The sports and kit bags of the early twentieth century — cricket, boxing, flying — grew into the gentleman’s travel holdall as the weekend itself was invented. British saddlery brands made it a leather-goods benchmark.',
    useCase: 'Short trips, overnights and the gym’s upper tax bracket. One good holdall in canvas-and-leather outlives a decade of nylon; it also carries the suit carrier role in hybrid designs.',
    pairings: ['A blazer and jeans through a train station', 'A waxed jacket on a country weekend', 'White sneakers and a knitted polo', 'A dopp kit inside, matching'],
    essential: true,
    find: [
      { retailer: 'Bennett Winch', url: 'https://www.bennettwinch.com/search?q=holdall' },
      { retailer: 'Filson', url: 'https://www.filson.com/search?q=duffle' },
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=leather+canvas+holdall+weekender' },
    ],
    keywords: ['weekender', 'holdall', 'duffle bag', 'duffel bag'],
  },
  {
    id: 'briefcase',
    name: 'Briefcase',
    categoryId: 'bags',
    what: 'The structured work bag: bridle or box leather, a frame or flap top, and the presence of an object built for documents that mattered. The attaché (rigid, boxy) and the soft flap case are its two poles.',
    history: 'From the lawyer’s brief bag — literally the bag for briefs — formalised through nineteenth-century saddlery into the executive icon. Swaine Adeney and Papworth cases became knighthood-adjacent objects.',
    useCase: 'Suited work and any meeting where the bag speaks before you do. Dark brown or black bridle leather over decades — it is furniture for the working life.',
    pairings: ['A navy suit and covert coat', 'A trench on a wet commute', 'Oxfords, polished, inevitably', 'A stick umbrella in the same hand'],
    essential: false,
    find: [
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=bridle+leather+briefcase+english' },
      { retailer: 'Etsy', url: 'https://www.etsy.com/search?q=leather+briefcase+handmade' },
      { retailer: 'Mr Porter', url: 'https://www.mrporter.com/en-gb/mens/search?keywords=briefcase' },
    ],
    keywords: ['briefcase', 'attache', 'work bag'],
  },
  {
    id: 'portfolio',
    name: 'Portfolio / Folio',
    categoryId: 'bags',
    what: 'The slim, handle-less leather envelope for documents and a tablet or thin laptop — zipped or open-topped, carried in the hand or under the arm. The briefcase’s minimalist heir for lives that no longer carry much.',
    history: 'From the Italian “portafoglio” — carrier of leaves. Artists’ and bankers’ folios both fed the type; the laptop’s shrinking thickness gave it a second life as the elegant answer to the rucksack-with-a-suit problem.',
    useCase: 'Meetings, presentations and travel days when everything fits in ten millimetres of leather. It forces an edit of what you carry — which is half its point.',
    pairings: ['An unstructured suit, no tie', 'A knitted polo and pleated trousers', 'A car coat between offices', 'A cardholder and phone — the full kit'],
    essential: false,
    find: [
      { retailer: 'Etsy', url: 'https://www.etsy.com/search?q=leather+portfolio+folio+case' },
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=leather+document+folio+case' },
      { retailer: 'Mr Porter', url: 'https://www.mrporter.com/en-gb/mens/search?keywords=portfolio+case' },
    ],
    keywords: ['portfolio', 'folio', 'document case'],
  },
  {
    id: 'messenger-bag',
    name: 'Messenger Bag',
    categoryId: 'bags',
    what: 'The cross-body flap bag — canvas or leather, one strap worn across the chest, the flap buckled or clipped over a soft body. Between satchel (school) and courier (bike) sits the civilian messenger: hands-free and unfussy.',
    history: 'Lineman’s and postal bags supplied the pattern; New York bike couriers of the 1980s–90s made it urban equipment, and the laptop era made it the first bag a generation carried to work.',
    useCase: 'Commutes and cities — anywhere hands are needed and shoulders can serve. It sits best against casualwear and soft tailoring; against a structured suit the strap fights the shoulders.',
    pairings: ['A chore coat and jeans', 'A raincoat on a bike', 'Knitwear — the strap flattens poplin', 'Boots or sneakers, never Oxfords'],
    essential: false,
    find: [
      { retailer: 'Filson', url: 'https://www.filson.com/search?q=messenger' },
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=waxed+canvas+messenger+bag' },
      { retailer: 'Etsy', url: 'https://www.etsy.com/search?q=leather+messenger+bag+men' },
    ],
    keywords: ['messenger bag', 'satchel', 'crossbody bag', 'shoulder bag'],
  },
  {
    id: 'backpack',
    name: 'Backpack (Minimal)',
    categoryId: 'bags',
    what: 'The two-strap carry in its grown-up form: clean lines, quality cloth (ballistic nylon, canvas, leather trim), no climbing hardware, no logo shouting. It carries the most weight with the least strain — the ergonomics never stopped being right.',
    history: 'From military rucksacks and alpine sacs through Japanese city-pack culture, the minimal backpack was rehabilitated for adult wardrobes in the 2010s — the answer to laptops, gyms and backs that had opinions.',
    useCase: 'Commuting, travel and any day carrying real weight — with casualwear and knitwear naturally; with tailoring only in its sleekest, darkest form (and even then the coat suffers).',
    pairings: ['An overshirt and jeans', 'A parka in winter', 'Sneakers and a zip-neck knit', 'Travel tailoring, dark pack, if you must'],
    essential: true,
    find: [
      { retailer: 'Filson', url: 'https://www.filson.com/search?q=backpack' },
      { retailer: 'Bennett Winch', url: 'https://www.bennettwinch.com/search?q=backpack' },
      { retailer: 'Mr Porter', url: 'https://www.mrporter.com/en-gb/mens/search?keywords=backpack' },
    ],
    keywords: ['backpack', 'rucksack', 'daypack'],
  },
  {
    id: 'dopp-kit',
    name: 'Dopp Kit / Wash Bag',
    categoryId: 'bags',
    what: 'The zipped toiletry case — leather or waxed canvas, wipeable lining, sized for a razor, brush and the honest minimum. The travelling wardrobe’s smallest member and its most frequently handled.',
    history: '“Dopp” was Charles Doppelt, a Chicago leather-goods maker whose kits were issued to millions of GIs in WWII — the army made the name generic. The British “wash bag” tradition ran parallel through saddlery houses.',
    useCase: 'Every trip, permanently packed — the discipline of a duplicated kit (razor, toothbrush, the lot) is the frequent traveller’s cheapest luxury.',
    pairings: ['A holdall it lives inside', 'A leather tote for gym days', 'Its own hook in any bathroom', 'A matching key fob, for the set'],
    essential: true,
    find: [
      { retailer: 'Bennett Winch', url: 'https://www.bennettwinch.com/search?q=wash+bag' },
      { retailer: 'Filson', url: 'https://www.filson.com/search?q=travel+kit' },
      { retailer: 'Etsy', url: 'https://www.etsy.com/search?q=leather+dopp+kit' },
    ],
    keywords: ['dopp kit', 'wash bag', 'toiletry bag'],
  },
  {
    id: 'document-tube',
    name: 'Document Tube',
    categoryId: 'bags',
    what: 'The cylindrical case — leather, canvas or rigid — for drawings, plans and anything that must roll rather than fold. A specialist object with an architect’s romance about it.',
    history: 'Map and chart cases served soldiers, surveyors and navigators for two centuries; the architect’s drawing tube civilianised the form. Leather versions from English makers turned the site tool into a studio signature.',
    useCase: 'Carrying artwork, plans, prints and posters — or living as studio furniture between outings. Slung on its strap it pairs oddly well with a clean, workwear-leaning wardrobe.',
    pairings: ['A chore coat and raw denim', 'A rollneck and wide trousers, studio-style', 'A bicycle, historically accurate', 'A portfolio for the flat pages'],
    essential: false,
    find: [
      { retailer: 'Etsy', url: 'https://www.etsy.com/search?q=leather+document+tube+architect' },
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=leather+map+document+tube+case' },
    ],
    keywords: ['document tube', 'map case', 'drawing tube'],
  },

  // =========================================================================
  // HATS / HEADWEAR
  // =========================================================================
  {
    id: 'baseball-cap',
    name: 'Baseball Cap',
    categoryId: 'hats',
    what: 'The six-panel cotton cap with a curved brim — in its menswear-adult form: unstructured, low-profile, plain or minimally marked, in washed cotton, wool or corduroy. The logo question decides everything about how it reads.',
    history: 'The Brooklyn Excelsiors wore the prototype in 1860; New Era’s 59Fifty (1954) fixed the modern shape. It escaped the ballpark by mid-century and became the world’s default headwear.',
    useCase: 'Casual outfits, sun and bad hair days — a washed navy or stone cap over knitwear and outerwear is now a classic move. Structured, flat-brimmed versions belong to streetwear; the soft cap to everything else.',
    pairings: ['A Harrington and jeans', 'An overcoat, for the high-low classic', 'A tee and fatigues', 'Sunglasses on the brim, off duty'],
    essential: true,
    find: [
      { retailer: 'Universal Works', url: 'https://www.universalworks.co.uk/search?q=cap' },
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=unstructured+cotton+baseball+cap' },
      { retailer: 'Mr Porter', url: 'https://www.mrporter.com/en-gb/mens/search?keywords=baseball+cap' },
    ],
    keywords: ['baseball cap', 'cap', 'dad cap', 'six panel'],
  },
  {
    id: 'beanie',
    name: 'Beanie',
    categoryId: 'hats',
    what: 'The knitted winter hat — the fisherman’s short watch cap (worn above the ears, folded) and the longer ribbed beanie being the two poles. Wool or wool-cashmere, plain, in colours that talk to the rest of the outfit.',
    history: 'The watch cap kept naval watchkeepers warm for centuries; docks, trawlers and armies wore versions of the same knit. Its fashion life runs from Steve Zissou to every menswear winter since.',
    useCase: 'Cold, daily — pulled to sit high (watch-cap style) with workwear and outerwear, or lower and slouchier with casual layers. Navy, charcoal, cream and moss serve every coat you own.',
    pairings: ['A peacoat and rollneck', 'A duffle coat and scarf', 'A chore coat and flannel shirt', 'A waxed jacket in the rain'],
    essential: true,
    find: [
      { retailer: "Colhay's", url: 'https://colhays.com/search?q=hat' },
      { retailer: 'Universal Works', url: 'https://www.universalworks.co.uk/search?q=beanie' },
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=wool+watch+cap+beanie' },
    ],
    keywords: ['beanie', 'watch cap', 'knitted hat', 'wool hat'],
  },
  {
    id: 'bucket-hat',
    name: 'Bucket Hat',
    categoryId: 'hats',
    what: 'The soft, downward-brimmed cotton hat that crushes into a pocket and shrugs off rain — fishing kit that became festival kit. In olive drab, tan or navy cotton twill it stays on the right side of the workwear/streetwear line.',
    history: 'Irish farmers and fishermen wore the tweed original from around 1900; armies issued jungle versions, and hip-hop (LL Cool J above all) turned the humble rain hat into a statement. The Irish walking hat remains its dressed cousin.',
    useCase: 'Rain, sun and casual outfits with a relaxed silhouette — it suits fuller trousers and workwear layers. It is the least formal hat here; wear it with anything tailored at your own risk.',
    pairings: ['A chore coat and wide jeans', 'A field jacket, fittingly', 'A tee and fatigues in summer', 'A rain shell at a festival'],
    essential: false,
    find: [
      { retailer: 'Universal Works', url: 'https://www.universalworks.co.uk/search?q=bucket+hat' },
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=cotton+bucket+hat+olive' },
      { retailer: 'Etsy', url: 'https://www.etsy.com/search?q=waxed+bucket+hat' },
    ],
    keywords: ['bucket hat', 'fishing hat', 'rain hat'],
  },
  {
    id: 'flat-cap',
    name: 'Flat Cap / Ivy Cap',
    categoryId: 'hats',
    what: 'The low, one-piece-crowned cap with a small stiff brim the crown snaps or sews onto — tweed, wool or cotton. The ivy (trimmer, rounder) and the flat cap proper are near-twins; both sit close and age beautifully.',
    history: 'A 1571 English law compelling wool caps on Sundays seeded it into the working classes; by 1900 it was the uniform of dockers and dukes alike (shooting estates loved it). Peaky Blinders re-armed it a century later.',
    useCase: 'Cold-weather casual and country-leaning smart — with waxed jackets, tweed, knitwear and overcoats. It is the easiest brimmed hat to start wearing: nobody asks a flat cap to explain itself.',
    pairings: ['A waxed jacket and Shetland', 'An overcoat and scarf', 'A tweed sport coat and cords', 'A duffle coat at the match'],
    essential: false,
    find: [
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=harris+tweed+flat+cap' },
      { retailer: 'Etsy', url: 'https://www.etsy.com/search?q=tweed+flat+cap' },
      { retailer: 'Mr Porter', url: 'https://www.mrporter.com/en-gb/mens/search?keywords=flat+cap' },
    ],
    keywords: ['flat cap', 'ivy cap', 'tweed cap', 'paperboy'],
  },
  {
    id: 'fedora',
    name: 'Fedora',
    categoryId: 'hats',
    what: 'The soft felt hat with a lengthwise crown crease, pinched front, and a brim (roughly 5–6.5cm) that can snap down at the front and up at the back. Fur felt — rabbit or beaver — is the material that separates the real thing from the costume.',
    history: 'Named for an 1882 play in which Sarah Bernhardt wore one; it became THE male hat of the 1920s–50s — Bogart’s silhouette — before hatlessness (blame cars, and perhaps JFK) ended the golden age.',
    useCase: 'With tailoring and overcoats, worn utterly matter-of-factly — the fedora fails only when treated as an event. Mid-grey, brown or navy felt, brim proportionate to shoulders, and down in front.',
    pairings: ['An overcoat and leather gloves', 'A flannel suit and covert coat', 'A trench in the rain, cinematically', 'A rollneck for the modern read'],
    essential: false,
    find: [
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=fur+felt+fedora+hat' },
      { retailer: 'Etsy', url: 'https://www.etsy.com/search?q=fur+felt+fedora' },
      { retailer: 'Mr Porter', url: 'https://www.mrporter.com/en-gb/mens/search?keywords=fedora' },
    ],
    keywords: ['fedora', 'felt hat', 'snap brim'],
  },
  {
    id: 'trilby',
    name: 'Trilby',
    categoryId: 'hats',
    what: 'The fedora’s narrow-brimmed, rakish sibling: a shorter brim (about 4cm) permanently turned up at the back and down at the front, with a more tapered crown. It perches where a fedora sits.',
    history: 'Named for the stage version of du Maurier’s Trilby (1895), it became the racing man’s hat — sharp, fast, slightly caddish where the fedora was solid. The 1960s loved it; the ska revival kept it.',
    useCase: 'Smart-casual with narrow lapels and trim coats — its proportions want slim tailoring. On the right head with the right suit it is dashing; oversized on the wrong one it is a party costume.',
    pairings: ['A covert coat and slim suit', 'A Harrington, mod-adjacent', 'A mac and knitted tie', 'Small-brimmed confidence generally'],
    essential: false,
    find: [
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=wool+felt+trilby+hat' },
      { retailer: 'Etsy', url: 'https://www.etsy.com/search?q=felt+trilby+men' },
      { retailer: 'Mr Porter', url: 'https://www.mrporter.com/en-gb/mens/search?keywords=trilby' },
    ],
    keywords: ['trilby', 'stingy brim', 'narrow brim hat'],
  },
  {
    id: 'panama-hat',
    name: 'Panama Hat',
    categoryId: 'hats',
    what: 'The summer straw hat woven from toquilla palm — genuinely Ecuadorian despite the name — in fedora or optimo (centre-ridge) shapes. Fineness of weave is the connoisseurship: the best roll through a wedding ring, allegedly.',
    history: 'Woven in Ecuador since the 1600s, exported via Panama — gold rushers and canal builders fixed the misnomer, and Roosevelt’s 1906 canal-visit photograph fixed the fame. Montecristi remains the Stradivarius of weaves.',
    useCase: 'Real summer, real sun: with linen tailoring, holiday shirts and anything cream or tobacco. It is the only hat that improves a hot formal occasion — races, weddings, regattas.',
    pairings: ['A linen suit at a summer wedding', 'A camp collar shirt on holiday', 'Cream trousers and espadrilles', 'A guayabera, correctly'],
    essential: false,
    find: [
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=genuine+panama+hat+ecuador' },
      { retailer: 'Etsy', url: 'https://www.etsy.com/search?q=montecristi+panama+hat' },
      { retailer: 'Mr Porter', url: 'https://www.mrporter.com/en-gb/mens/search?keywords=panama+hat' },
    ],
    keywords: ['panama', 'panama hat', 'straw hat', 'toquilla'],
  },
  {
    id: 'newsboy-cap',
    name: 'Newsboy Cap',
    categoryId: 'hats',
    what: 'The flat cap’s fuller cousin: an eight-panel crown gathered onto a button at the centre, overhanging a small brim. Rounder, softer and more vintage-reading than the ivy — the bakerboy of costume dramas.',
    history: 'The turn-of-the-century street uniform — newsboys, dockers, immigrants at Ellis Island — in every archive photograph. Its revivals track appetite for that era: Peaky Blinders made it a phenomenon twice over.',
    useCase: 'Cold-weather casual with texture: tweed and wool versions over chunky knits, overcoats and workwear. Its volume suits fuller faces and fuller trousers better than the flat cap does.',
    pairings: ['A duffle or Ulster coat', 'An Aran jumper and cords', 'A chore coat and boots', 'Braces-and-collarless-shirt costume, knowingly'],
    essential: false,
    find: [
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=eight+panel+newsboy+cap+tweed' },
      { retailer: 'Etsy', url: 'https://www.etsy.com/search?q=newsboy+cap+wool' },
      { retailer: 'Grailed', url: 'https://www.grailed.com/shop?query=newsboy+cap' },
    ],
    keywords: ['newsboy', 'bakerboy', 'eight panel cap', 'gatsby cap'],
  },
  {
    id: 'driving-cap',
    name: 'Driving Cap',
    categoryId: 'hats',
    what: 'The streamlined flat cap associated with early motoring — a close, swept-back crown in tweed, wool or leather, cut low so wind passes over. In practice a flat cap tuned for speed; the name survives the open cockpit that demanded it.',
    history: 'Edwardian motorists needed headwear that stayed on at thirty miles an hour — goggles up, cap down. The style stuck to the gentleman-driver image through Goodwood and every vintage rally since.',
    useCase: 'As a flat cap with a backstory: country and casual outfits, driving gloves optional but thematically correct. Leather versions lean sharply vintage; tweed stays timeless.',
    pairings: ['A waxed jacket and scarf', 'A shawl cardigan and cords', 'String-back driving gloves, for the bit', 'An open-top car, ideally borrowed'],
    essential: false,
    find: [
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=tweed+driving+cap' },
      { retailer: 'Etsy', url: 'https://www.etsy.com/search?q=driving+cap+wool' },
    ],
    keywords: ['driving cap', 'motoring cap', 'duckbill cap'],
  },
  {
    id: 'wool-felt-hat',
    name: 'Wool Felt Hat',
    categoryId: 'hats',
    what: 'The brimmed felt hat family beyond the fedora’s formality — wider-brimmed, open-crowned or teardrop shapes in matte wool felt, often with a simple leather or grosgrain band. More relaxed and more affordable than fur felt, with an outdoorsy cast.',
    history: 'Felt is the oldest cloth there is, and the wide wool felt hat runs from shepherds and homesteaders to the modern makers who softened the fedora into weekend wear.',
    useCase: 'Casual and rural outfits wanting a brim without vintage formality: open crowns and wider brims read contemporary where a pinched fedora reads period. Rain shrugs off it; sun stays out of it.',
    pairings: ['A wool overshirt and jeans', 'A gilet and flannel shirt', 'A blanket-lined barn jacket', 'Boots with actual mud on them'],
    essential: false,
    find: [
      { retailer: 'Etsy', url: 'https://www.etsy.com/search?q=wide+brim+wool+felt+hat+men' },
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=wool+felt+wide+brim+hat' },
    ],
    keywords: ['wool felt hat', 'wide brim hat', 'open crown hat'],
  },
  {
    id: 'beret',
    name: 'Beret',
    categoryId: 'hats',
    what: 'The soft, round, brimless wool cap, worn angled with the excess pushed to one side. The Basque original is a single piece of felted knit; the military versions added badges and slant conventions the civilian one happily ignores.',
    history: 'Pyrenean shepherds wore it for centuries before it became, simultaneously, French national shorthand, artists’ uniform (Picasso, Che, Monica Vitti) and elite military insignia — an unmatched costume range for one circle of wool.',
    useCase: 'Cold weather with an artistic or continental slant — over knitwear, chore coats and overcoats. Wear it deliberately askew and act as though nothing has happened; hesitation is fatal to a beret.',
    pairings: ['A Breton tee, at maximum Frenchness', 'A chore coat and straight jeans', 'An overcoat and rollneck', 'A cigarette you don’t smoke'],
    essential: false,
    find: [
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=basque+beret+wool+laulhere' },
      { retailer: 'Etsy', url: 'https://www.etsy.com/search?q=wool+beret+men' },
    ],
    keywords: ['beret', 'basque beret', 'french cap'],
  },
  {
    id: 'sun-hat',
    name: 'Wide-Brim Sun Hat',
    categoryId: 'hats',
    what: 'The practical summer brim beyond the panama: packable straw, raffia or cotton hats with brims wide enough to actually shade (7cm and up). Function first — but raffia and natural tones keep it inside the wardrobe’s language.',
    history: 'Sun hats are as old as fields — every agricultural culture built one from what grew nearby. The leisure version arrived with beach holidays; the packable raffia travel hat is its current best form.',
    useCase: 'Beaches, gardens and genuinely hot travel — anywhere the sun is a problem to solve rather than a mood to strike. It beats a cap wherever ears and neck are in play.',
    pairings: ['Swim shorts and a camp collar shirt', 'A linen shirt, worn open', 'Espadrilles and sunglasses', 'Sunscreen — the hat is not enough'],
    essential: false,
    find: [
      { retailer: 'Etsy', url: 'https://www.etsy.com/search?q=raffia+sun+hat+men' },
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=packable+straw+sun+hat+men' },
      { retailer: 'Mr Porter', url: 'https://www.mrporter.com/en-gb/mens/search?keywords=straw+hat' },
    ],
    keywords: ['sun hat', 'wide brim sun hat', 'raffia hat', 'summer hat'],
  },
  {
    id: 'boater',
    name: 'Boater',
    categoryId: 'hats',
    what: 'The stiff straw hat with a flat crown, flat brim and a striped grosgrain band — sennit straw pressed hard enough to knock on. The most architectural hat in menswear and the most tied to its occasions.',
    history: 'Victorian river culture built it: rowing, punting and seaside promenades. Straw-hat season had actual dates (New York’s ended in a riot in 1922), and Henley Royal Regatta and barbershop quartets keep the flame.',
    useCase: 'Regattas, garden parties and summer events with dress codes old enough to remember it — with a blazer and flannels it is correct, not costume. Elsewhere, it is a statement of considerable commitment.',
    pairings: ['A striped rowing blazer at Henley', 'Cream flannels and a club tie', 'A linen suit at a garden party', 'Nothing ironic — it can tell'],
    essential: false,
    find: [
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=straw+boater+hat' },
      { retailer: 'Etsy', url: 'https://www.etsy.com/search?q=straw+boater+hat+men' },
    ],
    keywords: ['boater', 'straw boater', 'skimmer hat'],
  },
];
