/**
 * WORLD OF MENSWEAR — entries, part 1 of 4: TOPS and BOTTOMS.
 * Editorial reference entries — the voice is a knowledgeable friend who has
 * read everything on the subject, not a Wikipedia stub. Every "find" link is
 * a real, item-specific URL — a filtered search or collection on a quality
 * retailer or brand site, never a homepage.
 */
import type { WorldEntry } from './world-types';

export const WORLD_ENTRIES_TOPS_BOTTOMS: WorldEntry[] = [
  // =========================================================================
  // TOPS
  // =========================================================================
  {
    id: 'oxford-shirt',
    name: 'Oxford Shirt',
    categoryId: 'tops',
    what: 'A shirt cut from Oxford cloth — a basketweave cotton with a subtle texture and a soft, matte lustre. Heavier and more forgiving than poplin, it wrinkles gracefully and gets better with every wash. The cloth, not the collar, is what makes it an Oxford.',
    history: 'Oxford cloth was one of four weaves — Oxford, Cambridge, Harvard and Yale — developed by Scottish mills in the late nineteenth century and named after universities to flatter their customers. Only Oxford survived. It crossed to America with the polo and prep set and never left.',
    useCase: 'The most versatile shirt a man can own: smart enough under a blazer, relaxed enough with jeans. Wear it washed and slightly rumpled — an over-pressed Oxford misses the point.',
    pairings: ['Grey flannel trousers and penny loafers', 'Selvedge jeans and a Shetland crew neck', 'A navy blazer with mid-grey trousers', 'Chinos and white leather sneakers'],
    essential: true,
    find: [
      { retailer: "Drake's", url: 'https://drakes.com/search?q=oxford+shirt' },
      { retailer: 'Gitman Vintage', url: 'https://gitmanvintage.com/search?q=oxford' },
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=oxford+cloth+shirt' },
    ],
    keywords: ['oxford shirt', 'oxford cloth', 'basketweave shirt'],
  },
  {
    id: 'ocbd',
    name: 'OCBD (Oxford-Cloth Button-Down)',
    categoryId: 'tops',
    what: 'The Oxford shirt with its collar points buttoned to the body — the defining garment of American Ivy style. The best examples have a generous, unlined collar that rolls in a soft arc rather than lying flat. It is deliberately informal: a dress shirt that refuses to be one.',
    history: 'John E. Brooks of Brooks Brothers noticed English polo players buttoning their collars down to stop them flapping mid-chukka, and put the detail on a shirt in 1896. The American college campuses of the 1950s — and later Miles Davis and JFK — made it a uniform.',
    useCase: 'Anywhere between a T-shirt and a suit. It reads best worn slightly soft: open-collared at the weekend, or under a sport coat with the tie optional. Avoid pressing the collar flat — the roll is the whole charm.',
    pairings: ['A Shetland or lambswool crew neck', 'Chinos and boat shoes or loafers', 'A tweed sport coat and knit tie', 'Raw denim and a Harrington'],
    essential: true,
    find: [
      { retailer: 'Gitman Vintage', url: 'https://gitmanvintage.com/search?q=button+down+oxford' },
      { retailer: "Drake's", url: 'https://drakes.com/search?q=button-down+oxford' },
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=OCBD+oxford+button+down+shirt' },
    ],
    keywords: ['ocbd', 'button-down', 'button down shirt', 'button-down oxford', 'ivy shirt'],
  },
  {
    id: 'polo-shirt',
    name: 'Polo Shirt',
    categoryId: 'tops',
    what: 'A short-sleeved knitted shirt with a soft ribbed collar and a two- or three-button placket, classically in piqué cotton — the waffle-textured knit that breathes and holds its shape. Sits exactly halfway between a T-shirt and a shirt.',
    history: 'René Lacoste, the French tennis champion, designed it in the 1920s because stiff whites were unplayable in; he embroidered a crocodile on his chest and changed sportswear forever. Fred Perry gave it its British mod inflection; Ralph Lauren renamed the whole category after another sport entirely.',
    useCase: 'Warm weather smart-casual — the collar keeps you presentable when a tee would read careless. Tucked into tailored shorts or worn loose over chinos; under a linen blazer it will carry you through a summer wedding weekend.',
    pairings: ['Tailored shorts and espadrilles', 'Cream linen trousers and loafers', 'An unstructured cotton blazer', 'Chinos and low-profile sneakers'],
    essential: true,
    find: [
      { retailer: 'Sunspel', url: 'https://www.sunspel.com/search?q=polo+shirt' },
      { retailer: 'John Smedley', url: 'https://www.johnsmedley.com/search?q=polo' },
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=pique+polo+shirt' },
    ],
    keywords: ['polo shirt', 'polo', 'pique', 'tennis shirt'],
  },
  {
    id: 'turtleneck',
    name: 'Turtleneck',
    categoryId: 'tops',
    what: 'A close-fitting top with a high, folded-over collar that covers the neck entirely. In fine-gauge merino or cotton it is a shirt substitute; in heavier wool it becomes knitwear (see Roll Neck Jumper). The clean vertical line it draws is the most flattering neckline in menswear.',
    history: 'Worn by medieval knights under chainmail and nineteenth-century sailors and dockers for warmth, it was adopted in the twentieth century by everyone who wanted to signal thinking over conforming: Noel Coward, the Beats, Foucault, Steve McQueen in Bullitt.',
    useCase: 'Cold-weather smartness without a tie — under a blazer, an overcoat or a suit it is the most elegant winter alternative to a shirt. A fine black or navy turtleneck under grey tailoring is close to unimprovable.',
    pairings: ['A grey flannel suit in place of a shirt', 'An overcoat and dress trousers', 'Tweed sport coat and cords', 'Dark jeans and Chelsea boots'],
    essential: true,
    find: [
      { retailer: 'John Smedley', url: 'https://www.johnsmedley.com/search?q=roll+neck' },
      { retailer: "Colhay's", url: 'https://colhays.com/search?q=roll+neck' },
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=merino+turtleneck+men' },
    ],
    keywords: ['turtleneck', 'turtle neck', 'polo neck'],
  },
  {
    id: 'rollneck',
    name: 'Rollneck',
    categoryId: 'tops',
    what: 'The British term for the turtleneck, but in menswear usage it usually implies the finer, dressier end of the family: a light merino, cashmere or sea island cotton with a neatly doubled collar, worn as a shirt-layer rather than as outer knitwear.',
    history: 'The word comes straight from the doubled “roll” of the collar. British tailors and outfitters kept the term alive through the twentieth century, and the fine-gauge rollneck under tailoring became a signature of 1960s European style — think Marcello Mastroianni.',
    useCase: 'Precisely where a shirt feels stiff and a jumper feels casual: under suits, blazers and overcoats from October to March. Fine gauge is the key — it should sit close to the body with no bulk at the waist.',
    pairings: ['A double-breasted overcoat', 'Charcoal suit trousers and derbies', 'A herringbone tweed jacket', 'Grey flannels and monk straps'],
    essential: false,
    find: [
      { retailer: 'John Smedley', url: 'https://www.johnsmedley.com/search?q=roll+neck' },
      { retailer: 'Luca Faloni', url: 'https://lucafaloni.com/search?q=roll+neck' },
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=fine+gauge+rollneck' },
    ],
    keywords: ['rollneck', 'roll neck', 'roll-neck', 'fine gauge roll neck'],
  },
  {
    id: 'breton-tee',
    name: 'Breton Stripe Tee',
    categoryId: 'tops',
    what: 'A boat-necked cotton top in horizontal navy-on-white stripes, traditionally in a dense, heavyweight jersey that holds its shape. The neck is wide, the sleeves classically three-quarter or long, and the stripes famously numbered.',
    history: 'A French naval uniform piece from 1858 — the original spec called for 21 stripes, one for each of Napoleon’s victories, and the pattern made a man overboard easier to spot. Coco Chanel lifted it into fashion in 1917; Picasso and Jean Seberg made it bohemian shorthand.',
    useCase: 'The weekend top that looks considered without trying: under a chore coat or peacoat, with denim, in place of a plain tee whenever an outfit needs one point of pattern.',
    pairings: ['Ecru or indigo jeans and espadrilles', 'A navy chore coat', 'White chinos and boat shoes', 'A camel overcoat in winter'],
    essential: false,
    find: [
      { retailer: 'Armor-Lux at eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=armor+lux+breton+stripe' },
      { retailer: 'Universal Works', url: 'https://www.universalworks.co.uk/search?q=stripe+tee' },
      { retailer: 'Etsy', url: 'https://www.etsy.com/search?q=breton+stripe+shirt+men' },
    ],
    keywords: ['breton', 'stripe tee', 'striped tee', 'mariniere', 'sailor stripe'],
  },
  {
    id: 't-shirt',
    name: 'T-Shirt',
    categoryId: 'tops',
    what: 'The simplest garment in the wardrobe and the hardest to get right: a knitted cotton crew or V-neck with set-in sleeves. Weight and collar are everything — a substantial jersey (180gsm and up) with a neat, firm neckband separates a proper tee from underwear.',
    history: 'Issued by the US Navy as an undershirt around 1913, it became outerwear when returning GIs kept wearing theirs — then became iconography when Brando wore one in A Streetcar Named Desire (1951) and Dean followed in Rebel Without a Cause.',
    useCase: 'The base note of casual dressing: alone in summer, under everything else the rest of the year. Plain white, grey and navy in a heavyweight loopwheeled or tubular knit will outdress any printed tee.',
    pairings: ['Raw denim and white sneakers', 'Under an overshirt or chore coat', 'Fatigue trousers and desert boots', 'Under a knit cardigan'],
    essential: true,
    find: [
      { retailer: 'Merz b. Schwanen', url: 'https://www.merz-schwanen.com/search?q=t-shirt' },
      { retailer: 'Lady White Co.', url: 'https://www.ladywhiteco.com/search?q=t-shirt' },
      { retailer: 'Sunspel', url: 'https://www.sunspel.com/search?q=t-shirt' },
    ],
    keywords: ['t-shirt', 'tee', 'tshirt', 'crew neck tee'],
  },
  {
    id: 'henley',
    name: 'Henley',
    categoryId: 'tops',
    what: 'A collarless knitted top with a buttoned placket running two to five buttons down from the neck — essentially a T-shirt with a serious past. Long- or short-sleeved, at its best in a textured heavyweight cotton or waffle knit.',
    history: 'Named for Henley-on-Thames, where it was the rowing kit of the town’s crews in the nineteenth century — a collarless shirt that would not chafe mid-stroke. It survived as workwear and underwear before returning as a casual staple.',
    useCase: 'The step up from a tee when you want texture and a little undone-ness — the open placket does quiet work. Excellent layered under flannel shirts, chore coats and cardigans in the colder months.',
    pairings: ['A chore coat and jeans', 'Under an open flannel shirt', 'Moleskin trousers and boots', 'A shawl-collar cardigan'],
    essential: false,
    find: [
      { retailer: 'Merz b. Schwanen', url: 'https://www.merz-schwanen.com/search?q=henley' },
      { retailer: 'Sunspel', url: 'https://www.sunspel.com/search?q=henley' },
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=heavyweight+henley+men' },
    ],
    keywords: ['henley', 'grandad tee', 'placket tee'],
  },
  {
    id: 'camp-collar-shirt',
    name: 'Camp Collar Shirt',
    categoryId: 'tops',
    what: 'A boxy, short-sleeved shirt with a flat, open “camp” (or Cuban) collar that lies against the chest with no top button to close — the collar and lapel are one continuous piece. Usually straight-hemmed to be worn untucked.',
    history: 'A warm-weather working shirt with roots in Latin America and the Philippines, it hit Hollywood in the 1950s — resort wear for the Palm Springs set — then cycled back through every revival of mid-century style since.',
    useCase: 'High summer and holidays: worn open-necked and untucked, it is the dressed-down shirt that still has a shape. Solid colours and quiet textures (linen, seersucker, TENCEL) read far more expensive than loud prints.',
    pairings: ['Pleated linen trousers and loafers', 'Tailored swim shorts and espadrilles', 'White jeans in the evening', 'Under an unstructured cotton suit'],
    essential: false,
    find: [
      { retailer: 'Universal Works', url: 'https://www.universalworks.co.uk/search?q=camp+collar' },
      { retailer: "Drake's", url: 'https://drakes.com/search?q=camp+collar' },
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=camp+collar+shirt+linen' },
    ],
    keywords: ['camp collar', 'cuban collar', 'revere collar', 'vacation shirt', 'resort shirt'],
  },
  {
    id: 'guayabera',
    name: 'Guayabera',
    categoryId: 'tops',
    what: 'The Latin American dress shirt: four patch pockets, two vertical rows of fine pleats (alforzas) front and back, side vents, and a straight hem always worn untucked. Traditionally linen or fine cotton, ideally white or pastel.',
    history: 'Its origin is contested between Cuba and Mexico’s Yucatán — both claim it as farm wear turned formal wear from the eighteenth–nineteenth centuries. In much of the Caribbean and Central America it is literally official: acceptable dress for weddings and government business.',
    useCase: 'Serious summer events where a jacket is unreasonable — it IS the formality. Wear it crisp with tailored trousers; it is a garment of occasion, not a beach shirt.',
    pairings: ['Cream linen trousers and woven loafers', 'A panama hat', 'Tailored stone chinos', 'Suede huaraches or espadrilles'],
    essential: false,
    find: [
      { retailer: 'Etsy', url: 'https://www.etsy.com/search?q=linen+guayabera+men' },
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=guayabera+shirt+linen' },
    ],
    keywords: ['guayabera', 'mexican wedding shirt', 'havana shirt'],
  },
  {
    id: 'chambray-shirt',
    name: 'Chambray Shirt',
    categoryId: 'tops',
    what: 'A shirt in chambray — a plain-weave cotton with an indigo warp and white weft that reads like denim’s lighter, softer cousin. It fades and softens with wear the same way, without denim’s weight or stiffness.',
    history: 'Named for Cambrai in France, where the cloth was woven from the sixteenth century. The US Navy made the blue chambray work shirt standard issue from 1901, which is why the whole family still carries an honest, worked-in association.',
    useCase: 'The workhorse casual shirt: everything an Oxford does, one notch more rugged. Superb with knitwear over it, under waxed jackets, or open over a white tee in summer.',
    pairings: ['Ecru jeans (avoid matching indigos too closely)', 'A cream Aran or Shetland jumper', 'Olive fatigues and white sneakers', 'A tweed or corduroy sport coat'],
    essential: true,
    find: [
      { retailer: 'Gitman Vintage', url: 'https://gitmanvintage.com/search?q=chambray' },
      { retailer: 'Universal Works', url: 'https://www.universalworks.co.uk/search?q=chambray' },
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=chambray+work+shirt' },
    ],
    keywords: ['chambray', 'work shirt', 'denim shirt'],
  },
  {
    id: 'flannel-shirt',
    name: 'Flannel Shirt',
    categoryId: 'tops',
    what: 'A shirt in brushed cotton or wool flannel — the napped surface traps air, which is why it feels warmer than its weight suggests. Solid flannels read refined; plaids read rugged; both should drape softly rather than hang stiff.',
    history: 'Flannel cloth is Welsh, from the seventeenth century, brushed to make hill-farm winters survivable. The plaid flannel shirt became the uniform of North American loggers and railroad men — then of grunge, which is why cut and colour decide whether yours reads woodsman or Seattle 1992.',
    useCase: 'Cold-weather casual: worn buttoned as a shirt, open as a light jacket over a tee, or under a chore coat when the temperature drops. A solid grey or camel flannel shirt is a quietly luxurious alternative to the plaid default.',
    pairings: ['Raw denim and leather boots', 'A quilted gilet over the top', 'Moleskin or corduroy trousers', 'A beanie and waxed jacket'],
    essential: true,
    find: [
      { retailer: 'Gitman Vintage', url: 'https://gitmanvintage.com/search?q=flannel' },
      { retailer: 'Filson', url: 'https://www.filson.com/search?q=flannel+shirt' },
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=brushed+flannel+shirt+men' },
    ],
    keywords: ['flannel shirt', 'brushed cotton shirt', 'plaid shirt'],
  },
  {
    id: 'dress-shirt',
    name: 'Dress Shirt',
    categoryId: 'tops',
    what: 'The formal shirt: fine poplin or twill cotton, a structured collar (spread, semi-spread or cutaway) built to frame a tie, single or double (French) cuffs, and a tail long enough to stay tucked. Crispness is the entire point — this is the one shirt that should be pressed.',
    history: 'The white dress shirt descends from the linen shirts that were, for centuries, literally underwear — showing clean white at collar and cuff proved you could afford laundering. The detachable collar era (1827–1930s) formalised the collar shapes we still use.',
    useCase: 'Suits, interviews, weddings, funerals and every occasion with a dress code. White and pale blue first; double cuffs only when the event justifies cufflinks. It is not a casual shirt — untucked poplin pleases no one.',
    pairings: ['A charcoal or navy suit and silk tie', 'Grey flannels and a blazer', 'A V-neck or fine crew neck under tailoring', 'Black tie (in its marcella-front evening form)'],
    essential: true,
    find: [
      { retailer: "Drake's", url: 'https://drakes.com/search?q=poplin+shirt' },
      { retailer: 'Luca Faloni', url: 'https://lucafaloni.com/search?q=shirt' },
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=spread+collar+poplin+dress+shirt' },
    ],
    keywords: ['dress shirt', 'poplin shirt', 'formal shirt', 'spread collar', 'french cuff'],
  },
  {
    id: 'grandad-collar-shirt',
    name: 'Grandad Collar Shirt',
    categoryId: 'tops',
    what: 'A shirt with only a low, round band where the collar would be — also called a band collar. Removing the collar removes most of a shirt’s formality signals, leaving something clean, slightly artistic and impossible to wear a tie with.',
    history: 'A relic of the detachable-collar era: working men wore the collarless base shirt all week and buttoned a starched collar on for church. When collars became fixed, the collarless original re-emerged — first as workwear nostalgia, then as a minimalist staple.',
    useCase: 'When you want a shirt’s structure without its office associations — under knitwear (no collar to wrangle), with unstructured tailoring, or on its own in linen for summer. Especially good on men who find collars boxy on them.',
    pairings: ['An unstructured blazer, no tie', 'A crew-neck jumper over the top', 'Pleated trousers and loafers', 'A chore coat and straight jeans'],
    essential: false,
    find: [
      { retailer: 'Universal Works', url: 'https://www.universalworks.co.uk/search?q=grandad+collar' },
      { retailer: "Drake's", url: 'https://drakes.com/search?q=band+collar' },
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=grandad+collar+shirt' },
    ],
    keywords: ['grandad collar', 'band collar', 'collarless shirt', 'mandarin collar shirt'],
  },
  {
    id: 'overshirt',
    name: 'Overshirt / CPO Shirt',
    categoryId: 'tops',
    what: 'A shirt built to be worn as a light jacket: heavier cloth (wool, moleskin, heavy cotton), a roomier cut to layer over a tee or shirt, and usually patch chest pockets. The CPO is the naval original — wool, flap pockets, anchor-stamped buttons.',
    history: 'CPO stands for Chief Petty Officer — the US Navy issued the heavy wool shirt to that rank from the 1930s. Civilian workwear had parallel versions for decades; the menswear world folded them all into the “overshirt” category in the 2010s.',
    useCase: 'The third layer for in-between weather — over a tee in autumn, over a flannel in early winter, instead of a jacket indoors-to-outdoors. It solves the “too warm for a coat, too cold for a shirt” problem better than anything else.',
    pairings: ['A white heavyweight tee and jeans', 'A rollneck underneath in winter', 'Fatigue trousers and boots', 'Layered under a raincoat'],
    essential: true,
    find: [
      { retailer: 'Universal Works', url: 'https://www.universalworks.co.uk/search?q=overshirt' },
      { retailer: 'Private White V.C.', url: 'https://www.privatewhitevc.com/search?q=overshirt' },
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=wool+CPO+shirt' },
    ],
    keywords: ['overshirt', 'cpo', 'shirt jacket', 'shacket'],
  },
  {
    id: 'western-shirt',
    name: 'Western Shirt',
    categoryId: 'tops',
    what: 'A denim or twill shirt defined by its details: pointed front and back yokes, pearl snap fasteners instead of buttons, and slim chest pockets, often with sawtooth flaps. Cut closer than a work shirt, with a longer tail for staying tucked in the saddle.',
    history: 'Developed for working cowboys in the American West — snaps tear open safely if the shirt catches on a horn or fence — and codified by makers like Rockmount and Levi’s in the 1930s–50s. Country stars and rockabilly gave it its flash; the plain versions stayed pure workwear.',
    useCase: 'A characterful alternative to the chambray or flannel shirt — same register, more attitude. Keep the rest of the outfit quiet and let the yokes and snaps do the talking.',
    pairings: ['Raw or washed denim (embrace the double)', 'Suede chukka or roper boots', 'A leather or suede jacket', 'Cords and a shawl cardigan'],
    essential: false,
    find: [
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=pearl+snap+western+shirt' },
      { retailer: 'Grailed', url: 'https://www.grailed.com/shop?query=western+shirt' },
      { retailer: 'Etsy', url: 'https://www.etsy.com/search?q=vintage+western+shirt+men' },
    ],
    keywords: ['western shirt', 'pearl snap', 'cowboy shirt', 'sawtooth'],
  },
  {
    id: 'linen-shirt',
    name: 'Linen Shirt',
    categoryId: 'tops',
    what: 'A shirt in woven flax — the coolest-wearing cloth there is, with a dry handle and a rumple that is a feature, not a flaw. Good linen is substantial, not gauzy; it should crease in long, soft folds rather than sharp wrinkles.',
    history: 'Linen is the oldest shirt cloth in the world — Egyptian, biblical, medieval: all linen. It was THE shirting fibre until cotton undercut it in the nineteenth century, surviving since as the warm-weather aristocrat of the shirt drawer.',
    useCase: 'Summer, full stop — the hotter and stickier the day, the better it performs. Wear it a touch loose, sleeves rolled, and never iron it into submission; pressed-flat linen loses its charm.',
    pairings: ['Cream or tobacco linen trousers', 'Tailored shorts and espadrilles', 'White jeans and loafers', 'An unlined cotton blazer'],
    essential: true,
    find: [
      { retailer: 'Luca Faloni', url: 'https://lucafaloni.com/search?q=linen+shirt' },
      { retailer: "Drake's", url: 'https://drakes.com/search?q=linen+shirt' },
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=irish+linen+shirt+men' },
    ],
    keywords: ['linen shirt', 'flax shirt', 'summer shirt'],
  },

  // =========================================================================
  // BOTTOMS
  // =========================================================================
  {
    id: 'chinos',
    name: 'Chinos',
    categoryId: 'bottoms',
    what: 'Trousers in chino cloth — a firm cotton twill — with a flat or pleated front and a clean, uncluttered leg. The civilised middle ground of the trouser world: sharper than jeans, easier than wool. Stone, olive, navy and tobacco are the canonical colours.',
    history: 'British and then American troops in the colonies dyed their cotton drill “khaki” (Urdu for dust) from the 1840s; the cloth bought through China for US forces in the Philippines picked up the Spanish name “chino”. Demobbed GIs wore theirs to college and the campus took it from there.',
    useCase: 'The default smart-casual trouser — everything from the office (with a blazer) to the weekend (with a tee). A higher rise and a single pleat move them toward tailoring; a straight low rise toward workwear.',
    pairings: ['An OCBD and penny loafers', 'A navy blazer for the 90% of offices without suits', 'A white tee and sneakers', 'A crew neck and desert boots'],
    essential: true,
    find: [
      { retailer: 'Casatlantic', url: 'https://casatlantic.com/search?q=chino' },
      { retailer: "Drake's", url: 'https://drakes.com/search?q=chinos' },
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=cotton+twill+chinos' },
    ],
    keywords: ['chinos', 'chino', 'khakis'],
  },
  {
    id: 'dress-trousers',
    name: 'Dress Trousers',
    categoryId: 'bottoms',
    what: 'Tailored wool trousers worn separately from a suit — a proper waistband (often with side adjusters), a pressed crease, and a clean drape from a mid-to-high rise. Mid-grey is the great neutral; the crease is what separates them from every cotton trouser.',
    history: 'The odd trouser (“odd” as in not matching the jacket) emerged with the sports coat in the late nineteenth century, as men began breaking the suit apart for country and leisure wear. Grey flannels with a navy jacket became THE combination of the twentieth century.',
    useCase: 'Any time a jacket goes on and a full suit would be too much — which is most dressed-up occasions now. They also lift plain knitwear instantly: a jumper over dress trousers reads deliberate where the same jumper over jeans reads default.',
    pairings: ['A navy blazer or tweed sport coat', 'A fine rollneck and overcoat', 'An OCBD and loafers', 'A shawl cardigan in place of a jacket'],
    essential: true,
    find: [
      { retailer: 'Berg & Berg', url: 'https://bergbergstore.com/search?q=trousers' },
      { retailer: "Drake's", url: 'https://drakes.com/search?q=trousers' },
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=wool+dress+trousers+side+adjusters' },
    ],
    keywords: ['dress trousers', 'wool trousers', 'tailored trousers', 'slacks', 'odd trousers'],
  },
  {
    id: 'jeans',
    name: 'Jeans (Straight, Slim, Wide-Leg)',
    categoryId: 'bottoms',
    what: 'Five-pocket trousers in denim — riveted, contrast-stitched, and cut straight, slim or wide. Raw (unwashed) selvedge denim starts stiff and dark and moulds to its wearer; washed denim starts where raw denim ends up. The straight cut is the timeless one.',
    history: 'Levi Strauss and Jacob Davis patented the riveted work trouser in 1873 for Californian miners. A century of cowboys, GIs, bikers, rebels and rock stars turned workwear into the most worn garment on earth — the 501 is effectively the type specimen.',
    useCase: 'Everywhere tailoring isn’t: the true casual foundation. One dark, unfaded pair in a straight leg does the most work — dark denim with a blazer and loafers remains the easiest good outfit in menswear.',
    pairings: ['An OCBD or chambray shirt', 'White leather sneakers or Chelsea boots', 'A Shetland crew and field jacket', 'A blazer and loafers (keep the denim dark)'],
    essential: true,
    find: [
      { retailer: 'Blackhorse Lane Ateliers', url: 'https://blackhorselane.com/search?q=jeans' },
      { retailer: "Drake's", url: 'https://drakes.com/search?q=jeans' },
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=selvedge+denim+jeans' },
    ],
    keywords: ['jeans', 'denim', 'selvedge', 'five pocket'],
  },
  {
    id: 'corduroy-trousers',
    name: 'Cords / Corduroy Trousers',
    categoryId: 'bottoms',
    what: 'Trousers in corduroy — a cotton pile cloth woven into vertical ribs (“wales”). Wide wales read country and vintage; needlecord reads neat and urbane. The nap catches the light, giving cords more depth than any flat cotton.',
    history: 'Descended from fustian, the hard-wearing cotton of European labourers since the Middle Ages; the name is likelier from “cord” weave than the romantic “corde du roi” myth. By the twentieth century it was the cloth of gamekeepers, geography dons and the Bloomsbury set alike.',
    useCase: 'Autumn and winter casual tailoring — where chinos feel too summery and flannels too dressy. Tobacco, moss and rust cords with knitwear is one of the great cold-weather formulas.',
    pairings: ['A Shetland or Fair Isle jumper', 'A tweed jacket and brogues', 'A denim or chambray shirt', 'Suede chukka boots'],
    essential: false,
    find: [
      { retailer: "Drake's", url: 'https://drakes.com/search?q=corduroy+trousers' },
      { retailer: 'Universal Works', url: 'https://www.universalworks.co.uk/search?q=cord+trousers' },
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=corduroy+trousers+men' },
    ],
    keywords: ['corduroy', 'cords', 'needlecord', 'cord trousers'],
  },
  {
    id: 'flannel-trousers',
    name: 'Flannel Trousers',
    categoryId: 'bottoms',
    what: 'Tailored trousers in woollen flannel — the soft, matte, slightly fuzzy cloth that drapes like nothing else. Mid-grey flannels are arguably the single most useful tailored garment a man can own; the milled surface dresses down beautifully.',
    history: 'Flannel trousers were the sporting trouser of Edwardian England — cricket, tennis, boating — before settling into the twentieth-century wardrobe as the universal partner to the odd jacket. The Duke of Windsor practically lived in them.',
    useCase: 'Cold-month tailoring, from the office to dinner. They carry knitwear, tweed and blazers equally well, and unlike worsted suit trousers they never look like half a suit.',
    pairings: ['A navy blazer and OCBD', 'A grey rollneck and overcoat', 'A tweed sport coat and knit tie', 'A shawl-collar cardigan'],
    essential: false,
    find: [
      { retailer: 'Berg & Berg', url: 'https://bergbergstore.com/search?q=flannel+trousers' },
      { retailer: "Drake's", url: 'https://drakes.com/search?q=flannel+trousers' },
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=grey+flannel+trousers' },
    ],
    keywords: ['flannel trousers', 'grey flannels', 'wool flannel trouser'],
  },
  {
    id: 'pleated-trousers',
    name: 'Pleated Trousers',
    categoryId: 'bottoms',
    what: 'Trousers with one or two folds of cloth stitched into the waistband, opening toward the pocket (forward pleats) or the fly (reverse pleats). Pleats add room through the hip and thigh and give a higher-rise trouser its classic columnar drape.',
    history: 'Pleats arrived in the 1920s as trousers rose to the natural waist and fuller cuts needed managing; the drape suits of the 1930s–40s made them standard. Banished by the flat-front 2000s, they returned as tailoring rediscovered ease and swing.',
    useCase: 'For higher-rise, fuller-cut tailoring — worn AT the waist, where the pleats can hang closed and straight. On linen and flannel especially, a single pleat improves both comfort and line.',
    pairings: ['A tucked knitted polo', 'Loafers with a slightly cropped hem', 'A camp collar shirt in linen', 'Braces under a double-breasted jacket'],
    essential: false,
    find: [
      { retailer: 'Casatlantic', url: 'https://casatlantic.com/search?q=pleated' },
      { retailer: 'Berg & Berg', url: 'https://bergbergstore.com/search?q=pleated+trousers' },
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=pleated+high+rise+trousers+men' },
    ],
    keywords: ['pleated trousers', 'single pleat', 'double pleat', 'high rise trousers'],
  },
  {
    id: 'shorts',
    name: 'Shorts (Chino, Bermuda, Swim)',
    categoryId: 'bottoms',
    what: 'The warm-weather trouser family: chino shorts (casual cotton twill, mid-thigh to just above the knee), Bermuda shorts (longer, tailored, hemmed just above the knee), and swim shorts (quick-drying, ideally tailored enough to pass at the beach bar).',
    history: 'Shorts entered adult menswear through the military in hot colonies and through Bermuda specifically — where businessmen paired tailored shorts with blazers and knee socks, and still do. The swim short evolved from 1930s boxer trunks.',
    useCase: 'Heat, leisure and nowhere with a dress code. The inseam question answers itself: tailored and just-above-the-knee for towns and lunches, shorter and sportier for actual sport and sand.',
    pairings: ['A polo and espadrilles', 'A camp collar shirt on holiday', 'A linen shirt, worn open, at the beach', 'White sneakers and a heavyweight tee'],
    essential: true,
    find: [
      { retailer: 'Casatlantic', url: 'https://casatlantic.com/search?q=shorts' },
      { retailer: 'Universal Works', url: 'https://www.universalworks.co.uk/search?q=shorts' },
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=tailored+chino+shorts+men' },
    ],
    keywords: ['shorts', 'chino shorts', 'bermuda shorts', 'swim shorts', 'swim trunks'],
  },
  {
    id: 'cargo-trousers',
    name: 'Cargo Trousers',
    categoryId: 'bottoms',
    what: 'Military field trousers with large bellows pockets on the thighs — the originals in olive cotton sateen or ripstop, cut straight and roomy. The fatigue trouser (patch front pockets, no thigh cargo) is the quieter sibling worth knowing.',
    history: 'The British Battledress of 1938 carried the first thigh pocket; the US M-42 paratrooper and later M-65 field trousers perfected the type for equipment a soldier needed reachable in a crouch. Streetwear adopted them in the 1990s and never gave them back.',
    useCase: 'Rugged casual — they want honest partners: knits, tees, boots, canvas. Keep the fit straight and the colour military (olive, khaki, black); ignore anything with zips off-schedule.',
    pairings: ['A white or ecru heavyweight tee', 'A chore coat or field jacket', 'Military-style sneakers or boots', 'A watch cap in winter'],
    essential: false,
    find: [
      { retailer: 'Stan Ray', url: 'https://www.stanrayusa.com/search?q=cargo' },
      { retailer: 'Universal Works', url: 'https://www.universalworks.co.uk/search?q=cargo+pant' },
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=military+cargo+trousers+og107' },
    ],
    keywords: ['cargo trousers', 'cargo pants', 'fatigues', 'fatigue trousers', 'military trousers'],
  },
  {
    id: 'joggers',
    name: 'Joggers / Sweatpants (Classic Cut)',
    categoryId: 'bottoms',
    what: 'Knitted cotton fleece trousers with an elasticated or drawstring waist — in their classic form straight-legged, mid-weight loopback cotton, in grey marl, navy or black. The classic cut is loungewear with self-respect; the skinny “tech” jogger is another thing entirely.',
    history: 'Émile Camuset of Le Coq Sportif made the first jersey training trousers in the 1920s; American athletic departments and Champion’s reverse-weave fleece codified the grey sweat. For decades they were strictly gym-and-sofa — quality makers rehabilitated them.',
    useCase: 'Travel, home, coffee runs and genuinely off-duty days. The rule: everything else sharpens — clean sneakers, a good knit or overshirt — so the outfit reads chosen rather than surrendered.',
    pairings: ['A heavyweight sweatshirt of matching quality', 'Clean white or grey sneakers', 'An overshirt or harrington over the top', 'A rollneck for elevated lounging'],
    essential: false,
    find: [
      { retailer: 'Sunspel', url: 'https://www.sunspel.com/search?q=track+pant' },
      { retailer: 'Merz b. Schwanen', url: 'https://www.merz-schwanen.com/search?q=sweatpants' },
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=loopback+cotton+sweatpants' },
    ],
    keywords: ['joggers', 'sweatpants', 'track pants', 'sweats'],
  },
  {
    id: 'moleskin-trousers',
    name: 'Moleskin Trousers',
    categoryId: 'bottoms',
    what: 'Trousers in moleskin — a densely woven, heavily brushed cotton with a suede-like nap and a soft, almost windproof body. No moles involved: the name is for the feel. It wears warmer than its weight and ages into a beautiful broken-in softness.',
    history: 'A British and French workwear cloth of the eighteenth–nineteenth centuries — miners, farmers and foundrymen wore moleskin because it was cheap, warm and nearly indestructible. It migrated upward into country clothing, where it remains a quiet staple.',
    useCase: 'The cold-weather alternative to chinos — same versatility, more warmth and texture. Traditional country colours (moss, tobacco, stone, burgundy) with knitwear and boots are exactly right.',
    pairings: ['A Shetland jumper and chukka boots', 'A tattersall or flannel shirt', 'A waxed jacket', 'A tweed sport coat at the smart end'],
    essential: false,
    find: [
      { retailer: "Drake's", url: 'https://drakes.com/search?q=moleskin' },
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=moleskin+trousers+men' },
      { retailer: 'Etsy', url: 'https://www.etsy.com/search?q=moleskin+trousers' },
    ],
    keywords: ['moleskin', 'moleskin trousers', 'brushed cotton trousers'],
  },
  {
    id: 'linen-trousers',
    name: 'Linen Trousers',
    categoryId: 'bottoms',
    what: 'Trousers in woven flax — breezy, dry-handed and quick to shed heat, at their best in a fuller, often pleated cut that lets air move. Good linen trousers crease at the knee and lap like a linen shirt does: softly, and with charm.',
    history: 'Linen was the hot-climate trouser of the colonial and Mediterranean worlds long before air conditioning — planters, painters and Riviera idlers all wore it. The full-cut, high-rise linen trouser remains a fixture of Italian summer tailoring.',
    useCase: 'Serious heat, worn with the same ease the cloth has — sandals or loafers, no socks, nothing stiff above the waist. Cream, tobacco and olive do more than pale blue ever will.',
    pairings: ['A linen or camp collar shirt', 'A knitted polo, tucked', 'Espadrilles or woven loafers', 'A cotton blazer for summer events'],
    essential: false,
    find: [
      { retailer: 'Luca Faloni', url: 'https://lucafaloni.com/search?q=linen+trousers' },
      { retailer: 'Casatlantic', url: 'https://casatlantic.com/search?q=linen' },
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=linen+trousers+men+pleated' },
    ],
    keywords: ['linen trousers', 'linen pants', 'summer trousers'],
  },
  {
    id: 'gurkha-trousers',
    name: 'Gurkha Trousers',
    categoryId: 'bottoms',
    what: 'High-waisted trousers with a distinctive double-buckle waistband that wraps and fastens across the front — no belt, no side adjusters, the closure IS the design. Usually double-pleated and full through the leg, in cotton drill or linen.',
    history: 'Modelled on the uniform trousers of the Gurkha regiments of the British Indian Army — the wrapped waist suited hot climates and hard wear. Tailoring enthusiasts revived the pattern in the 2010s as high rises returned.',
    useCase: 'A statement trouser for warm-weather tailoring — the waistband deserves to be seen, so wear them with something tucked. They dress up an outfit with no jacket at all, which is their quiet superpower.',
    pairings: ['A tucked polo or knitted tee', 'A linen shirt with sleeves rolled', 'Loafers or sandals, no socks', 'An unstructured blazer at most'],
    essential: false,
    find: [
      { retailer: 'Casatlantic', url: 'https://casatlantic.com/search?q=gurkha' },
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=gurkha+trousers' },
      { retailer: 'Grailed', url: 'https://www.grailed.com/shop?query=gurkha+trousers' },
    ],
    keywords: ['gurkha', 'gurkha trousers', 'double buckle trousers'],
  },
];
