/**
 * WORLD OF MENSWEAR — entries, part 3 of 4: KNITWEAR, FORMALWEAR and
 * BASE LAYERS. See world-entries-1.ts for the editorial conventions.
 */
import type { WorldEntry } from './world-types';

export const WORLD_ENTRIES_KNIT_FORMAL_BASE: WorldEntry[] = [
  // =========================================================================
  // KNITWEAR
  // =========================================================================
  {
    id: 'crew-neck-jumper',
    name: 'Crew Neck Jumper',
    categoryId: 'knitwear',
    what: 'The round-necked pullover — the default jumper. Gauge decides its register: fine merino sits under jackets like a shirt-layer; mid-gauge lambswool is the everyday; chunky knits become outerwear-adjacent. The neckband should sit close without strangling.',
    history: 'Named for the rowing crews who wore them; knitted wool pullovers came up through fishermen’s and athletes’ wardrobes to become, by the mid-twentieth century, the most universal garment in the northern hemisphere’s winters.',
    useCase: 'Everything: over shirts, over tees, under coats and jackets. Navy, grey and cream in lambswool or merino will serve a decade; the crew is the knit to buy first and replace forever.',
    pairings: ['An OCBD with the collar out or in', 'A tee and jeans', 'Under a blazer or overcoat', 'Flannels for quiet smartness'],
    essential: true,
    find: [
      { retailer: "Colhay's", url: 'https://colhays.com/search?q=crew+neck' },
      { retailer: 'John Smedley', url: 'https://www.johnsmedley.com/search?q=crew+neck' },
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=lambswool+crew+neck+jumper' },
    ],
    keywords: ['crew neck', 'crewneck', 'crew-neck', 'jumper', 'sweater', 'pullover'],
  },
  {
    id: 'v-neck-jumper',
    name: 'V-Neck Jumper',
    categoryId: 'knitwear',
    what: 'The pullover with a V-shaped neckline, designed to frame a shirt collar and tie. Depth is everything: a shallow, neat V under tailoring is classic; the deep V of the 2000s is the reason the garment needs rehabilitating.',
    history: 'The V-neck rose with twentieth-century office dress — it existed to show the tie — and with golf and cricket knitwear, where colour-tipped Vs became club signatures. Its fortunes track the tie’s almost exactly.',
    useCase: 'Over a shirt — with or without a tie — under a jacket or on its own; it is the most traditional way to wear knitwear with tailoring. Worn over a bare chest or a tee, it loses its reason to exist.',
    pairings: ['A poplin shirt and knit tie', 'A blazer over the top', 'Grey flannels and derbies', 'A tattersall shirt at the country end'],
    essential: false,
    find: [
      { retailer: 'John Smedley', url: 'https://www.johnsmedley.com/search?q=v+neck' },
      { retailer: "Colhay's", url: 'https://colhays.com/search?q=v-neck' },
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=merino+v+neck+jumper' },
    ],
    keywords: ['v-neck', 'v neck jumper', 'vee neck'],
  },
  {
    id: 'zip-neck-jumper',
    name: 'Zip Neck Jumper',
    categoryId: 'knitwear',
    what: 'A high-collared pullover with a quarter or half zip at the throat — open, it is a relaxed collar; closed, nearly a rollneck. The sportiest member of the classic knit family, best in fine merino or textured lambswool.',
    history: 'Skiwear and golf gave menswear the zip neck in the mid-twentieth century — a practical throat you could vent on the move. It settled into weekend-uniform status for a certain kind of unfussy dresser.',
    useCase: 'Smart-casual layering with adjustability: over a tee or collared shirt, under a jacket or gilet. It reads more relaxed than a crew and more modern than a V — the travel knit par excellence.',
    pairings: ['A tee and chinos', 'A gilet over the top', 'Dark jeans and suede boots', 'An overcoat with the zip half up'],
    essential: false,
    find: [
      { retailer: 'John Smedley', url: 'https://www.johnsmedley.com/search?q=zip+neck' },
      { retailer: "Colhay's", url: 'https://colhays.com/search?q=zip' },
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=merino+quarter+zip+jumper' },
    ],
    keywords: ['zip neck', 'quarter zip', 'half zip', 'zip jumper'],
  },
  {
    id: 'cardigan',
    name: 'Cardigan (Button, Shawl Collar)',
    categoryId: 'knitwear',
    what: 'The open-fronted knit that buttons like a jacket. Two poles: the fine-gauge button cardigan (a knitted waistcoat with sleeves, worn under tailoring or over shirts) and the chunky shawl-collar cardigan (a soft indoor jacket with a rolled collar, the king of comfort).',
    history: 'Named for the 7th Earl of Cardigan, who led the Charge of the Light Brigade in a knitted waistcoat-jacket. Steve McQueen and Paul Newman made the shawl collar mid-century masculine; grandads everywhere kept the button version honest.',
    useCase: 'The fine version replaces a jacket indoors and layers under coats; the shawl version replaces a dressing gown, a fireside jacket and most hope of leaving the sofa. Both want shirts or tees beneath, never bare skin.',
    pairings: ['An OCBD and knit tie (fine, buttoned)', 'A white tee and jeans (shawl, weekend)', 'Grey flannels and loafers', 'A henley and cords by the fire'],
    essential: true,
    find: [
      { retailer: "Colhay's", url: 'https://colhays.com/search?q=cardigan' },
      { retailer: 'John Smedley', url: 'https://www.johnsmedley.com/search?q=cardigan' },
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=shawl+collar+cardigan+wool' },
    ],
    keywords: ['cardigan', 'shawl collar cardigan', 'button cardigan'],
  },
  {
    id: 'roll-neck-jumper',
    name: 'Roll Neck Jumper',
    categoryId: 'knitwear',
    what: 'The pullover with a tall, folded collar covering the neck — knitwear’s answer to a scarf. In heavier gauges (lambswool, geelong, cashmere) it is a winter centrepiece; the fine-gauge version lives in Tops as the shirt-substitute rollneck.',
    history: 'Sailors, dockers and submariners wore them for a century before Hollywood and the existentialists made the black rollneck intellectual shorthand — McQueen in Bullitt fixed the navy version permanently.',
    useCase: 'The centrepiece of cold-weather dressing: under overcoats, blazers and waxed jackets, over nothing but itself. One navy and one cream heavier rollneck cover most of winter.',
    pairings: ['An overcoat and flannels', 'A peacoat and denim', 'A tweed jacket for the country', 'White jeans and boots for contrast'],
    essential: true,
    find: [
      { retailer: "Colhay's", url: 'https://colhays.com/search?q=roll+neck' },
      { retailer: 'Luca Faloni', url: 'https://lucafaloni.com/search?q=cashmere+roll+neck' },
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=lambswool+roll+neck+jumper' },
    ],
    keywords: ['roll neck jumper', 'rollneck jumper', 'turtleneck jumper', 'polo neck jumper'],
  },
  {
    id: 'cable-knit-jumper',
    name: 'Cable Knit Jumper',
    categoryId: 'knitwear',
    what: 'A jumper worked in raised, twisting cable stitches — ropes of knit crossing each other up the body. The texture adds visual weight and actual warmth: crossed stitches trap more air. The Aran is its most famous dialect.',
    history: 'The Aran Islands’ knitting tradition — dense, cream báinín wool worked in cables, diamonds and honeycombs — was sold to the world from the 1930s; the (romantic, disputed) lore says each family knitted its own identifying pattern.',
    useCase: 'Winter weekends and anywhere texture is welcome: over shirts and under waxed or duffle coats. Cream is canonical; navy is the city’s version. Let it be the loudest texture in the outfit.',
    pairings: ['Raw denim and boots', 'Cords and a duffle coat', 'A chambray shirt beneath', 'A watch cap in matching wool'],
    essential: false,
    find: [
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=aran+cable+knit+jumper+wool' },
      { retailer: 'Etsy', url: 'https://www.etsy.com/search?q=aran+cable+knit+sweater+men' },
      { retailer: "Colhay's", url: 'https://colhays.com/search?q=cable' },
    ],
    keywords: ['cable knit', 'cable-knit', 'aran', 'fisherman sweater'],
  },
  {
    id: 'guernsey-sweater',
    name: 'Guernsey / Gansey Sweater',
    categoryId: 'knitwear',
    what: 'The Channel Island fisherman’s jumper: tightly knitted worsted navy wool, a boxy body identical front and back, shoulder-seam detailing, and gussets under the arms for rowing. Dense enough to turn wind and spray — a working garment first.',
    history: 'Knitted in Guernsey since the sixteenth century and spread up the British coast (as the “gansey”), each port developing its own stitch patterns. The Royal Navy adopted it; Nelson’s fleet wore Guernseys.',
    useCase: 'True cold, worn as the fishermen did — over a shirt, under oilskins or a waxed jacket. Its density means it needs no coat until deep winter; the high, tight neck loves a scarf.',
    pairings: ['Raw denim and sea boots', 'A waxed jacket in foul weather', 'Moleskin trousers', 'A Breton tee beneath, nautically'],
    essential: false,
    find: [
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=guernsey+jumper+wool' },
      { retailer: 'Etsy', url: 'https://www.etsy.com/search?q=guernsey+gansey+sweater' },
      { retailer: 'Grailed', url: 'https://www.grailed.com/shop?query=guernsey+sweater' },
    ],
    keywords: ['guernsey', 'gansey', 'fisherman jumper'],
  },
  {
    id: 'fair-isle-jumper',
    name: 'Fair Isle Jumper',
    categoryId: 'knitwear',
    what: 'Stranded colourwork knitting from the Shetland island of Fair Isle: horizontal bands of small geometric motifs in five or more soft, heathered colours. Real Fair Isle uses only two colours per row — the complexity is an illusion of sequence.',
    history: 'Islanders knitted patterned garments for trade from the nineteenth century; the Prince of Wales (later Edward VIII) wore a Fair Isle V-neck to golf in 1922 and created a century of demand overnight.',
    useCase: 'The pattern piece of winter: over plain shirts, under plain coats, with everything else quiet. A Fair Isle slipover over an OCBD is the Ivy-meets-Shetland classic.',
    pairings: ['A plain OCBD or chambray shirt', 'Cords or moleskins', 'A duffle or waxed coat', 'Plain knit accessories only'],
    essential: false,
    find: [
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=fair+isle+jumper+shetland' },
      { retailer: 'Etsy', url: 'https://www.etsy.com/search?q=fair+isle+sweater+men' },
      { retailer: 'Grailed', url: 'https://www.grailed.com/shop?query=fair+isle' },
    ],
    keywords: ['fair isle', 'fairisle', 'colourwork jumper', 'nordic jumper'],
  },
  {
    id: 'fishermans-rib-jumper',
    name: "Fisherman's Rib Jumper",
    categoryId: 'knitwear',
    what: 'A jumper knitted in fisherman’s (half-cardigan) rib — a deep, spongy, double-faced rib that looks hand-knitted even by machine. Thick without weight, stretchy without sag, and texturally richer than plain knit at any gauge.',
    history: 'A stitch from the working-knit tradition of the North Sea coasts — the doubled structure trapped more air for men working in wind. Modern knitwear houses adopted it precisely because it photographs like comfort.',
    useCase: 'The everyday texture knit: anywhere a plain crew would do, this does with more interest. Particularly good in ecru, camel and moss over jeans and cords.',
    pairings: ['Jeans and chukka boots', 'A chore coat over the top', 'Moleskins and a flat cap', 'A tee beneath in autumn'],
    essential: false,
    find: [
      { retailer: "Colhay's", url: 'https://colhays.com/search?q=rib' },
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=fishermans+rib+jumper' },
      { retailer: 'Mr Porter', url: 'https://www.mrporter.com/en-gb/mens/search?keywords=ribbed+sweater' },
    ],
    keywords: ['fisherman rib', "fisherman's rib", 'half cardigan rib', 'ribbed jumper'],
  },
  {
    id: 'waffle-knit-sweater',
    name: 'Waffle Knit Sweater',
    categoryId: 'knitwear',
    what: 'Knitwear in thermal waffle (honeycomb) stitch — a grid of raised squares that traps air in every cell. Lighter than cable, more textured than jersey; in cotton it is the classic thermal, in wool a proper jumper.',
    history: 'The waffle structure comes from thermal underwear — union suits and henleys of the American workwear tradition — and climbed into outer knitwear when texture became a design language of its own.',
    useCase: 'Layering weather: alone over a tee, under overshirts and field jackets. The waffle henley is the bridge piece — base layer by construction, casual top by adoption.',
    pairings: ['A field jacket and jeans', 'An overshirt in early winter', 'Fatigues and crepe-sole boots', 'A tee beneath for the collar line'],
    essential: false,
    find: [
      { retailer: 'Merz b. Schwanen', url: 'https://www.merz-schwanen.com/search?q=waffle' },
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=waffle+knit+thermal+men' },
      { retailer: 'Mr Porter', url: 'https://www.mrporter.com/en-gb/mens/search?keywords=waffle+knit' },
    ],
    keywords: ['waffle knit', 'thermal knit', 'honeycomb knit'],
  },
  {
    id: 'rugby-shirt',
    name: 'Rugby Shirt',
    categoryId: 'knitwear',
    what: 'The heavyweight cotton jersey of the rugby field: bold hoops, a stiff twill contrast collar, rubber buttons (so they snap off rather than injure), and a cut built to take a tackle. Between a polo and a sweatshirt, tougher than both.',
    history: 'English school and club rugby of the nineteenth century — hooped colours told teams apart in the mud. Ralph Lauren and Ivy campuses adopted it; every prep revival since has re-run the play.',
    useCase: 'Weekend casual with collegiate energy: with jeans, chinos or shorts. Wear the hoops proudly or choose a solid with contrast collar for the quieter read; either way it wants nothing formal near it.',
    pairings: ['Ecru jeans and boat shoes', 'Chino shorts in spring', 'Under a duffle coat', 'White sneakers and a cap'],
    essential: false,
    find: [
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=heavyweight+rugby+shirt+cotton' },
      { retailer: 'Grailed', url: 'https://www.grailed.com/shop?query=rugby+shirt' },
      { retailer: 'Mr Porter', url: 'https://www.mrporter.com/en-gb/mens/search?keywords=rugby+shirt' },
    ],
    keywords: ['rugby shirt', 'rugby jersey', 'hooped shirt'],
  },
  {
    id: 'shetland-jumper',
    name: 'Shetland Jumper',
    categoryId: 'knitwear',
    what: 'The crew neck knitted from Shetland wool — lofty, slightly hairy, heathered in colours drawn from the islands themselves. The “brushed Shetland” raises that halo further. Light for its warmth and nearly indestructible.',
    history: 'Knitted in the Shetland Islands for centuries from the native sheep’s wool; the Ivy League stores imported them by the boatload in the 1950s–60s, making the Shetland crew the definitive campus jumper.',
    useCase: 'The autumn-to-spring default over an OCBD or chambray shirt — the slight scratch is the charm (layer accordingly). The heathered colours — moss, ochre, peat, lovat — do half your outfit’s work.',
    pairings: ['An OCBD and chinos (the Ivy axiom)', 'Cords and desert boots', 'A waxed jacket over', 'Grey flannels for soft tailoring'],
    essential: false,
    find: [
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=shetland+wool+jumper+crew' },
      { retailer: "Colhay's", url: 'https://colhays.com/search?q=shetland' },
      { retailer: 'Etsy', url: 'https://www.etsy.com/search?q=shetland+wool+sweater' },
    ],
    keywords: ['shetland', 'shetland jumper', 'brushed shetland'],
  },
  {
    id: 'knitted-polo',
    name: 'Knitted Polo',
    categoryId: 'knitwear',
    what: 'A polo shirt executed in true knitwear — fine merino, cotton or silk-blend knit with a soft collar and two- or three-button placket, long- or short-sleeved. It drapes and moves like a jumper while reading like a shirt.',
    history: 'The golfwear and Riviera staple of the 1950s–60s — think Bond’s Sunspel polos and the Italian “maglia” tradition — revived hard in the 2010s as tailoring went tieless and needed something with a collar.',
    useCase: 'Smart-casual’s current answer to the shirt: under blazers and suits without a tie, tucked into pleated trousers, alone with chinos. Long-sleeved and tucked, it is the most flattering knit a man can wear with tailoring.',
    pairings: ['An unstructured suit, no tie', 'Pleated linen trousers, tucked', 'Grey flannels and loafers', 'A blouson at the weekend'],
    essential: false,
    find: [
      { retailer: 'John Smedley', url: 'https://www.johnsmedley.com/search?q=polo' },
      { retailer: "Colhay's", url: 'https://colhays.com/search?q=polo' },
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=knitted+polo+merino' },
    ],
    keywords: ['knitted polo', 'knit polo', 'long sleeve polo', 'merino polo'],
  },
  {
    id: 'slipover',
    name: 'Slipover (Sweater Vest)',
    categoryId: 'knitwear',
    what: 'The sleeveless pullover — a knitted V- or crew-neck vest worn over a shirt. It warms the core without bulking the arms, layers under jackets invisibly, and displays a shirt-and-tie combination like a frame.',
    history: 'Golf and cricket wear of the early twentieth century (the “cricket vest” survives in tipped cream form), a fixture of mid-century office dress, gleefully revived by both Ivy stylists and streetwear.',
    useCase: 'Layering with intent: over an OCBD or poplin shirt, under a jacket or alone. Fair Isle and cable slipovers add pattern without sleeves’ weight; plain lambswool ones read quietly donnish.',
    pairings: ['An OCBD and chinos', 'A shirt and knit tie beneath a jacket', 'Pleated trousers for the vintage read', 'A grandad-collar shirt, softly'],
    essential: false,
    find: [
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=lambswool+slipover+sleeveless+jumper' },
      { retailer: "Colhay's", url: 'https://colhays.com/search?q=slipover' },
      { retailer: 'Etsy', url: 'https://www.etsy.com/search?q=sweater+vest+wool+men' },
    ],
    keywords: ['slipover', 'sweater vest', 'sleeveless jumper', 'tank top knit'],
  },

  // =========================================================================
  // SWEATSHIRTS
  // =========================================================================
  {
    id: 'crewneck-sweatshirt',
    name: 'Crewneck Sweatshirt',
    categoryId: 'sweatshirts',
    what: 'The round-necked cotton fleece pullover — loopback (French terry) or brushed-back jersey, a V-stitch insert at the throat on the classic pattern, ribbed hem and cuffs. Weight decides the register: loopwheeled 12oz cloth reads considered; thin mall fleece reads disposable.',
    history: 'Born on American athletic fields in the 1920s — Benjamin Russell Jr.’s cotton practice jersey replaced itchy wool — and codified by Champion’s reverse weave. Japanese loopwheel mills kept the original machines running when everyone else modernised, which is why the best sweatshirt in the world is now made in Wakayama.',
    useCase: 'The off-duty mid-layer: over a tee or OCBD, under a field jacket or overcoat. Grey marl first, then navy; a plain, unbranded chest is what keeps it adult.',
    pairings: ['A white tee and ecru jeans', 'An OCBD with the collar out', 'Under a waxed jacket', 'Grey sweat over grey flannel for the high-low read'],
    essential: false,
    find: [
      { retailer: 'Merz b. Schwanen', url: 'https://www.merz-schwanen.com/search?q=sweatshirt' },
      { retailer: 'Camber USA', url: 'https://camberusa.com/collections/fleece' },
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=loopwheel+sweatshirt' },
    ],
    keywords: ['sweatshirt', 'crewneck sweatshirt', 'loopback', 'french terry', 'reverse weave', 'loopwheel'],
  },
  {
    id: 'hoodie',
    name: 'Hoodie',
    categoryId: 'sweatshirts',
    what: 'The hooded sweatshirt — a crewneck with a two-panel hood, drawcord and (on the pullover) a kangaroo pocket. Pullover is the classic; the full zip is the layering version. Cloth weight and an empty chest decide whether it reads considered or gym-bound.',
    history: 'Champion added the hood for warehouse workers and sideline athletes in the 1930s; it passed through Rocky, hip-hop and skateboarding to become the most worn garment of the century — and, done properly, one of the most useful.',
    useCase: 'Casual layering: under an overcoat, topcoat or leather jacket — the high-low pairing that modernises tailored outerwear. Alone with jeans it wants heft and a hood that stands.',
    pairings: ['Under a wool overcoat (the high-low classic)', 'Raw denim and clean sneakers', 'A harrington over the top', 'Fatigues and service boots'],
    essential: false,
    find: [
      { retailer: 'Camber USA', url: 'https://camberusa.com/collections/fleece' },
      { retailer: 'Lady White Co.', url: 'https://www.ladywhiteco.com/collections/fleece' },
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=heavyweight+pullover+hoodie' },
    ],
    keywords: ['hoodie', 'hooded sweatshirt', 'pullover hoodie', 'zip hoodie'],
  },
  {
    id: 'fleece-pullover',
    name: 'Fleece Pullover',
    categoryId: 'sweatshirts',
    what: 'The synthetic-pile mid-layer — a quarter-snap or half-zip pullover in polyester fleece, warm for its weight and quick to dry. The Snap-T silhouette is the reference: boxy, colour-blocked, a single chest pocket. Worn as an outer layer it crosses into outerwear; as a pullover it lives here.',
    history: 'Malden Mills (now Polartec) and Patagonia developed synthetic fleece in the late 1970s as wool’s lighter successor; the 1985 Snap-T made it a design object. Gorpcore returned it to town wardrobes forty years on.',
    useCase: 'Cold-weather casual: over a tee or flannel shirt, under a shell when the weather turns. It brings honest outdoors provenance — keep everything around it simple.',
    pairings: ['A flannel shirt and jeans', 'Fatigues and trail shoes', 'Under a waxed jacket in the wet', 'A watch cap and wool socks'],
    essential: false,
    find: [
      { retailer: 'Patagonia', url: 'https://eu.patagonia.com/gb/en/search/?q=snap-t' },
      { retailer: 'Mr Porter', url: 'https://www.mrporter.com/en-gb/mens/search?keywords=fleece+pullover' },
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=patagonia+snap-t+fleece' },
    ],
    keywords: ['fleece pullover', 'snap-t', 'polar fleece', 'pile fleece', 'quarter zip fleece'],
  },

  // =========================================================================
  // FORMALWEAR
  // =========================================================================
  {
    id: 'two-piece-suit',
    name: 'Two-Piece Suit',
    categoryId: 'formalwear',
    what: 'Jacket and trousers cut from the same cloth — the foundation stone of formal menswear. Single-breasted, two or three buttons, in navy or charcoal worsted first; everything else in tailoring is a variation on this theme.',
    history: 'The lounge suit emerged in mid-nineteenth-century Britain as informal country wear, then dethroned the frock coat entirely by the 1920s. A century of refinement has changed lapel widths and little else.',
    useCase: 'Business, weddings, funerals, occasions — and, broken into separates, half a wardrobe. The first suit should be navy or charcoal wool, softly constructed, and fitted by a tailor rather than a size chart.',
    pairings: ['A white or pale blue poplin shirt', 'Oxfords or derbies', 'A grenadine or knit tie', 'A rollneck for the modern evening read'],
    essential: true,
    find: [
      { retailer: 'Berg & Berg', url: 'https://bergbergstore.com/search?q=suit' },
      { retailer: "Drake's", url: 'https://drakes.com/search?q=suit' },
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=navy+wool+suit+canvassed' },
    ],
    keywords: ['suit', 'two piece suit', 'two-piece', 'lounge suit'],
  },
  {
    id: 'three-piece-suit',
    name: 'Three-Piece Suit',
    categoryId: 'formalwear',
    what: 'The two-piece plus a matching waistcoat. The waistcoat adds a vertical layer that keeps a jacketless man dressed, warms the core, and gives the suit a Victorian gravity no two-piece has.',
    history: 'Charles II decreed the vest into English dress in 1666 (Pepys recorded it); the three-piece WAS the suit until the twentieth century pared it back. It survives as the suit’s ceremonial and cold-weather form.',
    useCase: 'Winter tailoring, weddings and any occasion worth an extra layer of intent. The waistcoat’s bottom button stays undone — Edward VII’s girth made it custom, and custom made it law.',
    pairings: ['A watch chain if you dare', 'A poplin shirt and sober tie', 'Black Oxfords, polished', 'A covert or Ulster coat over'],
    essential: false,
    find: [
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=three+piece+suit+wool' },
      { retailer: 'Mr Porter', url: 'https://www.mrporter.com/en-gb/mens/search?keywords=three+piece+suit' },
      { retailer: 'Grailed', url: 'https://www.grailed.com/shop?query=three+piece+suit' },
    ],
    keywords: ['three piece suit', 'three-piece', 'suit with waistcoat'],
  },
  {
    id: 'sport-coat',
    name: 'Sport Coat / Odd Jacket',
    categoryId: 'formalwear',
    what: 'The tailored jacket worn with non-matching trousers — in cloths with texture and pattern (tweed, hopsack, houndstooth, corduroy) that no suit would risk. Softer shoulders and patch pockets welcome; it is tailoring off duty.',
    history: 'Born of Victorian sporting wardrobes — shooting and Norfolk jackets — then formalised by the 1920s–30s as “odd jackets” for town. American Ivy made the tweed-jacket-and-flannels combination a uniform of its own.',
    useCase: 'Everywhere a suit is too much and a jumper too little: dinners, offices without dress codes, any smart-casual brief. One navy hopsack and one brown tweed cover four seasons of it.',
    pairings: ['Grey flannels and loafers', 'Dark denim and Chelsea boots', 'An OCBD and knit tie', 'A rollneck in winter'],
    essential: true,
    find: [
      { retailer: "Drake's", url: 'https://drakes.com/search?q=jacket' },
      { retailer: 'Berg & Berg', url: 'https://bergbergstore.com/search?q=sport+coat' },
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=tweed+sport+coat+harris' },
    ],
    keywords: ['sport coat', 'sports jacket', 'odd jacket', 'tweed jacket'],
  },
  {
    id: 'waistcoat',
    name: 'Waistcoat / Vest',
    categoryId: 'formalwear',
    what: 'The sleeveless, buttoned torso layer of classic tailoring — high-cut in its suit form, lower and horseshoe-shaped for evening dress, and rustic in tweed or moleskin as the “odd waistcoat”. Worn correctly it shows a V of shirt and covers the waistband entirely.',
    history: 'Introduced by Charles II in 1666 as court reform against French fashion; three centuries as the suit’s middle layer followed. The odd waistcoat survives in country dress and among barmen, tailors and the wedding trade.',
    useCase: 'With a suit (as the third piece), at weddings (morning dress’s buff waistcoat), or odd over a shirt with country tailoring. It must be long enough — shirt showing beneath a waistcoat hem is the classic fitting error.',
    pairings: ['A tweed jacket and cords (odd, country)', 'Morning dress at a wedding', 'A collarless shirt for the working look', 'A watch chain across the front'],
    essential: false,
    find: [
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=tweed+waistcoat+men' },
      { retailer: 'Etsy', url: 'https://www.etsy.com/search?q=wool+waistcoat+men' },
      { retailer: 'Mr Porter', url: 'https://www.mrporter.com/en-gb/mens/search?keywords=waistcoat' },
    ],
    keywords: ['waistcoat', 'vest', 'odd waistcoat', 'gilet tailored'],
  },
  {
    id: 'morning-coat',
    name: 'Morning Coat',
    categoryId: 'formalwear',
    what: 'The daytime ceremonial coat: black or grey, cut away in an elegant sweep from the front waist button to tails behind. Worn as “morning dress” with striped or houndstooth trousers, a buff or dove waistcoat, and a proper tie or cravat.',
    history: 'Eighteenth-century riding coats were cut away for the saddle; by the Edwardian era the morning coat was standard formal day dress. It survives at British weddings, Royal Ascot and state occasions — the last redoubt of daytime formality.',
    useCase: 'Formal daytime occasions that specify it: weddings, Ascot’s Royal Enclosure, investitures. It is hired more often than owned — unless your calendar justifies the wardrobe space, hire well instead.',
    pairings: ['Cashmere-striped trousers', 'A dove grey waistcoat', 'A white shirt and silver tie', 'Black Oxfords, mirror-polished'],
    essential: false,
    find: [
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=morning+coat+tailcoat+grey' },
      { retailer: 'Etsy', url: 'https://www.etsy.com/search?q=morning+coat+vintage' },
      { retailer: 'Grailed', url: 'https://www.grailed.com/shop?query=morning+coat' },
    ],
    keywords: ['morning coat', 'morning dress', 'cutaway coat'],
  },
  {
    id: 'dinner-jacket',
    name: 'Dinner Jacket / Tuxedo',
    categoryId: 'formalwear',
    what: 'The black-tie evening jacket: black or midnight blue with silk-faced lapels (peak or shawl, never notch by tradition), worn with matching silk-striped trousers, a marcella or pleated shirt, and a black bow tie. Midnight blue reads blacker than black under artificial light.',
    history: 'The tailless evening jacket appeared in the 1860s–80s — the Prince of Wales’s informal Sandringham dinners and New York’s Tuxedo Park club both claim it. It replaced white tie almost everywhere across the twentieth century.',
    useCase: 'Black-tie events, strictly after six. Buy once, buy classic — one-button, grosgrain shawl or peak lapel — and it will outlast every trend and most marriages.',
    pairings: ['A marcella-front shirt', 'A black silk bow tie (self-tied)', 'Opera pumps or polished wholecuts', 'A white pocket square, one point'],
    essential: false,
    find: [
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=midnight+blue+dinner+jacket' },
      { retailer: 'Mr Porter', url: 'https://www.mrporter.com/en-gb/mens/search?keywords=tuxedo' },
      { retailer: 'Grailed', url: 'https://www.grailed.com/shop?query=dinner+jacket' },
    ],
    keywords: ['dinner jacket', 'tuxedo', 'black tie', 'smoking'],
  },
  {
    id: 'nehru-jacket',
    name: 'Nehru Jacket',
    categoryId: 'formalwear',
    what: 'A hip-length tailored jacket with a stand (mandarin) collar and no lapels, buttoning high to the throat. The clean vertical front gives it a spare, modern formality that Western tailoring cannot reproduce.',
    history: 'Derived from the Indian achkan and bandhgala court dress, named in the West for Prime Minister Jawaharlal Nehru who wore the style through the 1950s–60s. The Beatles’ Shea Stadium jackets made it a Western fashion moment.',
    useCase: 'Occasions that welcome elegant difference — evening events, weddings (essential dress at many South Asian ones), creative-formal settings. It wants a collarless or band-collar shirt beneath, never a tie.',
    pairings: ['A grandad-collar shirt', 'Slim dark trousers', 'Monk straps or wholecuts', 'A pocket square as the only ornament'],
    essential: false,
    find: [
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=nehru+jacket+bandhgala' },
      { retailer: 'Etsy', url: 'https://www.etsy.com/search?q=nehru+jacket+men' },
      { retailer: 'Grailed', url: 'https://www.grailed.com/shop?query=nehru+jacket' },
    ],
    keywords: ['nehru', 'bandhgala', 'mandarin collar jacket'],
  },
  {
    id: 'double-breasted-suit',
    name: 'Double-Breasted Suit',
    categoryId: 'formalwear',
    what: 'The suit whose jacket fronts overlap and button in two columns — classically six buttons with two to fasten (6x2), peak lapels, and a fuller wrap across the chest. It carries more cloth, more structure and more authority than any single-breasted cut.',
    history: 'Descended from naval reefer coats, it peaked in the 1930s drape era — the Duke of Windsor’s Kent cut — and again in the 1980s power decade. Its fortunes cycle; its swagger never changes.',
    useCase: 'Tailoring with presence: keep it buttoned when standing (the DB does not slouch), and let the lapels do the talking. In flannel or hopsack it dresses down surprisingly well without a tie.',
    pairings: ['A rollneck for the modern read', 'A poplin shirt and sober tie', 'Suede loafers to soften it', 'A covert coat over, in winter'],
    essential: false,
    find: [
      { retailer: 'Berg & Berg', url: 'https://bergbergstore.com/search?q=double+breasted' },
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=double+breasted+suit+peak+lapel' },
      { retailer: 'Grailed', url: 'https://www.grailed.com/shop?query=double+breasted+suit' },
    ],
    keywords: ['double breasted', 'double-breasted', 'db suit', '6x2'],
  },
  {
    id: 'smoking-jacket',
    name: 'Smoking Jacket',
    categoryId: 'formalwear',
    what: 'The at-home evening jacket: velvet or silk, shawl-collared, often frogged or sashed, in bottle green, burgundy or midnight. Designed to absorb cigar smoke so the good coat didn’t have to — now the most theatrical garment a man can legitimately own.',
    history: 'Victorian gentlemen retired to the smoking room and armoured themselves in quilted silk; the jacket’s golden age ran through Noel Coward to Hefner. In much of Europe “smoking” still means the dinner suit it fathered.',
    useCase: 'Hosting at home in black-tie-adjacent comfort, and (worn as an odd jacket) creative black tie where the invitation smiles on it. With velvet slippers, its natural footwear, the look completes itself.',
    pairings: ['A marcella shirt and bow tie', 'Velvet Albert slippers', 'Dress trousers with a silk stripe', 'A cigar, notionally'],
    essential: false,
    find: [
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=velvet+smoking+jacket' },
      { retailer: 'Etsy', url: 'https://www.etsy.com/search?q=smoking+jacket+velvet' },
      { retailer: 'Grailed', url: 'https://www.grailed.com/shop?query=smoking+jacket' },
    ],
    keywords: ['smoking jacket', 'velvet jacket', 'house jacket'],
  },
  {
    id: 'evening-tailcoat',
    name: 'Evening Tailcoat (White Tie)',
    categoryId: 'formalwear',
    what: 'The most formal garment in menswear: a black cutaway coat squared at the front waist with tails behind, worn open over a white marcella waistcoat, starched-front shirt with wing collar, and white bow tie. Every element is codified to the millimetre.',
    history: 'The Regency riding coat formalised into nineteenth-century evening dress and stopped evolving around 1900 — white tie is a living museum piece. State banquets, certain balls and the concert stage keep it breathing.',
    useCase: 'Only where “white tie” is printed on the card — nothing else qualifies and nothing else may substitute. Hire from a specialist unless invitations like that arrive often enough to justify tailoring one.',
    pairings: ['A white marcella waistcoat and bow tie', 'A starched wing-collar shirt', 'Opera pumps and black silk hose', 'White gloves, historically'],
    essential: false,
    find: [
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=white+tie+evening+tailcoat' },
      { retailer: 'Etsy', url: 'https://www.etsy.com/search?q=evening+tailcoat+vintage' },
      { retailer: 'Grailed', url: 'https://www.grailed.com/shop?query=tailcoat' },
    ],
    keywords: ['tailcoat', 'white tie', 'evening tails', 'full dress'],
  },

  // =========================================================================
  // BASE LAYERS
  // =========================================================================
  {
    id: 'undershirt',
    name: 'Undershirt (V-Neck, Crew)',
    categoryId: 'base-layers',
    what: 'The thin cotton or modal layer between skin and shirt: crew neck when no collar button will ever open, V-neck (or deep-V) when one will — the undershirt’s first law is that it must never be seen at the neckline. White under white, grey or tonal under everything else.',
    history: 'Descended from the union suits and vests of the nineteenth century, split into the modern singlet and tee by the US Navy. Clark Gable famously skipped his in It Happened One Night (1934) and allegedly cratered sales for a decade.',
    useCase: 'Under dress shirts to absorb, insulate and extend the shirt’s clean life — invisibly. Fine merino versions do the same job with better temperature manners.',
    pairings: ['Under a poplin dress shirt', 'Under an OCBD in winter', 'Under a rollneck for warmth', 'Never as outerwear — that is a T-shirt’s job'],
    essential: true,
    find: [
      { retailer: 'Sunspel', url: 'https://www.sunspel.com/search?q=undershirt' },
      { retailer: 'Lady White Co.', url: 'https://www.ladywhiteco.com/search?q=tee' },
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=cotton+undershirt+v+neck' },
    ],
    keywords: ['undershirt', 'vest top', 'under tee', 'a-shirt'],
  },
  {
    id: 'thermal-base-layer',
    name: 'Thermal Base Layer Top',
    categoryId: 'base-layers',
    what: 'The insulating first layer for real cold: waffle-knit cotton in the heritage version, technical synthetics or merino in the modern one. It works by trapping air against the skin — fit must be close or the physics fail.',
    history: 'From union suits to army-surplus “waffle tops”, thermals were pure function until workwear style adopted the henley-collared thermal as a garment in its own right.',
    useCase: 'Under shirts and knits in deep winter, under workwear always, and — in its waffle henley form — as a visible layer under open flannels and chore coats.',
    pairings: ['Under a flannel shirt', 'Under a CPO or chore coat', 'With fatigues and boots', 'Under a Guernsey on the coldest days'],
    essential: false,
    find: [
      { retailer: 'Merz b. Schwanen', url: 'https://www.merz-schwanen.com/search?q=thermal' },
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=waffle+thermal+top+men' },
      { retailer: 'Filson', url: 'https://www.filson.com/search?q=base+layer' },
    ],
    keywords: ['thermal', 'thermal top', 'waffle thermal', 'base layer top'],
  },
  {
    id: 'long-sleeve-base-layer',
    name: 'Long-Sleeve Base Layer',
    categoryId: 'base-layers',
    what: 'The full-arm version of the first layer — a close-fitting long-sleeved top in cotton, merino or technical knit that carries warmth to the wrists without adding bulk at the body.',
    history: 'Standard military and mountaineering issue for a century — the long-sleeved undervest — refined by the outdoor industry into the layering system’s foundation garment.',
    useCase: 'Winter layering under shirts, knits and jackets — especially when outer layers are unlined (waxed cotton, denim). The sleeves matter when cuffs meet wind.',
    pairings: ['Under a chambray or flannel shirt', 'Under an unlined waxed jacket', 'With a gilet directly over', 'Under a rugby shirt outdoors'],
    essential: false,
    find: [
      { retailer: 'Sunspel', url: 'https://www.sunspel.com/search?q=long+sleeve' },
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=long+sleeve+base+layer+merino' },
      { retailer: 'Mr Porter', url: 'https://www.mrporter.com/en-gb/mens/search?keywords=base+layer' },
    ],
    keywords: ['long sleeve base layer', 'long-sleeve thermal', 'undervest long sleeve'],
  },
  {
    id: 'merino-base-layer',
    name: 'Merino Wool Base Layer',
    categoryId: 'base-layers',
    what: 'The finest base layer cloth there is: superfine merino wool, which insulates when damp, breathes when warm, and resists odour for days — no synthetic matches the full set. Weight is measured in gsm: 150–200 for most wear.',
    history: 'Merino sheep came from Spain via Australasia; the outdoor industry’s rediscovery of fine wool in the 1990s–2000s (Icebreaker, Smartwool) broke the synthetic monopoly and reached menswear as travel-wear common sense.',
    useCase: 'Travel, winter, sport and any long day between climates — worn against skin under anything. One merino tee and one long-sleeve will quietly outperform a drawer of cotton.',
    pairings: ['Under everything in winter', 'Alone as a tee when travelling', 'Under a zip-neck on cold walks', 'With merino socks — commit'],
    essential: true,
    find: [
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=merino+base+layer+200gsm' },
      { retailer: 'Mr Porter', url: 'https://www.mrporter.com/en-gb/mens/search?keywords=merino+base+layer' },
      { retailer: 'John Smedley', url: 'https://www.johnsmedley.com/search?q=merino' },
    ],
    keywords: ['merino base layer', 'merino wool top', 'wool base layer'],
  },
  {
    id: 'long-johns',
    name: 'Long Johns',
    categoryId: 'base-layers',
    what: 'The bottom half of the thermal system: close-fitting knitted leg layers in cotton waffle, merino or blends, worn under trousers. Unseen, unsung, and the difference between enduring winter and enjoying it.',
    history: 'Named — the story goes — for boxer John L. Sullivan, who fought in similar; descended from the bisected union suit. Standard cold-climate issue for every army and outdoor trade since.',
    useCase: 'Under trousers in genuine cold — commutes, matches, mountains. Merino versions layer under tailoring invisibly; nobody at the meeting needs to know.',
    pairings: ['Under jeans on freezing days', 'Under flannel trousers in an unheated church', 'With boot socks and boots', 'Under ski wear, obviously'],
    essential: false,
    find: [
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=merino+long+johns+men' },
      { retailer: 'Merz b. Schwanen', url: 'https://www.merz-schwanen.com/search?q=long+johns' },
      { retailer: 'Mr Porter', url: 'https://www.mrporter.com/en-gb/mens/search?keywords=long+johns' },
    ],
    keywords: ['long johns', 'thermal bottoms', 'base layer bottoms', 'long underwear'],
  },
  {
    id: 'dress-socks',
    name: 'Dress Socks (Over-the-Calf)',
    categoryId: 'base-layers',
    what: 'Fine-gauge socks in cotton lisle, merino or silk blends, properly over-the-calf so no shin ever shows when seated. Colour follows trouser (not shoe); pattern — ribs, birdseye — is the connoisseur’s quiet signature.',
    history: 'Hosiery predates trousers by centuries — stockings were once the display garment of a man’s leg. The over-the-calf convention survives from that era: the leg of a dressed man stays covered.',
    useCase: 'With tailoring always; the calf-length rule is what separates finished from nearly. Navy with grey trousers, burgundy with navy — the small harmonies add up.',
    pairings: ['Charcoal trousers and black Oxfords', 'A navy suit with burgundy socks', 'Loafers and flannels', 'Boots, in boot-weight wool versions'],
    essential: true,
    find: [
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=over+the+calf+dress+socks+cotton+lisle' },
      { retailer: 'Mr Porter', url: 'https://www.mrporter.com/en-gb/mens/search?keywords=dress+socks' },
      { retailer: "Drake's", url: 'https://drakes.com/search?q=socks' },
    ],
    keywords: ['dress socks', 'over the calf socks', 'socks', 'hosiery'],
  },
];
