/**
 * WORLD OF MENSWEAR — entries, part 2 of 4: SHOES and OUTERWEAR.
 * See world-entries-1.ts for the editorial conventions.
 */
import type { WorldEntry } from './world-types';

export const WORLD_ENTRIES_SHOES_OUTERWEAR: WorldEntry[] = [
  // =========================================================================
  // SHOES
  // =========================================================================
  {
    id: 'oxford-shoe',
    name: 'Oxford (Cap-Toe, Plain-Toe, Brogue)',
    categoryId: 'shoes',
    what: 'The most formal lace-up: its defining feature is closed lacing, where the eyelet tabs are stitched under the vamp so the throat closes in a neat V. Cap-toe (a straight seam across the toe) is the business standard; plain-toe is sleeker still; brogued Oxfords add perforations and drop a formality notch.',
    history: 'Named for the half-boot Oxford students adopted in the nineteenth century as a rebellion against knee boots. The black cap-toe Oxford became THE shoe of the City, the boardroom and the morning suit — a position it has never lost.',
    useCase: 'Suits and formality — black cap-toes for business and ceremony, dark brown for suits with more texture. Their sleekness fights casual clothing; below flannel trousers they start to look stranded.',
    pairings: ['A navy or charcoal suit', 'Grey flannels and a blazer', 'A dinner suit (in polished plain-toe form)', 'A covert coat over tailoring'],
    essential: true,
    find: [
      { retailer: 'Morjas', url: 'https://www.morjas.com/search?q=oxford' },
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=cap+toe+oxford+shoes+goodyear+welted' },
      { retailer: 'Mr Porter', url: 'https://www.mrporter.com/en-gb/mens/search?keywords=oxford+shoes' },
    ],
    keywords: ['oxford shoe', 'cap toe', 'cap-toe', 'balmoral', 'closed lacing'],
  },
  {
    id: 'derby',
    name: 'Derby',
    categoryId: 'shoes',
    what: 'The lace-up with open lacing — the eyelet tabs are stitched on top of the vamp, so the throat opens wide. That single construction difference makes the derby roomier, easier to fit and inherently less formal than the Oxford: the workhorse smart shoe.',
    history: 'Attributed to the 14th Earl of Derby, whose generous foot demanded an easier entry, and standardised as a military and sporting shoe through the nineteenth century — open lacing suited gaiters and field wear.',
    useCase: 'The versatile smart lace-up: everything from suits (in sleek dark calf) to jeans (in grain leather or suede with a chunkier sole). If a man owns one pair of leather shoes, a dark brown derby is the strongest single answer.',
    pairings: ['Flannel or tweed tailoring', 'Dark selvedge denim', 'Cords and a Shetland', 'A suit when the Oxford feels stiff'],
    essential: true,
    find: [
      { retailer: 'Morjas', url: 'https://www.morjas.com/search?q=derby' },
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=derby+shoes+goodyear+welted' },
      { retailer: 'Mr Porter', url: 'https://www.mrporter.com/en-gb/mens/search?keywords=derby+shoes' },
    ],
    keywords: ['derby', 'blucher', 'open lacing', 'derbies'],
  },
  {
    id: 'loafer',
    name: 'Loafer (Penny, Tassel, Horsebit)',
    categoryId: 'shoes',
    what: 'The slip-on moccasin-construction shoe in its three canonical forms: the penny (a saddle strap with a diamond slot), the tassel (leather laces ending in tassels), and the horsebit (a metal snaffle across the instep). No laces, endless nonchalance.',
    history: 'Norwegian fishermen’s slip-ons crossed to America via Esquire and G.H. Bass, whose 1936 “Weejun” penny loafer conquered the campuses; students kept a penny in the slot for the payphone. Gucci’s 1953 horsebit took the type from prep to boardroom-glamour.',
    useCase: 'The definitive smart-casual shoe — sharp with tailoring, easy with denim, correct without socks in summer. Burgundy and dark brown penny loafers are the most versatile; suede raises the ease, horsebits raise the flash.',
    pairings: ['Grey flannels (the eternal match)', 'Chinos and an OCBD', 'White jeans in summer, no socks', 'A navy suit worn without a tie'],
    essential: true,
    find: [
      { retailer: 'Morjas', url: 'https://www.morjas.com/search?q=loafer' },
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=penny+loafers+leather' },
      { retailer: 'Grailed', url: 'https://www.grailed.com/shop?query=horsebit+loafer' },
    ],
    keywords: ['loafer', 'penny loafer', 'tassel loafer', 'horsebit', 'weejun', 'slip-on'],
  },
  {
    id: 'chelsea-boot',
    name: 'Chelsea Boot',
    categoryId: 'shoes',
    what: 'An ankle boot with elastic side gussets and a pull tab — no laces, one clean silhouette. In polished calf it is nearly as sharp as an Oxford; in suede with a crepe or rubber sole it is a weekend staple. The line matters: sleek last, trim ankle.',
    history: 'Patented by J. Sparkes-Hall, bootmaker to Queen Victoria, in 1851 — vulcanised elastic was the new technology. A century later the Beatles ordered Cuban-heeled pairs from Anello & Davide and the “Chelsea” (for the King’s Road set) became rock and roll’s boot.',
    useCase: 'The smartest boot: tailoring in winter, slim or straight jeans always. Black calf for sharp, brown suede for soft — both slide under a trouser leg with no bulk.',
    pairings: ['An overcoat and rollneck', 'Slim dark denim and a harrington', 'Grey flannels and a tweed coat', 'A black suit, black boots, no tie'],
    essential: true,
    find: [
      { retailer: 'Morjas', url: 'https://www.morjas.com/search?q=chelsea+boot' },
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=chelsea+boots+goodyear+welted' },
      { retailer: 'Mr Porter', url: 'https://www.mrporter.com/en-gb/mens/search?keywords=chelsea+boots' },
    ],
    keywords: ['chelsea boot', 'elastic sided boot', 'dealer boot'],
  },
  {
    id: 'desert-boot',
    name: 'Desert Boot',
    categoryId: 'shoes',
    what: 'A two-eyelet ankle boot in suede on a crepe rubber sole — soft, unlined, and deliberately simple. The crepe sole and stitched-down construction give it a relaxed, slightly rumpled character no dress boot has.',
    history: 'Nathan Clark of the Clarks family copied the boots British officers had made in Cairo’s bazaars during the desert campaign, launching the style in 1950. It became a mod icon, then a menswear constant — the anti-status status shoe.',
    useCase: 'Casual, spring through autumn: jeans, chinos, fatigues. It reads best a little scuffed — this is not a shoe to baby — and sand suede is the canonical colour.',
    pairings: ['Chinos and an OCBD', 'Washed denim and a harrington', 'Olive fatigues and a tee', 'A field jacket in autumn'],
    essential: true,
    find: [
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=clarks+desert+boots+suede' },
      { retailer: 'Mr Porter', url: 'https://www.mrporter.com/en-gb/mens/search?keywords=desert+boots' },
      { retailer: 'Grailed', url: 'https://www.grailed.com/shop?query=desert+boot' },
    ],
    keywords: ['desert boot', 'crepe sole boot', 'sand suede boot'],
  },
  {
    id: 'chukka-boot',
    name: 'Chukka Boot',
    categoryId: 'shoes',
    what: 'The desert boot’s dressier parent: an ankle boot with two or three eyelets and a rounded toe, in suede or calf, on a leather or rubber sole. Where the desert boot is defined by crepe, the chukka spans everything from casual to nearly-smart.',
    history: 'The name comes from polo — a “chukka” is a period of play — and the boot from the ankle boots polo players wore off the field in 1920s–30s British India. It entered the mainstream through post-war sportswear.',
    useCase: 'The one-boot answer to autumn: smart enough for chinos and tweed, easy enough for denim. Dark brown suede on a Dainite rubber sole is the most useful single specification.',
    pairings: ['Cords and a crew neck', 'Dark jeans and a waxed jacket', 'Flannels and a tweed sport coat', 'Moleskins and a gilet'],
    essential: false,
    find: [
      { retailer: 'Morjas', url: 'https://www.morjas.com/search?q=chukka' },
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=suede+chukka+boots+dainite' },
      { retailer: 'Mr Porter', url: 'https://www.mrporter.com/en-gb/mens/search?keywords=chukka+boots' },
    ],
    keywords: ['chukka', 'chukka boot', 'turf boot'],
  },
  {
    id: 'sneaker',
    name: 'Sneaker (Low-Profile / Clean)',
    categoryId: 'shoes',
    what: 'The minimal leather or canvas trainer: low profile, little branding, white or off-white, on a slim cupsole or vulcanised sole. It borrows the tennis shoes of the 1960s–70s — clean lines that let the rest of the outfit speak.',
    history: 'Rubber-soled “sneaks” date to the 1870s, but the clean white leather tennis shoe — Stan Smith, Rod Laver, the German Army Trainer — defined the type menswear settled on. The 2010s minimal-sneaker wave made it the default shoe of a generation.',
    useCase: 'Casual outfits that want freshness rather than polish, and the safety valve that keeps tailoring from stiffness. Keep them genuinely clean — the entire register of the shoe depends on it.',
    pairings: ['Jeans and a heavyweight tee', 'Chinos and an overshirt', 'A knitted polo in summer', 'An unstructured suit, deliberately'],
    essential: true,
    find: [
      { retailer: 'Mr Porter', url: 'https://www.mrporter.com/en-gb/mens/search?keywords=leather+sneakers' },
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=white+leather+minimal+sneakers' },
      { retailer: 'Grailed', url: 'https://www.grailed.com/shop?query=german+army+trainer' },
    ],
    keywords: ['sneaker', 'trainer', 'tennis shoe', 'plimsoll', 'gat'],
  },
  {
    id: 'monk-strap',
    name: 'Monk Strap (Single, Double)',
    categoryId: 'shoes',
    what: 'A buckled shoe with no lacing: one strap (single monk) or two (double monk) across the instep. It sits between Oxford and derby in formality but ahead of both in personality — the buckle is jewellery a man is allowed.',
    history: 'Named for the sandal-strap fastening of European monks’ footwear; the modern double monk was popularised by John Lobb and became a signature of twenty-first-century sartorial dressing — for a while, THE #menswear shoe.',
    useCase: 'Tailoring with intent — suits and flannels where an Oxford would be anonymous. Dark brown double monks with the top buckle done and the lower left undone is the initiated wearer’s convention.',
    pairings: ['A flannel suit', 'Grey trousers and a navy blazer', 'Tweed tailoring', 'Dark denim, carefully, with a jacket'],
    essential: false,
    find: [
      { retailer: 'Morjas', url: 'https://www.morjas.com/search?q=monk' },
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=double+monk+strap+shoes' },
      { retailer: 'Mr Porter', url: 'https://www.mrporter.com/en-gb/mens/search?keywords=monk+strap' },
    ],
    keywords: ['monk strap', 'single monk', 'double monk', 'buckle shoe'],
  },
  {
    id: 'moccasin',
    name: 'Moccasin',
    categoryId: 'shoes',
    what: 'The oldest shoe construction there is: a single piece of leather wrapped under and around the foot, joined to an apron on top with visible hand stitching. Soft, unstructured and flexible — loafers, boat shoes and camp mocs are all its descendants.',
    history: 'Native American in origin — deerskin moccasins predate European contact by centuries. New England makers (Quoddy, Rancourt, Sebago) industrialised the handsewn tradition, and the camp moc became a fixture of American casual style.',
    useCase: 'Soft weekend wear: boat-adjacent summers, cabin-adjacent autumns. A camp moc in chromexcel leather with jeans or shorts is the relaxed cousin of the loafer.',
    pairings: ['Chino shorts and a tee', 'Jeans and a flannel shirt', 'Fatigues and a chore coat', 'Thick socks, indoors, in winter'],
    essential: false,
    find: [
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=handsewn+camp+moccasin' },
      { retailer: 'Etsy', url: 'https://www.etsy.com/search?q=leather+moccasin+men' },
      { retailer: 'Grailed', url: 'https://www.grailed.com/shop?query=rancourt+moccasin' },
    ],
    keywords: ['moccasin', 'camp moc', 'handsewn shoe'],
  },
  {
    id: 'espadrille',
    name: 'Espadrille',
    categoryId: 'shoes',
    what: 'A canvas or cotton upper on a braided jute rope sole — the summer flat of the Mediterranean. The classic is a plain slip-on in natural, navy or black; the sole is the signature and should stay rope, not rubber pretending.',
    history: 'Pyrenean — Catalan and Basque peasants wore “espardenyes” for centuries, the name from esparto grass. Picasso, Dalí and 1950s Riviera style carried them into fashion; Grace Kelly and JFK sealed the deal.',
    useCase: 'Hot weather only, and happily beaten up — they are cheap, honest and disposable by design. Sockless with shorts, linen trousers or rolled chinos; they do not survive rain with dignity.',
    pairings: ['Linen trousers and a camp collar shirt', 'Tailored swim shorts', 'White jeans in the evening', 'A Breton tee on deck'],
    essential: false,
    find: [
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=espadrilles+men+jute' },
      { retailer: 'Etsy', url: 'https://www.etsy.com/search?q=espadrilles+men' },
      { retailer: 'Mr Porter', url: 'https://www.mrporter.com/en-gb/mens/search?keywords=espadrilles' },
    ],
    keywords: ['espadrille', 'alpargata', 'rope sole'],
  },
  {
    id: 'boat-shoe',
    name: 'Boat Shoe',
    categoryId: 'shoes',
    what: 'A handsewn moccasin with leather laces running around the collar and a white, siped rubber sole — the razor-cut grooves grip wet deck. Brown leather, worn sockless, slightly salt-stained: that is the shoe operating as designed.',
    history: 'Paul Sperry invented the siped sole in 1935 after watching his cocker spaniel grip ice, and the Sperry Top-Sider became US Navy issue and then prep canon — The Official Preppy Handbook (1980) treated it as a birthright.',
    useCase: 'Summer casual around water real or imagined: shorts, chinos, jeans rolled once. They are emphatically not office shoes; their charm is entirely off-duty.',
    pairings: ['Chino shorts and a polo', 'White jeans and a Breton tee', 'A rugby shirt on cool evenings', 'An OCBD with sleeves rolled'],
    essential: false,
    find: [
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=sperry+top+sider+boat+shoes' },
      { retailer: 'Mr Porter', url: 'https://www.mrporter.com/en-gb/mens/search?keywords=boat+shoes' },
      { retailer: 'Grailed', url: 'https://www.grailed.com/shop?query=boat+shoes' },
    ],
    keywords: ['boat shoe', 'deck shoe', 'top-sider', 'topsider'],
  },
  {
    id: 'wholecut-oxford',
    name: 'Wholecut Oxford',
    categoryId: 'shoes',
    what: 'An Oxford cut from a single piece of leather — no cap, no seams but the one at the heel. It is the purest expression of shoemaking: nothing to hide behind, so the leather quality and the last shape carry everything.',
    history: 'A bench-made tradition from the great English and continental houses — the wholecut demanded the largest flawless section of the hide and the steadiest hand, so it became a quiet flex among bespoke customers.',
    useCase: 'The dressiest shoe short of patent: evening events, sharp suits, occasions where sleekness is the goal. In black calf it can stand in for formal pumps at black tie.',
    pairings: ['A midnight or charcoal suit', 'Black tie, polished to a mirror', 'A covert coat and dress trousers', 'Nothing casual — it will not bend'],
    essential: false,
    find: [
      { retailer: 'Morjas', url: 'https://www.morjas.com/search?q=wholecut' },
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=wholecut+oxford+shoes' },
      { retailer: 'Mr Porter', url: 'https://www.mrporter.com/en-gb/mens/search?keywords=wholecut+oxford' },
    ],
    keywords: ['wholecut', 'whole cut oxford', 'seamless oxford'],
  },
  {
    id: 'jodhpur-boot',
    name: 'Jodhpur Boot',
    categoryId: 'shoes',
    what: 'An ankle boot fastened by a strap that wraps around the ankle and buckles at the side — no laces, no elastic. The rounded toe and single-buckle silhouette give it an equestrian elegance distinct from both Chelsea and chukka.',
    history: 'Named for Jodhpur in Rajasthan, home of the riding trousers it was designed to partner; British polo players brought both home around 1920. It remains a riding boot in function and a connoisseur’s choice in town.',
    useCase: 'The distinctive alternative to a Chelsea under tailoring or sharp casualwear — the buckle shows just below a trouser hem. Brown calf or suede, with trousers slim enough to reveal it.',
    pairings: ['Slim grey flannels and a tweed coat', 'Dark denim and a peacoat', 'Moleskins and a rollneck', 'A covert coat in town'],
    essential: false,
    find: [
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=jodhpur+boots+men' },
      { retailer: 'Mr Porter', url: 'https://www.mrporter.com/en-gb/mens/search?keywords=jodhpur+boots' },
      { retailer: 'Grailed', url: 'https://www.grailed.com/shop?query=jodhpur+boot' },
    ],
    keywords: ['jodhpur', 'jodhpur boot', 'strap boot'],
  },
  {
    id: 'crepe-sole-boot',
    name: 'Crepe-Sole Boot',
    categoryId: 'shoes',
    what: 'Any boot on a sole of natural crepe — coagulated latex rubber, pale, slightly tacky and endlessly cushioned. The playa shoe of the workwear world: suede or roughout uppers, moc-toe or plain, the sole doing the aesthetic heavy lifting.',
    history: 'Crepe rubber soling spread through the twentieth century on desert boots, playshoes and work boots alike — Clarks in Britain, Red Wing and the moc-toe tradition in America. It trades formality for comfort and never pretends otherwise.',
    useCase: 'Rugged-casual autumn and winter: jeans, fatigues, flannel, canvas. Crepe wears warm-weather badly (it softens in heat) and dresses up never — which is precisely its charm.',
    pairings: ['Selvedge denim and a CPO shirt', 'Fatigue trousers and a chore coat', 'A waffle henley and waxed jacket', 'Heavy socks and moleskins'],
    essential: false,
    find: [
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=crepe+sole+suede+boots' },
      { retailer: 'Grailed', url: 'https://www.grailed.com/shop?query=crepe+sole+boot' },
      { retailer: 'Mr Porter', url: 'https://www.mrporter.com/en-gb/mens/search?keywords=crepe+sole+boots' },
    ],
    keywords: ['crepe sole', 'crepe-sole boot', 'moc toe boot'],
  },
  {
    id: 'driving-shoe',
    name: 'Driving Shoe',
    categoryId: 'shoes',
    what: 'A soft moccasin with rubber pebbles (“gommini”) studding the sole and running up the heel — built so a driver’s heel could pivot on the pedals. Unlined, glove-soft suede in its definitive form.',
    history: 'Gianni Mostile patented the type as Car Shoe in 1963; Tod’s made the gommino a global status object in the 1980s–90s. It is the most Italian of shoes: sprezzatura you can put on your feet.',
    useCase: 'Summer leisure — they are house-and-yacht slippers that happen to be street-legal. Sockless with linen or chinos; the pebbled sole wears fast on pavement, which its owners regard as part of the deal.',
    pairings: ['Linen trousers and a polo', 'White jeans and a camp collar shirt', 'Chino shorts on holiday', 'An unstructured cotton blazer'],
    essential: false,
    find: [
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=driving+shoes+suede+men' },
      { retailer: 'Mr Porter', url: 'https://www.mrporter.com/en-gb/mens/search?keywords=driving+shoes' },
      { retailer: 'Grailed', url: 'https://www.grailed.com/shop?query=driving+loafer' },
    ],
    keywords: ['driving shoe', 'driving loafer', 'gommino', 'car shoe'],
  },
  {
    id: 'brogues',
    name: 'Brogues (Full, Semi, Quarter)',
    categoryId: 'shoes',
    what: 'Not a shoe shape but a decoration system: perforations and serrated edges applied to Oxfords, derbies and boots. Full brogues (wingtips) carry a W-shaped toe cap and maximum perforation; semi-brogues a perforated straight cap; quarter-brogues just the seam detailing.',
    history: 'The holes are Irish and Scottish — rural “bróga” were punched so bog water could drain. Edward VIII wore brogues to golf and the decoration climbed the social ladder into town wear, formality falling as perforation rises.',
    useCase: 'Textured tailoring and country-adjacent smartness: tweed, flannel, cords, denim. A dark brown semi-brogue derby may be the single most versatile smart shoe in Britain.',
    pairings: ['A tweed suit or sport coat', 'Grey flannels and a V-neck', 'Dark denim and a waxed jacket', 'Moleskins and a tattersall shirt'],
    essential: false,
    find: [
      { retailer: 'Morjas', url: 'https://www.morjas.com/search?q=brogue' },
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=full+brogue+wingtip+shoes' },
      { retailer: 'Mr Porter', url: 'https://www.mrporter.com/en-gb/mens/search?keywords=brogues' },
    ],
    keywords: ['brogue', 'brogues', 'wingtip', 'semi brogue', 'quarter brogue'],
  },
  {
    id: 'opera-pump',
    name: 'Opera Pump',
    categoryId: 'shoes',
    what: 'The formal evening slipper: patent leather, a low vamp, and a flat grosgrain bow. It is the correct shoe for white tie and the most elegant option for black tie — a survival of court dress in the modern wardrobe.',
    history: 'Directly descended from eighteenth-century court shoes, standardised in the nineteenth century for evening dress. Fred Astaire danced in them; a certain kind of dresser never let them go.',
    useCase: 'Black tie and white tie only — and, for the confident, velvet-jacket dinners at home. With silk hose at the most formal end; never in daylight.',
    pairings: ['A dinner suit with grosgrain lapels', 'White tie and tails', 'A velvet smoking jacket', 'Midnight blue everything'],
    essential: false,
    find: [
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=opera+pumps+patent+men' },
      { retailer: 'Mr Porter', url: 'https://www.mrporter.com/en-gb/mens/search?keywords=evening+pumps' },
      { retailer: 'Etsy', url: 'https://www.etsy.com/search?q=opera+pump+men+patent' },
    ],
    keywords: ['opera pump', 'court shoe', 'evening pump', 'grosgrain bow shoe'],
  },

  // =========================================================================
  // OUTERWEAR
  // =========================================================================
  {
    id: 'harrington-jacket',
    name: 'Harrington Jacket',
    categoryId: 'outerwear',
    what: 'A hip-length blouson in cotton or cotton-blend with a stand-up two-button collar, raglan sleeves, slanted flap pockets and — canonically — a Fraser tartan lining. Light, neat and endlessly composed.',
    history: 'Baracuta of Manchester made the original G9 in 1937 as a golf jacket. The nickname came from Rodney Harrington in Peyton Place (1964); Steve McQueen, James Dean and every mod and skinhead revival since made it a subcultural constant.',
    useCase: 'The spring-and-autumn casual jacket: over polos, tees and OCBDs, with jeans or chinos. Stone, navy and dark green are all canonical; it wants trim trousers to balance the bloused body.',
    pairings: ['A white tee and raw denim', 'A polo and chinos (the McQueen)', 'An OCBD and desert boots', 'A crew neck when it cools'],
    essential: true,
    find: [
      { retailer: 'Baracuta at eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=baracuta+g9+harrington' },
      { retailer: 'Private White V.C.', url: 'https://www.privatewhitevc.com/search?q=harrington' },
      { retailer: 'Grailed', url: 'https://www.grailed.com/shop?query=harrington+jacket' },
    ],
    keywords: ['harrington', 'g9', 'blouson jacket', 'golf jacket'],
  },
  {
    id: 'field-jacket',
    name: 'Field Jacket (M-65 Style)',
    categoryId: 'outerwear',
    what: 'The military field coat: four bellows pockets, a concealed hood in the collar, epaulettes, drawstring waist, in olive cotton sateen or nyco. Everything about it is functional, which is why it looks so good doing nothing.',
    history: 'The US Army’s M-1965 refined the M-43 and M-51 of WWII and Korea, serving through Vietnam. De Niro in Taxi Driver made it cinematic; every army-surplus generation since made it a civilian staple.',
    useCase: 'The utility layer for autumn: over knits, flannels and tees, with denim or fatigues. The four pockets replace a bag for short outings — that is half its point.',
    pairings: ['A heavyweight tee and jeans', 'A Shetland and cords', 'A hooded sweatshirt underneath', 'Desert or crepe-sole boots'],
    essential: true,
    find: [
      { retailer: 'eBay (military surplus)', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=m65+field+jacket+og107' },
      { retailer: 'Universal Works', url: 'https://www.universalworks.co.uk/search?q=field+jacket' },
      { retailer: 'Grailed', url: 'https://www.grailed.com/shop?query=m65+field+jacket' },
    ],
    keywords: ['field jacket', 'm65', 'm-65', 'military jacket'],
  },
  {
    id: 'overcoat',
    name: 'Overcoat',
    categoryId: 'outerwear',
    what: 'The tailored wool coat worn over everything: single- or double-breasted, knee-length or below, in melton, herringbone or cashmere blends. It is the garment that makes winter dressing look intentional rather than endured.',
    history: 'The great nineteenth-century coat tradition — Chesterfield, Guards coat, Ulster — codified the type: town coats over tailoring, each with its own collar and button grammar. The names blur now; the silhouette endures.',
    useCase: 'Over tailoring by right, over knitwear and denim by modern habit — a navy or charcoal overcoat instantly dresses whatever is under it. Buy it roomy enough for a jacket beneath and long enough to cover the seat.',
    pairings: ['A suit and scarf', 'A rollneck and flannels', 'A hoodie and jeans (the high-low classic)', 'Leather gloves and derbies'],
    essential: true,
    find: [
      { retailer: 'Berg & Berg', url: 'https://bergbergstore.com/search?q=coat' },
      { retailer: 'Private White V.C.', url: 'https://www.privatewhitevc.com/search?q=overcoat' },
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=wool+overcoat+men+crombie' },
    ],
    keywords: ['overcoat', 'topcoat', 'wool coat', 'winter coat'],
  },
  {
    id: 'trench-coat',
    name: 'Trench Coat',
    categoryId: 'outerwear',
    what: 'The belted gabardine raincoat with military furniture: double-breasted front, storm flap at the shoulder, epaulettes, cuff straps and a back yoke that sheds water. Stone (“honey”) is the icon; navy is the stealth option.',
    history: 'Burberry and Aquascutum both claim it; the name comes from the WWI trenches, where officers wore it over their uniforms — the D-rings and flaps all had jobs. Bogart in Casablanca turned military kit into cinema’s most romantic coat.',
    useCase: 'Rain over smart clothes — suits, blazers, dresses of any register. Belt it properly or tie the belt behind; a flapping loose trench serves no one.',
    pairings: ['A grey suit and umbrella', 'A rollneck and flannels', 'Dark jeans and a shetland at the weekend', 'A silk scarf at the neck'],
    essential: true,
    find: [
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=gabardine+trench+coat+men' },
      { retailer: 'Mr Porter', url: 'https://www.mrporter.com/en-gb/mens/search?keywords=trench+coat' },
      { retailer: 'Grailed', url: 'https://www.grailed.com/shop?query=burberry+trench' },
    ],
    keywords: ['trench coat', 'trench', 'belted raincoat'],
  },
  {
    id: 'raincoat',
    name: 'Raincoat / Mac',
    categoryId: 'outerwear',
    what: 'The single-breasted, minimal rain coat — fly front, hidden buttons, clean collar, in rubberised cotton (the true Mackintosh), bonded cotton or modern technical cloth. The trench’s quiet sibling: no belt, no drama.',
    history: 'Charles Macintosh patented rubberised cloth in 1823, and “mac” became British English for any raincoat. The minimal single-breasted form became the commuter’s default and, via 1960s cinema, a byword for understatement.',
    useCase: 'Wet days over anything — its plainness is the point, vanishing over a suit as easily as over jeans. A knee-length navy or stone mac is the least demanding coat a wardrobe can hold.',
    pairings: ['A suit on a wet commute', 'A crew neck and chinos', 'A rollneck and white jeans in spring rain', 'A flat cap, unironically'],
    essential: false,
    find: [
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=mackintosh+raincoat+men' },
      { retailer: 'Private White V.C.', url: 'https://www.privatewhitevc.com/search?q=mac' },
      { retailer: 'Grailed', url: 'https://www.grailed.com/shop?query=mackintosh+coat' },
    ],
    keywords: ['raincoat', 'mac', 'mackintosh', 'rubberised coat'],
  },
  {
    id: 'blazer',
    name: 'Blazer',
    categoryId: 'outerwear',
    what: 'The navy jacket with metal or horn buttons worn as outerwear-cum-tailoring — single-breasted with patch pockets in its easy form, double-breasted with gilt buttons in its club form. Not a suit jacket: the cloth (hopsack, serge, flannel) is made to stand alone.',
    history: 'Two origin stories share the name: the scarlet “blazing” rowing jackets of Cambridge’s Lady Margaret Boat Club, and the brass-buttoned reefer jackets of the Royal Navy — HMS Blazer’s crew allegedly smartened up for Queen Victoria in 1837.',
    useCase: 'The universal donor of tailoring: over flannels for smart, over jeans for sharp-casual, over chinos for everything in between. If a wardrobe holds one tailored jacket, it is this.',
    pairings: ['Grey flannels and loafers', 'An OCBD and knit tie', 'Dark denim and Chelsea boots', 'White jeans in summer'],
    essential: true,
    find: [
      { retailer: "Drake's", url: 'https://drakes.com/search?q=blazer' },
      { retailer: 'Berg & Berg', url: 'https://bergbergstore.com/search?q=blazer' },
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=navy+hopsack+blazer' },
    ],
    keywords: ['blazer', 'navy blazer', 'club jacket'],
  },
  {
    id: 'chore-coat',
    name: 'Chore Coat',
    categoryId: 'outerwear',
    what: 'The French worker’s jacket: boxy, unlined, three or four patch pockets, a simple shirt-style collar, in cotton drill or moleskin. “Bleu de travail” blue is the heritage colour; the shape is the whole design.',
    history: 'Standard-issue French workwear from the 1880s — the blue dye was cheapest and hid grease. Bill Cunningham photographed decades of New York fashion wearing one; the 2010s workwear revival made it the new casual blazer.',
    useCase: 'The everyday third layer, spring and autumn: over tees, henleys and flannels. It carries as much as a small bag and looks better with every wash and fray.',
    pairings: ['A Breton tee and jeans', 'A henley and fatigues', 'A flannel shirt in autumn', 'White tee, ecru denim, summer evening'],
    essential: true,
    find: [
      { retailer: 'Universal Works', url: 'https://www.universalworks.co.uk/search?q=bakers+jacket' },
      { retailer: 'eBay (vintage)', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=french+chore+jacket+bleu+de+travail' },
      { retailer: 'Etsy', url: 'https://www.etsy.com/search?q=french+chore+coat' },
    ],
    keywords: ['chore coat', 'chore jacket', 'french work jacket', 'bleu de travail'],
  },
  {
    id: 'barn-jacket',
    name: 'Barn Jacket',
    categoryId: 'outerwear',
    what: 'The American country cousin of the chore coat: hip-length cotton canvas or duck, corduroy collar, big flap pockets, often blanket- or flannel-lined. Boxier and warmer than a chore coat, built for firewood and errands.',
    history: 'American farm-supply workwear — Carhartt’s duck chore coats from 1889 onward — filtered through Ralph Lauren and L.L.Bean into weekend-gentry canon in the 1980s. The “barn coat” name stuck to the polished versions.',
    useCase: 'Cold-morning casual: over flannels and knits with jeans, cords or moleskins. It thrives on wear — a pristine barn jacket is a contradiction in terms.',
    pairings: ['A flannel shirt and jeans', 'A Shetland and cords', 'A beanie and leather gloves', 'Duck boots in genuinely foul weather'],
    essential: false,
    find: [
      { retailer: 'Filson', url: 'https://www.filson.com/search?q=jacket' },
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=barn+jacket+canvas+corduroy+collar' },
      { retailer: 'Grailed', url: 'https://www.grailed.com/shop?query=barn+jacket' },
    ],
    keywords: ['barn jacket', 'barn coat', 'duck canvas jacket'],
  },
  {
    id: 'peacoat',
    name: 'Peacoat',
    categoryId: 'outerwear',
    what: 'The naval short coat: double-breasted in heavy midnight melton wool, broad Ulster collar that stands against wind, slash handwarmer pockets, anchor-stamped buttons. Hip-length and built like armour.',
    history: 'From the Dutch “pijjekker” (coarse-wool jacket); standardised by the Royal and US Navies through the nineteenth century for deck watches. Surplus stores put a generation of civilians in them after both wars.',
    useCase: 'Proper cold over casual and semi-smart clothes — the collar up against wind is not an affectation, it is the design. Navy with denim and boots is the eternal setting.',
    pairings: ['A rollneck and raw denim', 'A Breton tee in early winter', 'Grey flannels for the smart version', 'A watch cap, inevitably'],
    essential: true,
    find: [
      { retailer: 'Private White V.C.', url: 'https://www.privatewhitevc.com/search?q=peacoat' },
      { retailer: 'eBay (naval surplus)', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=us+navy+peacoat+melton' },
      { retailer: 'Grailed', url: 'https://www.grailed.com/shop?query=peacoat' },
    ],
    keywords: ['peacoat', 'pea coat', 'reefer jacket'],
  },
  {
    id: 'duffle-coat',
    name: 'Duffle Coat',
    categoryId: 'outerwear',
    what: 'The hooded wool coat fastened with wooden or horn toggles through rope or leather loops — workable in gloves, which was the point. Heavy duffel wool, a roomy cut and the only hood in classic tailored outerwear.',
    history: 'Named for the Belgian town of Duffel and adopted by the Royal Navy for convoy watches; Field Marshal Montgomery’s camel version made it famous. Post-war surplus dressed students, CND marchers and Paddington Bear alike.',
    useCase: 'Deep-winter casual: over knitwear and denim, cords or moleskins. It is the warmest-hearted coat in menswear — boyish in camel, serious in navy.',
    pairings: ['A Guernsey or Aran jumper', 'Cords and desert boots', 'A college scarf, worn long', 'Jeans and a flannel shirt'],
    essential: false,
    find: [
      { retailer: 'Gloverall at eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=gloverall+duffle+coat' },
      { retailer: 'Mr Porter', url: 'https://www.mrporter.com/en-gb/mens/search?keywords=duffle+coat' },
      { retailer: 'Grailed', url: 'https://www.grailed.com/shop?query=duffle+coat' },
    ],
    keywords: ['duffle coat', 'duffel coat', 'toggle coat'],
  },
  {
    id: 'waxed-jacket',
    name: 'Waxed Jacket (Barbour Style)',
    categoryId: 'outerwear',
    what: 'The British country rain jacket in waxed cotton — olive or navy, corduroy collar, big bellows pockets, tartan lining, brass zip. It is not waterproof so much as weather-indifferent, and it re-waxes rather than wears out.',
    history: 'J. Barbour & Sons of South Shields outfitted fishermen and gamekeepers from 1894; the Bedale (1980, for riding) and Beaufort (1983, for shooting) became the countryside’s uniform and then the city’s favourite piece of borrowed authenticity.',
    useCase: 'Rain, dogs, weekends and the entire British autumn: over knitwear, flannel and tweed. It should fit roomy and be worn hard — the patina of wax, mud and repair IS the garment.',
    pairings: ['A Shetland and cords', 'A tattersall shirt and moleskins', 'Jeans and wellies or country boots', 'A flat cap and a long-suffering dog'],
    essential: true,
    find: [
      { retailer: 'Barbour at eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=barbour+bedale+beaufort+waxed' },
      { retailer: 'Private White V.C.', url: 'https://www.privatewhitevc.com/search?q=waxed' },
      { retailer: 'Grailed', url: 'https://www.grailed.com/shop?query=barbour+waxed+jacket' },
    ],
    keywords: ['waxed jacket', 'wax jacket', 'barbour', 'waxed cotton'],
  },
  {
    id: 'gilet',
    name: 'Gilet / Vest',
    categoryId: 'outerwear',
    what: 'The sleeveless insulating layer — quilted down, fleece-lined or waxed — worn over knitwear and under coats. It warms the core and frees the arms, which is why the country set and the cyclists both swear by it.',
    history: 'From hunting and alpine wear: the quilted “husky” gilet became landed-gentry shorthand in 1970s–80s Britain, while down vests were doing parallel service in the American outdoors tradition.',
    useCase: 'The in-between layer: autumn mornings, winter layering, spring evenings. Over a flannel shirt or Shetland with jeans or cords, or under an overcoat when the temperature truly drops.',
    pairings: ['A flannel shirt and jeans', 'A crew neck and chinos', 'Under a waxed jacket in deep winter', 'A rollneck for the alpine look'],
    essential: false,
    find: [
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=quilted+gilet+men' },
      { retailer: 'Mr Porter', url: 'https://www.mrporter.com/en-gb/mens/search?keywords=gilet' },
      { retailer: 'Filson', url: 'https://www.filson.com/search?q=vest' },
    ],
    keywords: ['gilet', 'vest', 'bodywarmer', 'body warmer', 'quilted vest'],
  },
  {
    id: 'blouson',
    name: 'Blouson',
    categoryId: 'outerwear',
    what: 'The umbrella term for the short, bloused jacket that gathers at a fitted waistband — the harrington is one, the bomber another, the suede A-1 style a third. The silhouette balloons softly above the hem: hence the name.',
    history: 'The shape is aviation and sportswear born — flight jackets needed to end at the waist to clear a cockpit harness, golf jackets to clear a swing. French usage gave menswear the useful catch-all word.',
    useCase: 'Casual outfits that want a neat, cropped top half — the blouson flatters by ending at the natural waist and letting trousers run long. Suede versions are the smartest; keep what is under it trim.',
    pairings: ['A knitted polo and flannels', 'A tee and straight jeans', 'A rollneck in suede-blouson form', 'Chinos and loafers'],
    essential: false,
    find: [
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=suede+blouson+jacket+men' },
      { retailer: 'Mr Porter', url: 'https://www.mrporter.com/en-gb/mens/search?keywords=blouson+jacket' },
      { retailer: 'Grailed', url: 'https://www.grailed.com/shop?query=suede+blouson' },
    ],
    keywords: ['blouson', 'valstar', 'a-1 jacket', 'suede jacket'],
  },
  {
    id: 'teba-jacket',
    name: 'Teba Jacket',
    categoryId: 'outerwear',
    what: 'The Spanish shirt-jacket hybrid: soft, completely unstructured, with a shirt-like collar that has no lapel roll, shirt-style cuffs, and patch pockets. It is tailoring with the tailoring removed — a jacket that behaves like a cardigan.',
    history: 'Named for the Conde de Teba, who had his shooting jackets made soft for comfort in the field; Spanish makers (Justo Gimeno above all) kept the pattern alive until the soft-tailoring movement rediscovered it.',
    useCase: 'Where a blazer is too formal and a chore coat too rough: smart-casual with knitwear, flannels or good denim. It packs flat and shrugs off crumpling — the great travel jacket.',
    pairings: ['A rollneck and grey flannels', 'An OCBD and chinos', 'A polo in summer tebas of linen', 'Dark denim and loafers'],
    essential: false,
    find: [
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=teba+jacket' },
      { retailer: 'Grailed', url: 'https://www.grailed.com/shop?query=teba+jacket' },
      { retailer: 'Etsy', url: 'https://www.etsy.com/search?q=teba+jacket' },
    ],
    keywords: ['teba', 'teba jacket', 'spanish jacket'],
  },
  {
    id: 'loden-janker',
    name: 'Loden Janker',
    categoryId: 'outerwear',
    what: 'The Austrian/Bavarian traditional wool jacket: boiled or milled loden wool (dense, water-shedding, usually deep green or grey), a stand or short collar, horn buttons and a trim, cardigan-like cut. Tracht — folk dress — that reads as quiet sophistication abroad.',
    history: 'Loden cloth comes from Tyrolean peasant weaving — the wool is washed, felted and brushed until it turns weather. The Janker is its jacket form, worn for centuries in the Alps and adopted by everyone from Austrian aristocracy to mid-century intellectuals.',
    useCase: 'Cold-weather smart-casual with a point of view: over rollnecks and flannels, instead of a blazer or cardigan. The horn buttons and green wool carry the character; keep everything else plain.',
    pairings: ['A cream rollneck and grey flannels', 'Moleskin trousers and brogues', 'A tattersall shirt and knit tie', 'Cords and chukka boots'],
    essential: false,
    find: [
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=loden+janker+jacket' },
      { retailer: 'Etsy', url: 'https://www.etsy.com/search?q=loden+janker+men' },
      { retailer: 'Grailed', url: 'https://www.grailed.com/shop?query=loden+jacket' },
    ],
    keywords: ['loden', 'janker', 'tyrolean jacket', 'austrian jacket', 'trachten'],
  },
  {
    id: 'saharienne',
    name: 'Saharienne (Safari Jacket)',
    categoryId: 'outerwear',
    what: 'The safari jacket: four bellows pockets, a belted waist, epaulettes and a shirt collar, in sand-coloured cotton drill or linen. Halfway between shirt and jacket, it is the most elegant thing hot weather allows a man to wear over another layer.',
    history: 'Born of British colonial bush kit, it became fashion when Yves Saint Laurent’s 1968 “saharienne” collection put it on both sexes. Roger Moore’s Bond and Hemingway’s safaris fixed the male archetype.',
    useCase: 'Warm-weather smart-casual and travel — over a polo, tee or linen shirt with tailored trousers or chinos. Belt it loosely or knot the belt behind; the pockets replace a bag entirely.',
    pairings: ['A knitted polo and cream trousers', 'A linen shirt and shorts on holiday', 'A tee and chinos in the city', 'Suede loafers or desert boots'],
    essential: false,
    find: [
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=safari+jacket+saharienne' },
      { retailer: 'Mr Porter', url: 'https://www.mrporter.com/en-gb/mens/search?keywords=safari+jacket' },
      { retailer: 'Grailed', url: 'https://www.grailed.com/shop?query=safari+jacket' },
    ],
    keywords: ['saharienne', 'safari jacket', 'bush jacket'],
  },
  {
    id: 'balmacaan-coat',
    name: 'Balmacaan Coat',
    categoryId: 'outerwear',
    what: 'A loose, single-breasted coat with raglan sleeves and a small, round “bal” collar that buttons to the throat — no lapels to speak of. The raglan shoulder gives it an easy, sloping swing that suits knitwear as well as suits.',
    history: 'Named for an estate near Inverness, it was the Scottish country raincoat — tweed or gabardine — of the late nineteenth century. Ivy style adopted it (the “bal collar”), and Japanese menswear made the oversized balmacaan a modern classic.',
    useCase: 'The relaxed alternative to a structured overcoat: over knitwear, denim and soft tailoring. In tweed it is a country coat; in gabardine, city rainwear with more character than a mac.',
    pairings: ['A rollneck and wide trousers', 'A crew neck and jeans', 'A suit when you want ease over sharpness', 'A scarf filling the round collar'],
    essential: false,
    find: [
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=balmacaan+raglan+coat' },
      { retailer: 'Grailed', url: 'https://www.grailed.com/shop?query=balmacaan+coat' },
      { retailer: 'Etsy', url: 'https://www.etsy.com/search?q=balmacaan+coat+vintage' },
    ],
    keywords: ['balmacaan', 'bal collar coat', 'raglan raincoat'],
  },
  {
    id: 'ulster-coat',
    name: 'Ulster Coat',
    categoryId: 'outerwear',
    what: 'The heaviest of the classic overcoats: double-breasted, six-to-eight buttons, a wide “Ulster collar” with broad, low-notch lapels that flip up to guard the face, patch or flap pockets, often a half-belt at the back. Tweed or heavy melton, built for actual weather.',
    history: 'From Ulster, Ireland, where the frieze cloth originals were woven in the 1860s; it was the great travelling coat of the Victorian era — Sherlock Holmes wears one in the early stories. The polo coat is its camel-hair descendant.',
    useCase: 'Deep winter over anything from suits to jumpers — its scale wants either tailoring or bulk beneath. This is the coat for the man who walks in winter and means it.',
    pairings: ['A tweed suit and scarf', 'A rollneck and heavy flannels', 'Leather gloves and a felt hat', 'Cords and boots at the weekend'],
    essential: false,
    find: [
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=ulster+overcoat+tweed' },
      { retailer: 'Grailed', url: 'https://www.grailed.com/shop?query=ulster+coat' },
      { retailer: 'Etsy', url: 'https://www.etsy.com/search?q=ulster+overcoat' },
    ],
    keywords: ['ulster', 'ulster coat', 'ulster collar', 'polo coat'],
  },
  {
    id: 'covert-coat',
    name: 'Covert Coat',
    categoryId: 'outerwear',
    what: 'A single-breasted, fly-fronted town coat in covert cloth — a tough, mottled green-fawn twill — with its signature four (sometimes five) rows of stitching at the cuffs and hem, and often a velvet collar. Knee-length, trim and unmistakably British.',
    history: 'Built for riding to hounds — “covert” (pronounced “cover”) is where game shelters; the stitched rows stopped the hem tearing in thorn. It moved from the hunt to the City, where it remains the connoisseur’s short overcoat.',
    useCase: 'Over tailoring — its fawn colour flatters navy and grey suits particularly — or over knitwear and cavalry twills at the weekend. The velvet collar version leans racing-gent; wear it with confidence or not at all.',
    pairings: ['A navy suit and burgundy loafers', 'Grey flannels and a tweed jacket', 'A tattersall shirt and knit tie', 'Chelsea boots and cords'],
    essential: false,
    find: [
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=covert+coat+velvet+collar' },
      { retailer: 'Grailed', url: 'https://www.grailed.com/shop?query=covert+coat' },
      { retailer: 'Etsy', url: 'https://www.etsy.com/search?q=covert+coat+men' },
    ],
    keywords: ['covert coat', 'covert cloth', 'velvet collar coat'],
  },
  {
    id: 'raglan-coat',
    name: 'Raglan Coat',
    categoryId: 'outerwear',
    what: 'Any coat cut with raglan sleeves — the sleeve runs in one piece to the collar, with a diagonal seam from underarm to neck instead of a set-in shoulder. The result: soft, sloping shoulders, ease of movement, and a forgiving fit over anything.',
    history: 'Named for Lord Raglan, who lost an arm at Waterloo and had coats cut for easier dressing. The construction became the standard for rain and travel coats — it sheds water down the seam and fits many shoulders from one pattern.',
    useCase: 'The easy overcoat or raincoat — particularly good on broad or sloping shoulders that fight set-in coats, and over thick knitwear. It always reads a little more relaxed than its structured equivalent.',
    pairings: ['Knitwear of any weight beneath', 'A suit, for the soft-shouldered look', 'A scarf — the neckline invites one', 'Denim and boots at the casual end'],
    essential: false,
    find: [
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=raglan+sleeve+overcoat' },
      { retailer: 'Grailed', url: 'https://www.grailed.com/shop?query=raglan+coat' },
      { retailer: 'Mr Porter', url: 'https://www.mrporter.com/en-gb/mens/search?keywords=raglan+coat' },
    ],
    keywords: ['raglan coat', 'raglan sleeve', 'split raglan'],
  },
  {
    id: 'car-coat',
    name: 'Car Coat',
    categoryId: 'outerwear',
    what: 'A straight, thigh-length coat — shorter than an overcoat, longer than a jacket — with a clean single-breasted front and minimal detail. The length is the definition: it clears a car seat without bunching.',
    history: 'Born with the motor car: Edwardian drivers needed weatherproof coats that worked seated, and the shortened “motoring coat” evolved into the mid-century suburban classic as car ownership spread.',
    useCase: 'Commuting and city winters — it does the smartness of an overcoat without the sweep, and suits shorter men particularly. Over a suit or over a jumper and jeans equally.',
    pairings: ['A suit for the commute', 'A crew neck and chinos', 'A rollneck and dark denim', 'Leather gloves — it is a driving coat'],
    essential: false,
    find: [
      { retailer: 'Private White V.C.', url: 'https://www.privatewhitevc.com/search?q=coat' },
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=wool+car+coat+men' },
      { retailer: 'Mr Porter', url: 'https://www.mrporter.com/en-gb/mens/search?keywords=car+coat' },
    ],
    keywords: ['car coat', 'three quarter coat', 'short overcoat'],
  },
  {
    id: 'deck-jacket',
    name: 'Deck Jacket',
    categoryId: 'outerwear',
    what: 'The naval work jacket: hip-length, hook-fastened or zipped, in tightly woven cotton (jungle cloth) with a wool or alpaca lining — the N-1 is the archetype. Stubby, warm and almost indestructible.',
    history: 'The US Navy’s N-1 deck jacket of WWII, issued in khaki and navy for winter deck duty. Surplus and reproduction culture — especially Japanese — elevated it into one of the great casual winter jackets.',
    useCase: 'Cold casual wear where a peacoat feels dressy: denim, fatigues, boots and heavy knits. The fuzzy collar worn up is both the look and the function.',
    pairings: ['A rollneck and raw denim', 'A hooded sweatshirt beneath', 'Fatigues and service boots', 'A watch cap and work gloves'],
    essential: false,
    find: [
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=n-1+deck+jacket' },
      { retailer: 'Grailed', url: 'https://www.grailed.com/shop?query=n1+deck+jacket' },
      { retailer: 'Etsy', url: 'https://www.etsy.com/search?q=n1+deck+jacket' },
    ],
    keywords: ['deck jacket', 'n-1', 'n1 jacket', 'jungle cloth'],
  },
  {
    id: 'shirt-jacket',
    name: 'Shirt Jacket (Shacket)',
    categoryId: 'outerwear',
    what: 'The jacket built on a shirt’s pattern: shirt collar, button front, but in jacket-weight cloth (wool, heavy cotton, blanket check) and cut roomy for layering. It overlaps the overshirt/CPO family — the shacket is simply its most jacket-like end.',
    history: 'Workwear catalogues sold “shirt-jacs” through the mid-twentieth century — Pendleton’s wool board shirts and hunting jac-shirts among the best known. The portmanteau “shacket” arrived with the 2010s layering boom.',
    useCase: 'Autumn’s answer to “do I need a coat?”: over a tee or light knit, under nothing. Blanket checks and plaids lean outdoorsy; solid navy or olive wool versions pass almost as tailoring.',
    pairings: ['A heavyweight tee and jeans', 'A henley and cords', 'Layered under a parka in deep winter', 'Boots — crepe or commando sole'],
    essential: false,
    find: [
      { retailer: 'Universal Works', url: 'https://www.universalworks.co.uk/search?q=shirt+jacket' },
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=wool+shirt+jacket+men' },
      { retailer: 'Grailed', url: 'https://www.grailed.com/shop?query=shacket' },
    ],
    keywords: ['shacket', 'shirt jacket', 'jac shirt', 'pendleton jacket'],
  },
  {
    id: 'noragi',
    name: 'Noragi',
    categoryId: 'outerwear',
    what: 'The Japanese farmer’s jacket: a kimono-derived wrap or open front with no buttons (or simple ties), dropped shoulders, and traditionally indigo-dyed cotton, often sashiko-stitched or boro-patched. Worn open, it drapes like no Western jacket.',
    history: 'Noragi means “field wear” — rural workwear of Edo-period Japan, stitched and re-stitched (boro) because cotton was precious. Japanese heritage brands and the American workwear revival brought it into global menswear.',
    useCase: 'The characterful third layer for casual outfits — worn open over a tee or henley, sitting somewhere a cardigan and a chore coat cannot reach. Let it be the only statement in the outfit.',
    pairings: ['A white tee and wide jeans', 'A henley and fatigues', 'Ecru or indigo everything', 'Simple canvas sneakers'],
    essential: false,
    find: [
      { retailer: 'Etsy', url: 'https://www.etsy.com/search?q=noragi+jacket' },
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=noragi+indigo+jacket' },
      { retailer: 'Grailed', url: 'https://www.grailed.com/shop?query=noragi' },
    ],
    keywords: ['noragi', 'kimono jacket', 'sashiko jacket', 'boro'],
  },
  {
    id: 'parka',
    name: 'Parka',
    categoryId: 'outerwear',
    what: 'The long, hooded cold-weather coat — fishtail (M-51/M-65) in its military form, down-filled in its expedition form. The hood is the defining organ; the length covers the seat; everything else is insulation strategy.',
    history: 'The word and idea are Inuit; the US Army’s Korean War fishtail parkas became mod culture’s outer shell (worn to protect suits on scooters), while Canadian expedition parkas defined the down lineage.',
    useCase: 'Genuine cold and wet, over anything casual — it is the practical winter coat that never pretends to tailoring. A fishtail over a suit remains one of subculture’s great images, but that is an advanced move.',
    pairings: ['A heavy rollneck and jeans', 'A hoodie and cargo trousers', 'A Harrington layered beneath (mod-style)', 'Boots with actual tread'],
    essential: false,
    find: [
      { retailer: 'eBay (surplus)', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=m51+fishtail+parka' },
      { retailer: 'Mr Porter', url: 'https://www.mrporter.com/en-gb/mens/search?keywords=parka' },
      { retailer: 'Grailed', url: 'https://www.grailed.com/shop?query=fishtail+parka' },
    ],
    keywords: ['parka', 'fishtail', 'm51', 'hooded coat'],
  },
  {
    id: 'bomber-jacket',
    name: 'Bomber Jacket (MA-1 / A-2)',
    categoryId: 'outerwear',
    what: 'The flight jacket in its two great forms: the leather A-2 (shirt collar, zip front, ribbed hem) and the nylon MA-1 (sage green, orange rescue lining, knit collar). Cropped to the waist, bloused, and heavy with borrowed valour.',
    history: 'US Army Air Corps issue — the A-2 from 1931, the MA-1 from the jet-age 1950s when leather froze at altitude. Surplus stores handed them to skinheads, punks and eventually every high-fashion runway.',
    useCase: 'Sharp casualwear — the MA-1 with slim trousers and clean sneakers, the A-2 with denim and boots. The blouson cut wants the layers under it thin and the trousers trim.',
    pairings: ['A white tee and grey trousers', 'A rollneck under the MA-1', 'Raw denim and service boots (A-2)', 'A hoodie, carefully, for the streetwear read'],
    essential: false,
    find: [
      { retailer: 'eBay', url: 'https://www.ebay.co.uk/sch/i.html?_nkw=alpha+industries+ma-1+bomber' },
      { retailer: 'Grailed', url: 'https://www.grailed.com/shop?query=ma-1+bomber' },
      { retailer: 'Mr Porter', url: 'https://www.mrporter.com/en-gb/mens/search?keywords=bomber+jacket' },
    ],
    keywords: ['bomber', 'ma-1', 'a-2 jacket', 'flight jacket'],
  },
];
